### ISSUE TITLE
Issue with interpolated values

### ISSUE THREAD

**Issue by ynnoj** [jamesarosen/ember-i18n#175]
Getting an Ember error when trying to use interpolated values. Running Ember 1.8, jQuery 1.11.1 and Handlebars 1.3.0.

> EmberError: Something you did caused a view to re-render after it rendered but before it was inserted into the DOM.

```javascript
users: {
        table: {
            title: {
                one: "user",
                other: "{{count}} users"
            }
       }
}
```

```handlebars
{{t 'users.table.title' countBinding='filteredContent.length'}}
```

Thanks!

**Comment by jamesarosen** [comment]
It's been a while since there was any movement here. I'm going to close this, but please reopen if you find a test case. I'm happy to release a patch for the v3 series. Or you may wish to jump to v4.
