### ISSUE TITLE
Update dependency to handlebars 2.0.0

### ISSUE THREAD

**Issue by dmoreno** [jamesarosen/ember-i18n#186]
EmberJS has handlebars 2.0.0 as dependecy. When you use ember-18n with bower, it warns about an incompatibility between emberjs and ember-i18n.

Now, is it possible to use ember-i18n with handlebars 2.0.0?

**Comment by jamesarosen** [comment]
All the Ember-I18n v3.0.0-beta.* versions work with Ember 1.9+ and Handlebars 2.0. See, for example, https://travis-ci.org/jamesarosen/ember-i18n/jobs/45055849

**Comment by dmoreno** [comment]
Great! Thanks for your work!
