### ISSUE TITLE
Another issue with interpolated values

### ISSUE THREAD

**Issue by shareit** [jamesarosen/ember-i18n#187]
I'm using:
Ember      : 1.7.1
Ember Data : 1.0.0-beta.8.2a68c63a
Handlebars : 1.3.0
Ember i18n: 2.92

I have the following translation `lblPager: "Page {{currentPage}} of {{totalPages}}"`.
`currentPage` and `totalPages` are two properties defined in the corresponding controller. These properties are automatically calculated based on the model changes. 

The problem is that the second param (`totalPages`) is not replaced correctly by the `t` helper every time. I added some logs in the controller properties and it seems that the properties are correctly calculated in the controller, but the `t` helper did not know when to update the parameters.

More than that I have replaced the `{{t "lblProofStudioPager" currentPageBinding="currentPageNumber" totalPagesBinding="totalPages"}}` with the following:  `Page {{currentPageNumber}} of {{totalPages}}` and the problem is solved, meaning that the two parameters (`currentPageNumber` and `totalPages`) are displayed correctly every time but the strings are not translated any more.

Probably the best solution will be to make a demo page but I hoping that other users found this issue before me. Please advice.

Thanks,

**Comment by locks** [comment]
(sorry for editing your post, I just tried to make it slightly more readable on GH)

**Comment by jamesarosen** [comment]
@shareit have you tried making a failing test? The [t helper specs](https://github.com/jamesarosen/ember-i18n/blob/master/spec/translateHelperSpec.js) don't have a test for multiple interpolations in the same string. It might be worth adding one.

**Comment by shareit** [comment]
@jamesarosen One if working as expected. I have multiple translations in the application that contains only one interpolation in the same string.

**Comment by jcbvm** [comment]
In my app I have a lot of multiple bindings in one translation, sometimes even 3 or 4 and it is working properly, so for me it seems somewhere else things are going wrong here.
