### ISSUE TITLE
complete example of ember-i18n using select menu ?

### ISSUE THREAD

**Issue by tapanbavaliya** [jamesarosen/ember-i18n#190]
can you provide me the complete example of ember-i18n when select the different language from select menu.

**Comment by jamesarosen** [comment]
You'll have to reload the page if the locale changes. As noted in the README, Ember-I18n doesn't have live bindings to the locale (for performance reasons).

**Comment by tapanbavaliya** [comment]
@jamesarosen  thank you for your answer but can you provide example folder in project because i am new in ember so its bit confusing to me how to code using ember-i18n liberty only refereeing doc.

and how "reload the page if the locale changes" concept works specially.

**Comment by jamesarosen** [comment]
I'm afraid I don't have any example projects online. For some time now I've wanted to do documentation in JSBin examples.

**Comment by jamesarosen** [comment]
Example for v4.0.0 posted in the wiki: https://github.com/jamesarosen/ember-i18n/wiki/Example:-Language-Chooser
