### ISSUE TITLE
Getting deprecation warning when using with ember 1.10.0 (with ember-i18n ver 2.9.1)

### ISSUE THREAD

**Issue by dshrestha** [jamesarosen/ember-i18n#194]
We are getting mix of deprecation warning as well as js error after we upgraded to ember 1.10.0.
We get deprecation warning like :

    "Usage of Ember.Handlebars.get is deprecated, use a Component or  Ember.Handlebars.makeBoundHelper instead..... "

This warning is generated on call to "get" function .
 
    function selectCompileImplementation() {
        var flag = Ember.ENV.I18N_COMPILE_WITHOUT_HANDLEBARS;

        if (flag === true) {
            return function compileWithoutHandlebars(template) {
                return function (data) {
                    return template
                        .replace(/\{\{\{(.*?)\}\}\}/g, function(i, match) {
                            // tripple curlies -> no-escaping
                            return get(data, match);
                        }).replace(/\{\{(.*?)\}\}/g, function(i, match) {
                            return escapeExpression( get(data, match) );//source of deprecation error
                        });
                };
            };
        }

I had upgraded to ember 1.10.0 and had set
 
    Ember.ENV.I18N_COMPILE_WITHOUT_HANDLEBARS = true;

Also in some cases we get hard js error like : 

    TypeError: options is undefined

which is caused in ember.js file , in this function :

     __exports__["default"] = function handlebarsGet(root, path, options) {
      Ember.deprecate('Usage of Ember.Handlebars.get is deprecated, use a Component or Ember.Handlebars.makeBoundHelper instead.');

      return options.data.view.getStream(path).value();
    }

 This happens when I am trying to get translated string in my js file , for eg:

    validations: {
        urlParam: {
            length: {
                allowBlank: true,
                maximum: 64,
                messages: {

                    tooLong: Em.I18n.t("survey.message.generic.length.long.error", {
                        field: Em.I18n.t("survey.label.url.parameters"),
                        count: 64
                    })
                }
            }
        }
    }

Is there a way to avoid these errors and deprecation warnings.

**Comment by dshrestha** [comment]
Using v3.0.0-beta2 seems to solve this issue.

**Comment by dshrestha** [comment]
Using v3.0.0-beta2 seems to solve the deprecation warning issues but then I get this error:

    TypeError: PlainHandlebars is undefined

Originating from this code :

  EmHandlebars.registerBoundHelper('t', function(key, options) {
    return new PlainHandlebars.SafeString(I18n.t(key, options.hash));
  });

where PlainHandlebars is window.Handlebars which off-course is undefined because we don't use handlebars anymore because we are using htmlbars. Please help.

**Comment by jcbvm** [comment]
Try v3.0.0-beta3 which makes no longer use of the plain Handlebars. It is working for me with ember 1.10.0

**Comment by dshrestha** [comment]
@jcbvm thanks for the response. That took care of the issue I was getting before. Now I am getting an error where the key is being passed as undefined to the "t" helper but I think there must be something else going on outside of the localization lib. Thanks again.

**Comment by dshrestha** [comment]
Here is a quick jsbin : http://emberjs.jsbin.com/cibiteyebe/1/
to demonstrate the issue with localization with beta version 3. The issue seems to be with the helper.

    EmHandlebars.registerBoundHelper('t', function(key, options) {
      return new EmHandlebars.SafeString(I18n.t(key, options.hash));
    });

key is getting passed as undefined. In the jsbin if we remove the {{t user.edit.title}}, the app runs.

**Comment by jamesarosen** [comment]
@dshrestha I think https://github.com/jamesarosen/ember-i18n/issues/193#issuecomment-73799842 is your problem. (The difference between a quoted and unquoted helper argument.)
