### ISSUE TITLE
Upgrade to 1.10 causes TranslateableProperties to require setting property to null

### ISSUE THREAD

**Issue by MattNguyen** [jamesarosen/ember-i18n#198]
In the process of upgrading from 1.09 to 1.10, controllers that included `Ember.I18n.TranslateableProperties` required setting the underlying translateable property to null. 

For example:

```javascript
var ApplicationController = Ember.ObjectController.extend(Ember.I18n.TranslateableProperties, {
  title: null,
  titleTranslation: 'path.to.translation'
});
```

This makes sense since controllers proxy properties to models, and if the model doesn't define the property, then Ember will complain about delegating to the content property of object. 

However, I'm not sure why this worked in 1.09. Any help would be appreciated.

**Comment by jamesarosen** [comment]
Is there something we can do in code to make this work automatically? Or should we just document the requirement?

**Comment by MattNguyen** [comment]
@jamesarosen -  Check out this: https://github.com/MattNguyen/ember-i18n/commit/e53461471a491675d9384e5363e0280958162cec.

Basically, run all the observer initialization stuff in a `scheduleOnce` in the `afterRender` queue. This seems to work for my use case, but the `TranslateableProperties` tests are now broken and I'm not sure why. 

What do you think?

**Comment by jamesarosen** [comment]
To fix the tests, we'll probably have to use more `Ember.run` calls to make sure everything is flushed by the time we're making assertions.

**Comment by blimmer** [comment]
Any updates on this PR? I'm migrating stuff over to 1.11 and this problem has come to bite me several times.

**Comment by jamesarosen** [comment]
@blimmer do you want to try adding `Ember.run` to the tests on top of https://github.com/MattNguyen/ember-i18n/commit/e53461471a491675d9384e5363e0280958162cec ?

**Comment by blimmer** [comment]
I can but probably not this week.

**Comment by MattNguyen** [comment]
Sorry I meant to comment here that I already fixed the tests. They should
be good to go.

**Comment by MattNguyen** [comment]
See: https://github.com/jamesarosen/ember-i18n/pull/199

**Comment by MattNguyen** [comment]
Closing for https://github.com/jamesarosen/ember-i18n/pull/199
