### ISSUE TITLE
Using zero and other plural forms in 'en' locale

### ISSUE THREAD

**Issue by seifsallam** [jamesarosen/ember-i18n#202]
In the docs it's mentioned that 'zero', 'one', 'two', 'few', 'many', 'other' are supported but not in `en`. Is there a hook or an easy way to add support for this in `en`?

**Comment by GreatWizard** [comment]
It's because ember-i18n follows official CLDR rules. See https://github.com/jamesarosen/ember-i18n/issues/93

**Comment by seifsallam** [comment]
Thanks :) 

For others having same issue, here is how to do in with `ember-i18n` + `ember-cli`

```js
import Ember from 'ember';
import locales from '<project-name>/locales/en';

export default {
  name: 'i18n',
  initialize: function() {
    Ember.I18n.pluralForm = function customInflector(n) {
      return n === 0 ? 'zero' : n === 1 ? 'one' : 'other';
    };

    Ember.I18n.locale = 'en';
    Ember.I18n.translations = locales;

    Ember.View.reopen(Ember.I18n.TranslateableAttributes);
  }
};
```
