### ISSUE TITLE
Loading translations at runtime with a network call

### ISSUE THREAD

**Issue by mansona** [jamesarosen/ember-i18n#205]
I know this repo is a bit in flux at the moment but I wanted to know your opinion on a particular way to load translations across the network instead of including them in the assets and the build. 

You say in the Readme: 

> Em.I18n.translations must be fully populated before Ember renders any views. There are no bindings on the translations themselves, so Ember will not know to re-render views when translations change.

I know there was talk about having the internals watch for changes, and I know there is collaboration with the other ember-cli-i18n repo to improve this, but taking this advice to heart I decided to make use of "deferring readiness" in the initialiser so that the app would wait for the translations to get back before a template was rendered.

I followed the instructions here: http://nerdyworm.com/blog/2013/04/03/ember-initializers/ and produced the following: 

```
import Ember from 'ember';

var i18n = {
    name: 'i18n',
    initialize: function(container, application) {
        application.deferReadiness();

        Ember.$.getJSON("/i18n", function(json) {
            Ember.I18n.translations = json;
            application.advanceReadiness();
        });
    }
};

export default i18n;
```

can you let me know if this is essentially a bad idea? I don't know if there is a "more correct" way of doing this but essentially this seems to work at the moment.

**Comment by jamesarosen** [comment]
The app I wrote this library for does something similar. In fact, it breaks up translations into bundles and loads all the necessary bundles in a route's `beforeModel` hook. I think that might be a better place than an initializer (since you could then use your data store), but the concept is the same: block rendering until translations are loaded.

**Comment by jamesarosen** [comment]
v4.0 alpha (see #213) has live bindings on locale and on new translations being added.

**Comment by jcbvm** [comment]
With v4.0 can we also add locales dynamically? Or do they have to exist (like a locale with empty translations and filling them when needed)? Currently I'm loading translations via JSON files and would like to only add translations/locales when they are needed.

**Comment by jamesarosen** [comment]
They can be loaded at runtime. See https://github.com/jamesarosen/ember-i18n#adding-translations-at-runtime.

**Comment by jcbvm** [comment]
Ah yes, but what not was really clear to me: does this also create a new Locale with setting plurals etc?

**Comment by jamesarosen** [comment]
It will define a new locale. There's a test for that. There isn't an API for defining pluralization settings at runtime.

**Comment by jcbvm** [comment]
Alright thanks, keep up the good work btw, v4.0 looks really nice.
