### ISSUE TITLE
Assign functions to translatable properties?

### ISSUE THREAD

**Issue by jpcody** [jamesarosen/ember-i18n#209]
With many components, each sharing a handful of attributes, it would be really nice to either assign functions to translateable properties or support interpolations in lookup keys.

Imagine each component has a `title` and `body`. Rather than duplicating this code again and again, it would be really nice to do something like the following:

```JS
App.BaseComponent = Ember.Component.extend({
  titleTranslation: function(){ return this.get( "namespace" ) + ".title"; },
  bodyTranslation:  function(){ return this.get( "namespace" ) + ".body"; }
});

App.LongNamespacedComponent = App.BaseComponent.extend( 
  Em.I18n.TranslateableProperties,
  {
    namespace: "long-namespaced-component-name-goes-here"
  }
);

Em.I18n.translations = {
  "long-namespaced-component-name-goes-here": {
    "title": "My Title",
    "body": "Full body text"
  }
};
```

Am I missing previous discussions around this or a way this is already possible? If not, do you imagine it would be possible in the future?

Thanks!

**Comment by jamesarosen** [comment]
The line you're looking for is [here](https://github.com/jamesarosen/ember-i18n/blob/4dcccc4c96c1de06a93761ac3eae560eff45a763/lib/i18n.js#L46). Specifically, for each `fooTranslation` `key` in the object, it does `I18n.t(object[key])`.

When evaluating templates, however, we [use](https://github.com/jamesarosen/ember-i18n/blob/4dcccc4c96c1de06a93761ac3eae560eff45a763/lib/i18n.js#L59) `get(object, key)`.

I don't see a problem with changing `I18n.t(object[key])` to `I18n.t(get(object, key))`. If we do that, you'll just need to turn your functions into computed properties:

```js
App.BaseComponent = Ember.Component.extend({
  titleTranslation: Ember.computed('namespace', function(){
    return this.get( "namespace" ) + ".title";
  }),

  bodyTranslation: Ember.computed('namespace', function(){
    return this.get( "namespace" ) + ".body";
  })
});
```

**Comment by jpcody** [comment]
Thanks, @jamesarosen. This worked for my particular use-case, and it seems like a practical choice. In the next couple of days, I'll try and get a PR in and make sure there are no unintended side-effects.

**Comment by jpcody** [comment]
Ended up dropping `TranslateableProperties` in favor of computed attributes, which made my world much better. Given https://github.com/jamesarosen/ember-i18n/pull/213 is underway, foregoing a PR on this so as to not distract from that effort. Thanks, @jamesarosen!
