### ISSUE TITLE
Glimmer support

### ISSUE THREAD

**Issue by Geokoumpa** [jamesarosen/ember-i18n#210]
Hello,

I've tried the new Glimmer rendering engine on 1.13.0-beta.1 and from what I can see, all translated properties appear as [object Object]. Am I doing something wrong or is there work to be done on this plugin as well as to be usable with glimmer?

Thanks,
G

**Comment by jamesarosen** [comment]
I tend to track official releases, so I haven't started work on Glimmer support.

**Comment by jamesarosen** [comment]
It is likely that the v3 series will never support Glimmer because of emberjs/ember.js#11080.

I'm hoping to add Glimmer support to v4.0 (see #213) once that issue is resolved.

**Comment by miguelmota** [comment]
+1 glimmer support

At least on a separate branch.
