### ISSUE TITLE
Broken translatable properties with 3.1.1

### ISSUE THREAD

**Issue by gzurbach** [jamesarosen/ember-i18n#217]
I have a select menu in my app showing a list of countries. The countries are loaded in the application route `beforeModel` hook. This select menu uses a `promptTranslation`. Translations are also loaded asynchronously within an initializer.

This is the select:
```javascript
{{view "select"
        content=controllers.countries.content
        optionValuePath="content.id"
        optionLabelPath="content.name"
        promptTranslation='address.form.country.prompt'}}
```
And this is the initializer (part of it):
```javascript
export default {
    name: 'i18n',
    initialize: function (container, app) {
        app.deferReadiness();

        Ember.Select.reopen(Ember.I18n.TranslateableProperties);

        var request = Ember.$.get('/api/translations');
        request.done(function (data) {
            Ember.I18n.translations = data;
            app.advanceReadiness();
        });
    }
};
```
If I upgrade ember-i18n from 3.1.0 to 3.1.1 it starts acting up. The prompt does show up anymore. The select menu will always show the first country (and sometimes the last one). If I use the prompt without i18n (hardcoded value), it works again. 
I'm assuming there is a racing issue between the request to get the countries and the request to get the translations. Not sure if there is a better way. Do you have any thoughts? Thanks!

**Comment by jamesarosen** [comment]
What happens if you set the `prompt` to some other computed property that changes after render? (Say bind it to a property on the controller, then update that value from the console.) I'm wondering whether live-bound `prompt` works at all.

3.1.1 changed the time at which that translation is evaluated and set on the view.

**Comment by jamesarosen** [comment]
There have been enough problems with this that I'm considering yanking 3.1.1. v4 will be out soon anyway.

**Comment by gzurbach** [comment]
I'm sorry I did not get back to you yet, I've been very busy. I will go back to that issue ASAP and let you know. Thanks for your responsiveness!

**Comment by jamesarosen** [comment]
As v4 is out now, I'm going to close this. I'll gladly help with a patch PR for v3.1 if you want to start one, though.
