### ISSUE TITLE
Tag Pre-Release v4 alpha branch

### ISSUE THREAD

**Issue by blimmer** [jamesarosen/ember-i18n#218]
So those of us testing it out on demo projects don't suddenly lose the `v4-alpha` branch.

**Comment by jamesarosen** [comment]
I'm about to release that as beta.0. I'll tag the alpha as well.

**Comment by blimmer** [comment]
:+1:

**Comment by jamesarosen** [comment]
https://github.com/jamesarosen/ember-i18n/tree/v4.0.0-beta.1 and https://github.com/jamesarosen/ember-i18n/tree/v4-alpha (which are pointers to the same commit)
