### ISSUE TITLE
addTranslations won't work

### ISSUE THREAD

**Issue by danshapir** [jamesarosen/ember-i18n#223]
Hey,

This line:
this.container._registry.register(key, existingTranslations);
In: ember-i18n/add-translations

should be changed to 
container._registry.register(key, existingTranslations);

Because this has no container :)

**Comment by jamesarosen** [comment]
Yup!

**Comment by danshapir** [comment]
Thanks!
Sorry for the noobie npm questions, how to I get this fix if you didn't release a new version?

**Comment by jamesarosen** [comment]
You'll find http://stackoverflow.com/questions/14187956/npm-install-from-git-in-a-specific-version helpful.
