### ISSUE TITLE
i18n Service not injected into Routes by default

### ISSUE THREAD

**Issue by andybluntish** [jamesarosen/ember-i18n#225]
G'day,

The README states that the i18n Service is automatically injected into every Route, Controller and Component. However when using `translationMacro` in a route, I found I needed to inject the service myself (`i18n: Ember.inject.service()`). I looked into the instance initializer and saw that the service is only being injected into components and controller.

I'm not sure what the intended behaviour is. Does the documentation need updating, or is it supposed to be injected into routes as well?

**Comment by jamesarosen** [comment]
My intention for injecting it into routes was to enable things like
```
beforeModel: function(params) {
  return Ember.$.ajax(`/translations/${params.locale}`)
    .then((translations) => { this.get('i18n').addTranslations(params.locale, translations); })
}
```

That seems like a fairly legitimate use-case. What's yours?

**Comment by andybluntish** [comment]
I'm using the [ember-cli-document-title](https://www.npmjs.com/package/ember-cli-document-title) addon, and pulling the 'base' title from the translations by importing `translationMacro`.

```js
import Ember from 'ember';
import { translationMacro as t } from 'ember-i18n';

const {
  get,
  inject
} = Ember;

export default Ember.Route.extend({
  i18n: inject.service(),

  _titleBase: t('app.title'),
  title(tokens) {
    const base = get(this, '_titleBase');
    const hasTokens = tokens && tokens.length;

    return hasTokens ? `${tokens.reverse().join(' | ')} | ${base}` : base;
  }
});
```
As you can see, I've had to specifically inject the i18n service. It's not a problem, but the readme says that the service is injected into routes automatically.

**Comment by jamesarosen** [comment]
I like that. I think it's worth auto-injecting into routes. The trouble is that I don't know whether injection rules for routes *work*. See https://github.com/emberjs/ember.js/issues/11172, though that might be fixed in https://github.com/emberjs/ember.js/commit/9b0d55d96540aa7ddb5f783476c91d78c4e17fb3.

**Comment by jamesarosen** [comment]
Would you mind trying adding `route` to the list of injections in your local copy of ember-i18n and commenting out your one-off injection? If that works, I'm all for it.

**Comment by andybluntish** [comment]
OK, so I commented out the `i18n: inject.service()` line in the route, and added `instance.registry.injection('route', 'i18n', 'service:i18n');` to the instance initializer, and everything seems to work great.

For reference, I'm using Ember 1.12.1, CLI 0.2.7, and i18n 4.0.0-beta.2.

**Comment by andybluntish** [comment]
Also, this is the Application Route that I'm working with.
