### ISSUE TITLE
Don't inject the i18n service automatically

### ISSUE THREAD

**Issue by blimmer** [jamesarosen/ember-i18n#226]
I don't think the i18n service needs to be blindly injected into all `Route`, `Controller`, and `Component`. It's a lazy lookup, but I still think it's easier to just do:
```js
i18n: Ember.inject.service();
```
where you need i18n.

This is a style preference, not really a direct issue.

**Comment by jamesarosen** [comment]
I'm leaning towards this as well, but I haven't decided.
