### ISSUE TITLE
Unknown blueprint: translations

### ISSUE THREAD

**Issue by JoshWhite** [jamesarosen/ember-i18n#228]
Hi,

I'm trying to add translation files as described in the README:

>ember install ember-i18n
>ember generate translations es

But I'm getting this error:
>Unknown blueprint: translations

npm seems to have done it's magic and downloaded all the necessary files, but ember-cli doesn't appear to know about it. Am I missing something?

**Comment by jamesarosen** [comment]
Not yet implemented! Coming soon to an i18n library near you!
