### ISSUE TITLE
Bad Docs? this.i18n.t() does not exist but this.get('i18n').t() does

### ISSUE THREAD

**Issue by Kilowhisky** [jamesarosen/ember-i18n#234]
Inside a route i'm doing 

`i18n: Ember.inject.service();`
`this.i18n.t('login.loginTitle');`

But the function does not exist when called this way.
But when i call this way it is working. 

`i18n: Ember.inject.service();`
`this.get('i18n').t('login.loginTitle');`

Are the docs just wrong or is this something different?

**Comment by jamesarosen** [comment]
The docs are wrong. Injections declared in the registry don't need `get`, but using `Ember.inject.service()` does. I'm planning on removing all the automatic injections and only supporting the latter.

**Comment by jamesarosen** [comment]
See also #226
