### ISSUE TITLE
t helper is broken with glimmer (1.13 compatibility)

### ISSUE THREAD

**Issue by blimmer** [jamesarosen/ember-i18n#237]
The [helper.js](https://github.com/jamesarosen/ember-i18n/blob/master/addon/helper.js#L6) implementation appears to be incompatible with the newly released Ember 1.13 helpers.

There are several errors associated with these changes, it seems:

1. Container moved in environment
This patch fixes this part:
```js
export default function t(params, hash, options, env) {
  const container = env.data ? env.data.view.container : env.container;
  const i18n = container.lookup('service:i18n');
```

2. Structure of stream appears to have changed
The output from the helper appears to be `[Object object]` once the container lookup passes.
![](https://i.imgur.com/C250twB.png)

Supposedly 1.13 supports non-dasherized helpers, so perhaps [the hack](https://github.com/jamesarosen/ember-i18n/blob/a42a8450714e429fc6414f8e0001bbe26f794400/app/instance-initializers/ember-i18n.js#L16) to register the helper in the initializer is no longer needed (this would be great for testing).

**Comment by jamesarosen** [comment]
See #227, which is waiting for emberjs/ember.js#11445

**Comment by blimmer** [comment]
Thanks for the update!
