### ISSUE TITLE
Bower dependency is set to Ember 1.12

### ISSUE THREAD

**Issue by bummzack** [jamesarosen/ember-i18n#239]
... resulting in a warning when installing with Ember 1.13

**Comment by pjmorse** [comment]
See #227 . tl;dr the current master is likely to have problems with 1.13.0 but there are fixes in 1.13.1 (due today, supposedly) which will bring them in line.

**Comment by jamesarosen** [comment]
After 1.13.1 is released, I'll change to `>=1.12, <3`

**Comment by bummzack** [comment]
Perfect. Thank you.
