### ISSUE TITLE
Generator doesn't properly work with Pods

### ISSUE THREAD

**Issue by bummzack** [jamesarosen/ember-i18n#244]
If the Pod directories are within a subdirectory, say `pods`, the generator for locales doesn't honor that setting.

In `config/environment`:

    var ENV = {
      modulePrefix: 'my-app',
      podModulePrefix: 'my-app/pods',
      ....

Running `ember generate locale es`, it will put the locale-files into `my-app/locales/es/`. In a setup with Pods in a subfolder, the locales won't be available (missing translations).

It took me quite some time to figure out that the `locales` folder has to be inside the `my-app/pods` directory. 

I think adding a note in the documentation regarding Pods would be fine. Even better would be if the generator/blueprint would honor the setting.

**Comment by jamesarosen** [comment]
It's supposed to put translations in `my-app/locales/es/translations.js`.

Where does the generator put the files if `podModulePrefix` is defined?

See also #242

**Comment by bummzack** [comment]
It puts them in `my-app/locales/es/translations.js`, but with `podModulePrefix` defined I just get missing translations everywhere. When I move locales directory to `my-app/pods/locales/` the translations work.

According to issue #242 this shouldn't happen.. maybe it was re-introduced somewhere? Or did I miss some config setting?

**Comment by jamesarosen** [comment]
#242 hasn't been merged or released. Have you tried using that branch directly in your app?

```json
// package.json
"ember-i18n": "jamesarosen/ember-i18n#pod-module-prefix"
```

**Comment by bummzack** [comment]
Ah sorry, no I didn't use that branch. Then this issue is probably a dupe of #242. Sorry about that and thanks for all your work on that module.
