### ISSUE TITLE
Issue with unit testing and the {{t}} helper

### ISSUE THREAD

**Issue by green-arrow** [jamesarosen/ember-i18n#251]
I looked at #227 and saw that the helper lookup issue should have been solved with the latest Ember release which contains support for dashless helpers. I am running `1.13.2`, but still have issues when running my unit tests. When running a test for a component which uses the `{{t}}` helper in its template, I am getting the 'unable to find helper' error. When trying to put it in the `needs` array, I get the `attempted to inject unknown factory` error. Am I missing something here?

**Comment by jamesarosen** [comment]
It's difficult to support such a complex helper in unit tests. At a minimum, you would need to

 1. add `service:i18n`, `helper:t`, and a local-translation and locale-config to `needs`
 2. register the helper with a container
 3. inject the `service:i18n` into your object

I may add a note to the README because this keeps coming up and nobody has come up with a good way to solve it.

**Comment by green-arrow** [comment]
A note in the README would definitely be helpful. I know that when I used `ember-cli-i18n`, the solution I used was to create a "fake" `t` helper and register it before any unit tests which needed the helper. I added a helper file:

`tests/helpers/register-i18n.js`
```javascript
import Stream from 'ember-cli-i18n/utils/stream';
import t from 'ember-cli-i18n/utils/t';
import Ember from 'ember';

// tHelper without the container and application dependencies, sigh...
function tHelper(params /*, hash, options, env */ ) {
  var path = params.shift();

  var stream = new Stream(function() {
    return t(path, params);
  });

  // bind any arguments that are Streams
  for (var i = 0, l = params.length; i < l; i++) {
    var param = params[i];
    if (param && param.isStream) {
      param.subscribe(stream.notify, stream);
    }
  }

  if (path.isStream) {
    path.subscribe(stream.notify, stream);
  }

  return stream;
}

export function registerI18N() {
  // Yay, private APIs!
  Ember.HTMLBars._registerHelper('t', tHelper);
}
```

Then, in any tests which needed to use the helper, you would import the function then call it from the `setup` method.

I'm not sure if a similar approach would work for this library as well, but I will look into it.

**Comment by jamesarosen** [comment]
I added https://github.com/jamesarosen/ember-i18n/wiki/Doc:-Testing

**Comment by iezer** [comment]
@jamesarosen could you please provide an example of how to register the helper in a component test with `integration: true`?

**Comment by jamesarosen** [comment]
Done

**Comment by iezer** [comment]
@jamesarosen  Thank you very much. fwiw with @mixonic helped me with another solution that calls the initializer instead of registering the helper:

```
import initializer from "my-app/instance-initializers/ember-i18n";

module("foo", {
  integration: true,
  setup(){
    initializer.initialize(this);
  }
}); 
```

**Comment by jamesarosen** [comment]
@iezer I like that. Feel free to add that to the wiki as an alternate.

**Comment by iezer** [comment]
@jamesarosen Done.

**Comment by bbansalWolfPack** [comment]
@jamesarosen  I tried the ember-18n example given on below link:
https://github.com/jamesarosen/ember-i18n/wiki/Doc:-Testing
But somehow its not working for me. Can you help me out? Specifically i am not able to understand why below things are imported in needs[] and what are these two things?

'locale:xy/translations',
    'locale:xy/config',

**Comment by jamesarosen** [comment]
@bbansalWolfPack this project has been deprecated in favor of [ember-intl](https://github.com/ember-intl/ember-intl). It no longer receives support.

**Comment by bbansalWolfPack** [comment]
@jamesarosen thanks for the update, I am still using ember-i18n so is there a way I can mock this for unit tests?
