### ISSUE TITLE
i18n Editor

### ISSUE THREAD

**Issue by jcbvm** [jamesarosen/ember-i18n#252]
Hi, I just wanted to inform you that I created an application to manage multiple translation files for ember-i18n 4.0+. If you have time, maybe take a look at it. I thought maybe it would be nice for others to share the link in the docs (really optional, it is not my intention to promote it, but I thought maybe others might find it useful).

https://github.com/jcbvm/ember-i18n-editor

**Comment by jamesarosen** [comment]
Looks cool! Is there somewhere in the [wiki](https://github.com/jamesarosen/ember-i18n/wiki) you think it might fit? If not, maybe we need a "See Also" section.

**Comment by jcbvm** [comment]
I think it might fit best in a "See Also" or something like "Tools" section indeed, because it's not part of ember-i18n itself.

**Comment by jamesarosen** [comment]
I like "See Also" because it could include a "Built with Ember-I18n" list. I've started a page just for you: https://github.com/jamesarosen/ember-i18n/wiki/Links
