### ISSUE TITLE
Calling set on destroyed object error when using (t) for placeholder in input field

### ISSUE THREAD

**Issue by Kilowhisky** [jamesarosen/ember-i18n#253]
When using ember-i18n.t() helper as a placeholder sub expression an error will be thrown if you navigate away from the route where the placeholder is being used. 

For example if you use the following
` {{input value=username placeholder=(t 'login.usernamePlaceholder') required=true}}`
 
and then navigate away from this page and change the locale then an error will be thrown. 

I have a test app that shows this problem located here: http://www.megafileupload.com/d3NH/test-project.zip

**Comment by danshapir** [comment]
Same thing happening to be on the latest version

**Comment by Kilowhisky** [comment]
I believe this is caused by this line:

https://github.com/jamesarosen/ember-i18n/blob/master/addon/legacy-helper.js#L28

The helper subscribes but then doesn't unsubscribe when its parent object is being destroyed.  so this block gets called on a destroyed object .

```
var out = new Stream(function() {
      const value = i18nKey.isStream ? i18nKey.value() : i18nKey;
      return value === undefined ? '' : i18n.t(value, readHash(hash));
    });
```

 I see that this seems to be a legacy issue < 1.13.

**Comment by jamesarosen** [comment]
@Kilowhisky interesting. Do you think we should try tearing all the streams down when `env.data.view` is about to be destroyed?

**Comment by danshapir** [comment]
Probably, since now this makes using the t helper as an inner helper {{component text=(t 'WOW')} unuseable

**Comment by Kilowhisky** [comment]
@jamesarosen 

This sounds the best course of action. Trying to write up a PR for it right now but this is the first one i've done so its going to be cludgy.

**Comment by danshapir** [comment]
PR Made:
https://github.com/jamesarosen/ember-i18n/pull/258

**Comment by Kilowhisky** [comment]
@danshapir Nice. 

I was going with this. 

```
      // un-observe the locale on destruction of the associated view
      env.data.view.one("willDestroyElement", this, function () {
        i18n.localeStream.unsubscribe(out.notify, out);
      });
```

Out of curiosity what will `this.destroy()` do if the element is already in the process of being destroyed?

**Comment by jamesarosen** [comment]
> Out of curiosity what will this.destroy() do if the element is already in the process of being destroyed?

[Absolutely nothing](https://github.com/emberjs/ember.js/blob/v1.12.1/packages/ember-metal/lib/streams/stream.js#L162-L175)

**Comment by Kilowhisky** [comment]
I should rephrase that. How is calling `destroy` on an object already in the process of being destroyed supposed to clean up the subscriber in the helper we are working with? 

Actually his PR fix isn't working for me.

**Comment by danshapir** [comment]
you are using it wrong, the scope is wrong
```javascript
// un-observe the locale on destruction of the associated view
      env.data.view.one("willDestroyElement", this, function () {
        i18n.localeStream.unsubscribe(out.notify, out);
      });
```javascript

You are passing this
I am passing out
I am destroying the stream, not the view
