### ISSUE TITLE
Suggest using language agnostic (non-english) interpolation replace value

### ISSUE THREAD

**Issue by kellyselden** [jamesarosen/ember-i18n#254]
This is an opinion. Sending something like this:
```js
  product: {
    products: 'Products',
    count: {
      one: '{{count}} products',
      other: '{{count}} products'
    }
```
to a translation service might be confusing to them. I can see them ignoring instruction and translating `{{count}}`. I could preprocess the file and replace `{{count}}` with some symbol, then reverse it later, but it would be nice to handle it here. ember-cli-i18n used `%@` as replace values.

Would you be open to either add a different replace value, and users could use either, or perhaps make the replace value overridable?

**Comment by jamesarosen** [comment]
> I can see them ignoring instruction and translating `{{count}}`

I don't think we ever ran into that in five years of translating on my last project, but it's theoretically possible.

See also [my comment on the issue](https://github.com/dockyard/ember-cli-i18n/issues/56#issuecomment-69993887) and [@sandstrom's](https://github.com/dockyard/ember-cli-i18n/issues/56#issuecomment-82358284).

You can always set your own compiler:

```js
// utils/i18n/compile-template.js:

export default function(template) {
  return function compiledI18nTemplate(context) {
    return Ember.String.fmt(template, "what are the other args?");
  };
}
```

though the above implementation suggests a problem: ember-i18n expects `context` to be a hash, which it gets from the [`Helper#compute`](https://github.com/jamesarosen/ember-i18n/blob/v4.0.0/addon/helper.js#L11). I suppose we could give the helper a `getContext(orderedParams, namedParams)`, with the default implementation:

```js
// addon/helper.js:

getContext(orderedParams, namedParams) {
  return namedParams;
}
```
Then people who want ordered params could override it:
```js
// app/instance-inititalizers/i18n-t.js:

container.lookup('helper:t').getContext = function getOrderedParams(orderedParams) {
  return orderedParams.slice(1);
};
```

**Comment by kellyselden** [comment]
Given `Ember.String.fmt`'s use, you could use `%@1` and `%@2` instead of ordered params. I like your suggestions. I might fiddle with it a bit. I will let you know if I come up with an elegant solution.

**Comment by sandstrom** [comment]
I think interpolation is such a common thing that anyone working with translation will know about it. It's also pretty easy to explain. Just a thought :boat:

**Comment by jamesarosen** [comment]
@kellyselden if you're interested in using ordered params in your app, do you like my suggestion to extract `getContext(orderedParams, hashParams)` so you can override it? Do you have another idea for how to make that work?

**Comment by kellyselden** [comment]
@jamesarosen @sandstrom I don't think I feel as strongly about this one anymore. If I was worried about the `{{count}}` getting translated, I've found that I could do something like
```js
count: {
  one: '{{x1}} product',
  other: '{{x1}} products'
}
```
and
```js
{{t "product.count" count=model.meta.count x1=model.meta.count}}
```
