### ISSUE TITLE
t helper is not available

### ISSUE THREAD

**Issue by saarangsoltani** [jamesarosen/ember-i18n#260]
I don't understand why the `t` helper is not available in my templates. I'm pretty sure the addon is loaded as i can inject the service and translate through `i18n.t(' key')` but `t` helper is not available.
Here are the version numbers :
Ember : 1.13.2
Ember-data : 1.13.4
Ember-cli :  2.7
![screenshot] (http://i.imgur.com/kjdL9an.png)

**Comment by jamesarosen** [comment]
Any chance this is in a test? See https://github.com/jamesarosen/ember-i18n/wiki/Doc:-Testing

**Comment by saarangsoltani** [comment]
@jamesarosen this is not in tests

**Comment by jamesarosen** [comment]
Can you set a breakpoint [here](https://github.com/jamesarosen/ember-i18n/blob/v4.0.0/app/instance-initializers/ember-i18n.js#L22) and make sure the instance-initializer is registering it?

**Comment by saarangsoltani** [comment]
thanks you gave me a clue. i had to update my ember-load-initializers.
