### ISSUE TITLE
Doc/best practice for adding translations from backend?

### ISSUE THREAD

**Issue by mk-conn** [jamesarosen/ember-i18n#261]
Hi,

I'm kinda lost and don't know where else to ask... Trying to fetch translations from my backend and add it via initialisation but it seems either I understand something totally wrong or something is not working.. 

Here is my code (Ember 1.13.2, ember-cli 0.2.7):

```
import Ember from 'ember';

export default {
    name: 'i18n-setup',
    after: ['current-user', 'ember-i18n'],

    initialize: function({instance}) {

        var user = instance.container.lookup('service:current-user');
        var i18n = instance.container.lookup('service:i18n');
        
        var locale = user.get('currentLocale');
        i18n.set('locale', locale);

        Ember.$.getJSON('/api/v1/strings', function (data) {
            console.log('Available locales: ', i18n.get('locales'));

            i18n.addTranslations(locale, data);
        });
    }
};
```
This code results in:
```
Uncaught TypeError: Cannot read property 'indexOf' of undefined (in service.js:38)
```
which is
```
if (this.get("locale").indexOf(locale) === 0) {
        this.get("_locale").rebuild();
}

```

In general, would this be an approach that *should* work? If not, how are others doing it?

**Comment by mk-conn** [comment]
Okay, my user is somehow not set, so the code was setting the locale to 'undefined' - now its working. But the general question remains if this could be a best practice...

**Comment by jamesarosen** [comment]
If you want to *block* initialization, you'll want to return a promise from `initialize`. I think this case is reasonably common, though I recommend doing it in a route instead of an initializer:

```js
// app/routes/application.js

export default Ember.Route.extend({
  i18n: Ember.inject.service(),

  beforeModel: function() {
    const currentLocale = this.get('i18n.locale');
    return Ember.$.getJSON('/translations/' + locale)
             .then((data) => {
               this.get('i18n').addTranslations(locale, data);
             });
  }
});
```

**Comment by jamesarosen** [comment]
I wrote up [this doc in the wiki](https://github.com/jamesarosen/ember-i18n/wiki/Example:-Fetching-Translations-Live). It will likely evolve over time.
