### ISSUE TITLE
RFC: add i18n.exists(key)

### ISSUE THREAD

**Issue by blimmer** [jamesarosen/ember-i18n#264]
## Problem
There's no way to check for a key that may or may not be present. For example, I automatically try to assign the page title from a `pageTitles` object in my translations file. E.g.
```js
// translations.js
{
  'pageTitles': {
    'index': 'My Homepage',
    ...
  }
}
```
Some pages won't have a title token, and that's OK. In v3, I used the [exists](https://github.com/jamesarosen/ember-i18n/blob/v3.1.1/lib/i18n.js#L110) method to make sure I didn't end up with `Missing translation` messages in my page title.

## Proposal
We restore the behavior on the i18n service to check if `i18n.t(key)` would return a value. It should have no special logic outside of returning `true` if `i18n.t` returns a key from the translations file and `false` if it would fire the `missing` event.

**Comment by Truffula** [comment]
FWIW, just throwing this out there as it seems relevant. I agree that such a function would be handy, although at the moment (still on v3) I have a custom missingMessage function like the following, which allows you to pass in a fallback function/value to the context via the ifMissing property:

```js
function missingMessage(key, context) {
    if (context && typeof context.ifMissing !== 'undefined') {
        return typeof context.ifMissing === "function" ?
            context.ifMissing.call(this, key, context) :
            context.ifMissing;
    } else {
        Ember.warn('Translation missing: ' + key);
        return 'Translation missing: ' + key;
    }
};
```

So you can use:
```js
var I18n = this.get('I18n'),
    title = I18n.t('path.to.translation', {ifMissing: null});
// or
title = I18n.t('path.to.another.translation', {
    ifMissing: function(key, context) {
        return I18n.t('path.to.fallback.translation', context);
    },
    name: this.get('name')
});
```

Since I haven't got around to upgrading to v4 yet I'm not sure how well this would work with the new way things are bound etc.

**Comment by jamesarosen** [comment]
Does the new [Fallback Keys](https://github.com/jamesarosen/ember-i18n/wiki/Doc:-Translating-Text#fallback-keys) feature handle the case you're using `exists` for?

I'm happy to add this API if there's a use-case that isn't covered by the existing feature set.

**Comment by blimmer** [comment]
I could shoehorn Fallback Keys to work for this, but it's not 100% what `exists` gives you.

It's nice that `exists` is a boolean you can check before doing anything. In the example case (with page title), you could do something like this:
```js
pageTitle: function() {
  const i18n = this.get('i18n');
  const key = `pageTitles.${currentRouteName}`;

  if (i18n.exists(key)) {
    return i18n.t(key);
  }
}
```

That way, you can easily build logic to return nothing if the key doesn't exist.

As I mentioned I could shoehorn it like this:
```js
// in translations.js
'blank': ''
```

```js
pageTitle: function() {
  return this.get('i18n').t(`pageTitles.${currentRouteName}`, {default: 'blank'} )
}
```

but it's not as clean. Can fallback keys allow this? It would actually be a bit more concise if it would work.
```js
pageTitle: function() {
  return this.get('i18n').t(`pageTitles.${currentRouteName}`, {default: undefined} )
}
```

**Comment by jamesarosen** [comment]
Absolutely fair. It was in 3.0, so I'm certainly not against adding it. Do you want to make a PR? I don't mind doing it; its up to you.

**Comment by blimmer** [comment]
I actually kind of like the idea of idea of passing an `undefined` default and I think it wouldn't be terribly hard to implement (we'd have to make sure the user passed a default in the `data` hash, but it's not a `String`). What do you think?

**Comment by jamesarosen** [comment]
`default` can also be an array of strings. `default` is a *key* or *list of keys* so passing `undefined` to mean "no fallback" is better than passing `""`, which is really a *value*. I'm on the fence -- it's not an API that's intuitive to me, but I also can't think of anything I *object* to. It even helps us obey a guideline I like: *tell, don't ask*.

One question worth asking: if `{{t "foo.bar", default: undefined}}` returns an empty string when `foo.bar` isn't found, what does `{{t undefined}}` do? That's a question this library has never really asked. (It might have done certain things to avoid exceptions, but it wasn't with *intent*.)

**Comment by blimmer** [comment]
I agree, it seems a little weird to shoehorn the defaults with `undefined`. I think the way to do this is to implement the `exists` API. I'll build a PR for this behavior. Thanks for the input!
