### ISSUE TITLE
Lazy load translations via container inject

### ISSUE THREAD

**Issue by zaubererty** [jamesarosen/ember-i18n#266]
I have seen that ember-i18n is using containers for the translations.
With ember-cli-i18n ist was possible to inject a container before the service was loaded or before the language was switched.
```
export default {
  name: 'load-locales',
  before: 't',

  initialize: function(container, app) {
    var lang = $.cookie('user-lang');

    if (lang === undefined || lang.length > 3) {  // no cookie exists yet
      	lang = navigator.language || navigator.userLanguage;
      	if (lang.length > 3){
      		var langSplit = lang.split('-');
      		if (langSplit[0].length < 3){
      			lang = langSplit[0];
      		} else {
      			lang = 'en';
      		}
      	}
    }
    app.set('locale', lang);
    $.cookie('user-lang', lang, {expires:365, path:'/'});

..... <load data> .....

    //console.log(objs);
    container.register('locale:' + lang, objs, { singleton: true, instantiate: false });
  }
};
```

Is there a similar way in ember-i18n?

**Comment by jamesarosen** [comment]
Are you saying you want to add a set of translations to the `Ember.Container` before `service:i18n` is defined?

You should be able to do something very similar to what you have written, except the name of the object in the container is `'locale:' + lang + '/translations'`.

But I'm not sure I understand *why* you want to do this before `service:i18n` is instantiated. If you wait until after, you can use the public API: `i18n.addTranslations(lang, {...})`.

**Comment by zaubererty** [comment]
The reason for doing this is that way is cause I use moment and pickaday and localize them as well with the loaded loacale.
I have build a translation backend to being able to do translation changes without code changes. 
I had no success with looking up the translation container and the ember debugger does not display it.

My current solution is to add the translations with the suggested method and injecting a second  container for the rest of my needs.

Here my code for the moment localisation:
```
export default {
  name: 'localize-moment',
  after: 'load-locales',
  //before: 'ember-i18n',

  initialize: function(container, app) {
    var locale = app.get('locale');
    var currentLocale  = container.lookup('locale:' + locale);
    var momentLocale = currentLocale.moment;
    for(var key in momentLocale) {
      if (key.indexOf('EVAL') > -1){
        momentLocale[key.replace('EVAL','')] = eval(momentLocale[key]);
      }
      if (typeof(momentLocale[key]) === 'object'){
        var subElement = momentLocale[key];
        for (var k in subElement){
          if (k.indexOf('EVAL') > -1){
            subElement[k.replace('EVAL','')] = eval(subElement[k]);
          }
        }
        momentLocale[key] = subElement;
      }
    }
    moment.locale(locale, momentLocale);
  },
};
```
if I replaced the container "address" with the suggested one it stopped working.

**Comment by jamesarosen** [comment]
> if I replaced the container "address" with the suggested one it stopped working.

I assume you meant you changed `container.lookup('locale:' + locale);` to `container.lookup('locale:' + locale + '/translations');`. Do you also have something like
```js
container.register('locale:' + lang + '/translations', objs, { singleton: true, instantiate: false });
//                                    ^^^^^^^^^^^^^^^
```
in `load-locales`?

**Comment by jamesarosen** [comment]
Did you get this resolved?
