### ISSUE TITLE
Looking up translations in acceptance tests

### ISSUE THREAD

**Issue by drapergeek** [jamesarosen/ember-i18n#267]
I apologize if this is covered in the docs but I couldn't find anything about it.

I often reference translations directly in my tests. This allows me to only have to update translations in one place and my tests and UI are both updated. For example:
```javascript
  clickOn(t('posts.new'));
```
instead of 
```javascript
  clickOn('New Post')
```

(`clickOn` is a function that will click on any link or input with that text)

I can't seem to find anything I can import into my acceptance tests to be able to use the `t` helper in my tests with 4.0. Is there anyway I can access that function?

**Comment by jamesarosen** [comment]
Neat idea. It would not be hard to write a test helper for that purpose. I don't know that Ember addons can *declare* test helpers for your app, but it's worth looking into. My first guess is that it would look something like this
```js
// tests/helpers/t.js
import Ember from "ember";

function tHelper(app, key, context) {
  return app.__container__.lookup('service:i18n').t(key, context);
}

Ember.Test.registerHelper('t', tHelper);
```
And then use it exactly as you said above: `clickOn(t('posts.new'))`.

**Comment by drapergeek** [comment]
Thanks! That is exactly what I was looking for, it works great, I owe you a beer!

**Comment by siriniok** [comment]
@jamesarosen I think it should look like
```
function tHelper(app, key, context) {
  app.__container__.lookup('service:i18n').set('locale', 'en');
  return app.__container__.lookup('service:i18n').t(key, context);
}
```
Without setting locale I have error `test-support.js:6656: Assertion Failed: I18n: Cannot translate when locale is null`.

**Comment by jamesarosen** [comment]
I was assuming your app initializers would set a default locale.
