### ISSUE TITLE
t is missing?

### ISSUE THREAD

**Issue by martinstreicher** [jamesarosen/ember-i18n#268]
I have code that looks like this:

```
`import { translationMacro as t } from 'ember-i18n'`

... = Ember.Select.extend({
  content: [
    {
      label: t('relationship.spouse')
      value: '0'
    }
```

Shouldn't `t` be available there? Instead, I get 

```
Error: Assertion Failed: Cannot translate relationship.spouse. [object Object] does not have an i18n.
```

**Comment by locks** [comment]
Are you sure the `relationship.spouse` path is valid?

**Comment by martinstreicher** [comment]
I have this in the _translations.js_ file:

```
relationship: {
    coworker:           '* Coworker',
    friend:             '* Friend',
    relative:           '* Relative',
    spouse:             '* Spouse / Significant Other',
  },
```

**Comment by martinstreicher** [comment]
This is the code that is complaining:

```
export default function createTranslatedComputedProperty(key, interpolations = {}) {
  return Ember.computed(values(interpolations), function() {
    const i18n = get(this, 'i18n');
    Ember.assert(`Cannot translate ${key}. ${this} does not have an i18n.`, i18n);
    return i18n.t(key, mapPropertiesByHash(this, interpolations));
  });
}
```

Perhaps `this` (I assume referring to the `Ember.Select`) does not the `i18n` object? Is there a way to get it in there?

**Comment by locks** [comment]
http://emberjs.com/deprecations/v1.x/#toc_ember-select possibly relevant in that it might allow you to simplify your select and bypass the problem. I don't know what could be wrong with your current code.

**Comment by martinstreicher** [comment]
I solved this as follows:

```
 i18n: Ember.inject.service()

 menu: [
    {
      label: 'relationship.spouse'
      value: '0'
    }
    ...
 ]

  content: (->
    menuItems = this.get('menu')
    return({ label: this.get('i18n').t(item.label), value: item.value } for item in menuItems)
  ).property('menu')
```

**Comment by jamesarosen** [comment]
> Error: Assertion Failed: Cannot translate relationship.spouse. [object Object] does not have an i18n.

Is telling you that your `Ember.Select` subclass doesn't have an `i18n` property. See https://github.com/jamesarosen/ember-i18n/wiki/Doc:-i18n-Service

**Comment by jamesarosen** [comment]
You just need to add `i18n: Ember.inject.service(),` to your `Ember.Select` subclass.

**Comment by jeremytm** [comment]
I realise this is old, but I just came up against this issue and found a solution without needing to use `this.get('i18n').t()` so thought I would share.

@martinstreicher's issue was the same as mine: trying to use t() on a **nested** object whether it be in an object inside an array:
 ```
export default Ember.Component.extend({
  content: [
    {
      label: t('path')
    }
  ]
```
or an object nested directly on the parent:
```
export default Ember.Component.extend({
  content: {
    label: t('path'),
  },
```
In either case, the i18n object not only needs to be added to the parent:
```
export default Ember.Component.extend({
  
  i18n: Ember.inject.service(),

  content: {
    label: t('path'),
  },
```
But also needs to be added to the **nested** objects:
```
  ...
  
  initI18n: Ember.on('init',function(){
    this.set('content.i18n',this.get('i18n'));
  }),
```
Then it will work properly, and you can use nested items directly in your templates:
`{{content.label}}`

It's rather annoying though, and would be much nicer if the micro function could find it's own way to an instance of `i18n`.

Thoughts @jamesarosen? Nested objects can be very handy when defining things like form validations, error messages, modal content, etc. within components. It would be great to be able to use the micro function at any nested level without worrying about availability of `i18n`.

**Comment by jamesarosen** [comment]
You're bumping up against the edges of Ember and JavaScript, not Ember-I18n. The computed-property macro you're using relies on The I18n Ember.Service.

Object literals aren't created by the container and don't get the container or services I ejected automatically.

I remain confused why people are trying to declare an *Ember computed property* (which is what the `t` macro does) on bare object literals. You wouldn't do this:
```js
foo: {
  bar: Ember.computed(function() {
    return "foobar";
  })
}
```

**Comment by jeremytm** [comment]
I guess not. I concede I'm no ember expert.

If you wouldn't mind educating me (and others) on the best way to handle a situation like the following using [ember-validations](https://github.com/DockYard/ember-validations)?

```
  validations: {
    'username': {
      presence: {
        message: t('login.errors.no-username')
      },
    },
    'password': {
      presence: {
        message: t('login.errors.no-password')
      },
    },
  },
```

At the moment, this fails due to a lack of existence of `i18n` on the nested objects.

Is there absolutely no way for the micro function to look up `i18n` on it's own?

I understand you're equating it to Ember.computed, and there are probably reasons for this I'm not aware of yet, but maybe it could be a little smarter than Ember.computed?

**Comment by jamesarosen** [comment]
> I understand you're equating it to Ember.computed, and there are probably reasons for this I'm not aware of yet, but maybe it could be a little smarter than Ember.computed?

Let's start with what I'm assuming is a misconception you're operating under. `t('login.errors.no-password')` doesn't evaluate to a string like `"No Password"`. It evaluates to an instance of `Ember.ComputedProperty` that's more or less equivalent to
```js
Ember.computed('i18n', function() {
  return this.get('i18n').t('login.errors.no-password');
})
```

That is, it really *is* equivalent to a call to `Ember.computed`. You can see that [here](https://github.com/jamesarosen/ember-i18n/blob/e6098624d45b6f3b02e6b4fedc50569825d26780/addon/utils/macro.js#L10-L14).

> Is there absolutely no way for the micro function to look up i18n on it's own?

In Ember, the standard way to get access to singleton objects like the I18n service is to inject them into objects that need them. You *could* declare them as globals on `window`, which is exactly how previous versions of Ember-I18n worked. But the Ember community decided that was an antipattern. (Global state is generally a bad idea, especially in cases like the DOM where you might easily have conflicts.)

> If you wouldn't mind educating me (and others) on the best way to handle a situation like the following using ember-validations?

In this case, you're sort of in luck. ember-validations has built-in support for the older, globals-based Ember-I18n API. See https://github.com/DockYard/ember-validations#i18n and https://github.com/DockYard/ember-validations/issues/366. Make sure you read all the way to my comment at the bottom of 366.

**Comment by jeremytm** [comment]
Thanks so much for your help.
