### ISSUE TITLE
translation service is not available inside an object

### ISSUE THREAD

**Issue by jludev1** [jamesarosen/ember-i18n#269]
In code below, 
```javascript 
import Ember from 'ember';
import { translationMacro as t } from "ember-i18n";

export default Ember.Controller.extend({
  title: t('user’),

  createButton: {
      title:  t(‘create'), 
      action: ‘create'
   },
}
```
t(...) works for title.  
But t(...) does not work for createButton.title as 'this' in this.get('i18n') is not the controller when t() is called.
Is there a way to handle such scenario?

**Comment by jamesarosen** [comment]
Yup:
```js
export default Ember.Controller.extend({
  i18n: Ember.inject.service()
})
```
See https://github.com/jamesarosen/ember-i18n/wiki/Doc:-i18n-Service

**Comment by jamesarosen** [comment]
Sorry, I mis-read this. I've never seen anything like
```js
createButton: {
  title:  t(‘create'), 
  action: ‘create'
},
```
I don't know what that would do. You could instead do something like this
```js
_defineButton: Ember.on('init', function() {
  this.set('createButton', {
    title: this.get('i18n').t('create'),
    action: 'create'
  });
})
```

**Comment by jludev1** [comment]
Thanks for the quick response. 
Wrapping the data structure in function call works. But it adds limitation on code structure and can make the code harder to read. 
Is it possible to get the service in a static way, such as Ember.i18n.t(...)?

**Comment by jamesarosen** [comment]
> Is it possible to get the service in a static way, such as Ember.i18n.t(...)?

Not easily, because it needs access to the App's container. You might be able to do something like
```js
MyApp.I18n = MyApp.__container__.lookup('service:i18n');
```
in an initializer. But that's not something that the library itself would ever do.

**Comment by jamesarosen** [comment]
The other alternative would be to make the nested data structure an `Ember.Object`:
```js
export default Ember.Controller.extend({
  title: t('user’),

  createButton: Ember.Object.createWithMixins({
    i18n: Ember.inject.service(),
    title:  t(‘create'), 
    action: ‘create'
  },
}
```

**Comment by jamesarosen** [comment]
The other alternative would be to make the nested data structure an `Ember.Object`:
```js
export default Ember.Controller.extend({
  title: t('user’),

  createButton: Ember.Object.createWithMixins({
    i18n: Ember.inject.service(),
    title:  t(‘create'), 
    action: ‘create'
  },
}
```

**Comment by jludev1** [comment]
The mixin alternative sounds better. 
However, with template defined as below
``` javascript
{{createButton.title}}
```
, it will throw the following error:
Uncaught Error: Assertion Failed: Attempting to lookup an injected property on an object without a container, ensure that the object was instantiated via a container.

**Comment by jamesarosen** [comment]
Of course. That does suggest another solution, though. First, you build a custom computed property macro:
```js
function hasI18n(obj) {
  return Ember.computed(function() {
    return Ember.Object.createWithMixins(obj, {
      container: this.get('container'),
      i18n: Ember.inject.service()
    });
  });
}
```
Then you use that to write a shorthand version of my initial solution:
```js
createButton: hasI18n({
  title:  t(‘create'), 
  action: ‘create'
}),
```

**Comment by jludev1** [comment]
This solution works for objects, but still does not seem to work for array. When it's an array, the elements need to be wrapped individually. 
``` javascript
export default Ember.Controller.extend({
  actions: [
    hasI18n({
      title:  t('create'),
      action: 'create'
    }),
    hasI18n({
      title:  t('delete'),
      action: 'delete'
    })
  ]
}
```` 
However, when render such an array in template 
``` javascript
{{#each actions as |action|}}
  {{action.title}}
{{/each}}
```` 
Error "Ember.Object.create no longer supports defining computed properties. Define computed properties using extend() or reopen() before calling create()." will be thrown. 

Another issue is that when the array is passed to a component and iterated, actions[i].action or other properties will be undefined.

**Comment by jamesarosen** [comment]
@jludev1 the fundamental problem you seem to be up against is that you're trying to define objects at *eval* time rather than at *instantiate* time. ember-i18n hasn't been initialized and set up at eval time, so `t` couldn't possibly work.

My `hasI18n` suggestion basically turns the eval-time operation into an instantiate-time one. It's a workaround.

A different solution (as suggested by @rwjblue) is to do the `t` in the template:

```js
createButton: {
  titleKey:  'create', // define the translation *key*, not the *text*
  action: ‘create'
}),
```
and
```hbs
{{t action.titleKey}}
```

I think that's the best approach here.

**Comment by jludev1** [comment]
This will work if all the code are in house. But 3rd party components expects strings instead of keys, which means we need to go through the data structure to be passed in and do the translation in code. In certain scenarios, it could be worse than the wrapper approach.
