### ISSUE TITLE
Migrate translatable properties in textfields

### ISSUE THREAD

**Issue by abFx** [jamesarosen/ember-i18n#272]
What is the proper way to migrate translatable properties of textfields in this new version.

Reopening classes?
Mixins?

**Comment by jamesarosen** [comment]
Can you elaborate? Do you mean something like
```hbs
{{input value=user.email title='(t "user.email.title")' placeholder='(t "user.email.placeholder")'}}
```

**Comment by abFx** [comment]
Awesome, that's exactly what I was looking for, is that working now?

**Comment by jamesarosen** [comment]
I sure hope so!

**Comment by langalex** [comment]
I just tried this and it doesn't work for me:

    {{input placeholder='(t "form.title_placeholder")' }}

In the browser I see `(t "form.title_placeholder")` as the placeholder. Any idea?

I'm using Ember 1.13.3 and ember-18n 4.1.1.

**Comment by jamesarosen** [comment]
Try removing the quotes around the parentheses.

**Comment by langalex** [comment]
That obviously worked, thanks :)
