### ISSUE TITLE
Set Locale in initializer

### ISSUE THREAD

**Issue by jaimevent** [jamesarosen/ember-i18n#275]
I've read [here](https://github.com/jamesarosen/ember-i18n/wiki/Doc:-Setting-the-Locale) that's it's possible to set the Locale in an initializer, but I don't know exactly how?
I tried this, but it's not working:
```javascript
// app/initializers/set-locale.js

export function initialize(container, application) {
  var userLang = navigator.language || navigator.userLanguage;
  if (userLang.length > 3) {
      var langSplit = userLang.split('-');
      if (langSplit[0].length < 3){
          userLang = langSplit[0];
      } else {
          userLang = 'de';
      }
  }
  application.set('i18n.locale', userLang);
}

export default {
  name: 'set-locale',
  after: 'i18n',
  initialize: initialize
};

```

**Comment by kellyselden** [comment]
You're probably going to want to put it in an instance inititializer, then you can look it up via `instance.container.lookup('service:i18n')`

**Comment by jamesarosen** [comment]
I've updated that doc to show what I mean more clearly.
