### ISSUE TITLE
Access translations from inside hbs helpers

### ISSUE THREAD

**Issue by abFx** [jamesarosen/ember-i18n#279]
how do you access a translation from inside a helper?

    export function groupLink(params/*, hash*/) {
            url = "somethingfromparams";
	    return new Ember.Handlebars.SafeString('<a href="'+url+'">'+t("translatedText")+'</a>');
    }

**Comment by jamesarosen** [comment]
You'll need to use the new "stateful helper" form to get access to the `service:i18n` in a helper. See emberjs/rfcs#53.

**Comment by abFx** [comment]
awesome, thanks!

**Comment by galfert** [comment]
The "stateful helper" are only available in Ember 1.13. How do I access the the `t` helper in a helper in Ember 1.12?

**Comment by jamesarosen** [comment]
If Ember-I18n sees that you're on 1.12, it uses the private Stream API instead of a stayed up helper. You don't need to do anything different.

**Comment by jamesarosen** [comment]
Sorry, I misunderstood your most recent question.

I don't think there's a good way to do this in 1.12. Sorry.
