### ISSUE TITLE
i18n service t returns an Object

### ISSUE THREAD

**Issue by abFx** [jamesarosen/ember-i18n#280]
I'm injecting the i18n in a custom object, and when I try to retrieve a translated title, it returns an object, not the value.

I need to access by its string param

```
export default Ember.Object.extend({
    i18n: Ember.inject.service(),
    doSomething: function(){
         var defaultMessage = this.get('i18n').t('alert.errorDefault');
    }
});


//prints something like
SafeString {string: "Default message"}
```

The value returned works with templates I guess... and inside code should be access by value.string?

**Comment by jamesarosen** [comment]
See http://emberjs.com/api/classes/Ember.String.html#method_htmlSafe.

It defines a `valueOf()`, so you can concatenate it with other strings:
```js
'translated: ' + i18n.t('alert.errorDefault');
// "translated: Default message"

Ember.String.htmlSafe('one') + 'two' + Ember.String.htmlSafe('three');
// 'onetwothree'
```
But be warned: if you append an HTML-safe string to a plain (unsafe) string, you'll get a plain (unsafe) string. That means if you emit that into a template, the normal rules of HTML-escaping apply.

**Comment by abFx** [comment]
Thanks for the fast response... now feels likel I need to contribute to this lol

**Comment by rainerfrey** [comment]
I don't understand the need for this breaking change. Before 4.x, `I18n.t` returned a plain string, and the helper wrapped it as a `SafeString`.

Therefore you could transparently use string manipulation methods on values that could be strings from data or translated values. Still, the template escaping behavior was correct.
 
IMO it would be more appropriate if this layering was kept. The service is an abstraction that is meant to be used in any application code. It should not return an object that is very specific to template rendering.

**Comment by jamesarosen** [comment]
> Therefore you could transparently use string manipulation methods on values that could be strings from data or translations from I18n.

What manipulation methods can you not do on a `Handlebars.SafeString`?

The things I do every day work just fine:

```js
unsafe = 'a'
safe = Ember.String.htmlSafe(unsafe)

unsafe + safe // 'aa'
safe + unsafe // 'aa'
safe + 7 // 'a7'
7 + safe // '7a'
`${unsafe}${safe}` // 'aa'
unsafe == safe // true
safe == unsafe // true
[1, 2, 3].join(safe) // '1a2a3'

new Date('2015-04-17') // Thu Apr 16 2015 17:00:00 GMT-0700 (PDT)
new Date(Ember.String.htmlSafe('2015-04-17')) // Thu Apr 16 2015 17:00:00 GMT-0700 (PDT)
```

A lot of the `String` prototype methods *don't* work, though:

```js
safe.big()
safe.charAt()
safe.concat('b')
safe.match(/a/)
```

And the `String` prototype extensions *don't* either:
```js
safe.camelize()
safe.capitalize()
safe.classify()
safe.dasherize()
safe.decamelize()
safe.fmt()
safe.loc()
safe.pluralize()
safe.singularize()
safe.underscore()
safe.w()
```

> it would be more appropriate if this layering was kept

I don't necessarily disagree. I'd be interested to see an RFC to change it, but we can't do so until v5 since this is public API.

**Comment by rainerfrey** [comment]
The methods we use are:
* trim()
* match()
* split()

As I said, it is done where we use translated values in (mostly) controller code, and mostly when we pass values to non-ember libraries, where it depends on the input data whether we pass a model value or a translated label.

**Comment by jamesarosen** [comment]
You could probably monkey-patch around this for now:
```js
// app/utils/i18n/compile-template.js
import defaultCompileTemplate from "ember-i18n/utils/i18n/compile-template";

export default function compile(template, rtl = false) {
  const defaultTemplate = defaultCompileTemplate(template, rtl);
  return function render(data) {
    return '' + defaultTemplate(data);
  };
}
```
plus
```js
// app/initializers/i18n.js
import Ember from "ember";
import Helper from "ember-i18n/helper";
const SafeString = Ember.Handlebars.SafeString;

export default {
  name: 'i18n',
  initialize() {
    Helper.reopen({
      compute(params, interpolations) {
        const key = params[0];
        const i18n = this.get('i18n');
        return new SafeString(i18n.t(key, interpolations));
      }
    });
  }
};
```

**Comment by workmanw** [comment]
FWIW this kind of bit us too. We had some places where we trying to invoke native functions or do string comparison with return values from `Ember.I18n` and it was not a particularly easy thing to grep.

**Comment by jamesarosen** [comment]
We could introduce a new flag to move this to the helper. If we do, we should probably also let the macro specify whether the output should be wrapped.

**Comment by workmanw** [comment]
I think that would be really beneficial. Even if it defaulted to `SafeString=True`, having the ability to return regular strings would be really helpful in our app. It might also ease the pain for others upgrading to v4.

**Comment by jamesarosen** [comment]
We could do some combination of the following:

 1. `service:i18n` exposes a property, `markTranslationsSafe` that defaults to `true`
 1. `ENV.i18n.markTranslationsSafe` is the default value for `markTranslationsSafe`
 1. `service:i18n#t`, the `t` macro, and the `{{t}}` helper all obey `markTranslationsSafe` by default, but are overridable on a case-by-case basis

**Comment by cfator** [comment]
Really really really need this.  If I can buy the time I'll contribute but this seem like missing basic functionality.

**Comment by jamesarosen** [comment]
@cfator can you describe your use-case and why you can't accomplish what you need now? I understand that it can be a little annoying to convert from SafeStrings to plain strings, but you can do it.

**Comment by cfator** [comment]
That's the part I'm missing, how to convert a computed property to a string.

My situation is sometimes I have a i18n key for the string to display and
other times the server sends an already translated message that needs
displaying, so I end up doing something like this currently:

{{#if error}}
    {{#if error.needsTranslation}}
        {{t error.i18nKey}}
    {{else}}
        <p class="error-color">{{error.message}}</p>
    {{/if}}
{{/if}}

If I could just get the translated text in JavaScript it would simplify the
code alot.

**Comment by jamesarosen** [comment]
You can definitely get translated text in JS:
```js
export default Ember.Component.extend({
  i18n: Ember.inject.service(),
  error: null,

  errorMessage: Ember.computed('i18n.locale', 'error.needsTranslation', 'error.message', function() {
    if (this.get('error.needsTranslation')) {
      return this.get('i18n').t(this.get('error.i18nKey'));
    }
    return this.get('error.message');
  })
});
```
Those `t` calls will return `Handlebars.SafeString` instances, which you can use directly in your templates. I don't see your problems as related to this issue.

**Comment by cfator** [comment]
Thank you James, I understand now how this is done.

**Comment by tehmaestro** [comment]
Hi, I'm trying to apply the patch suggested above, but I get `Could not find module `ember-i18n/helper` imported from `mondly-app/initializers/i18n` . Any ideas? Thank you.

**Comment by pswai** [comment]
One potential issue is when a SafeString is copied.

As described at https://github.com/emberjs/ember.js/issues/14697, copied SafeString will have problem. Also, comparison like `Ember.String.htmlSafe('lala') == Ember.String.htmlSafe('lala')` fails since they are two different objects. This makes development a bit tricky that we need to check whether a string is primitive or SafeString.

**Comment by jamesarosen** [comment]
jamesarosen/ember-i18n has been deprecated in favor of [ember-intl](https://github.com/ember-intl).
