### ISSUE TITLE
Locales created using addTranslations don't appear in locales array

### ISSUE THREAD

**Issue by grantovich** [jamesarosen/ember-i18n#281]
The `locales` array seems to only include locales that are defined in `app/locales` modules. If you create a locale at runtime by calling `addTranslations` (e.g. if you are [loading translations from an API](https://github.com/jamesarosen/ember-i18n/wiki/Example:-Fetching-Translations-Live)), it will not show up in the array (e.g. if you are [displaying a language picker](https://github.com/jamesarosen/ember-i18n/wiki/Example:-Language-Chooser)). As a workaround I'll probably hardcode the list of locales in the language picker, but it would be nice to not have this knowledge duplicated between server and client.

**Comment by jamesarosen** [comment]
Nice catch. We'll probably have to do something like
```js
locales: computed(getLocales),

addTranslations(locale, translations) {
  addLocale(this.get('locales'), locale);
  ...
}

function addLocale(list, entry) {
  if (list.indexOf(entry) > -1) { return; }
  list.pushObject(entry);
}
```

**Comment by kellyselden** [comment]
@grantovich I submitted a fix for this in #282.

**Comment by jamesarosen** [comment]
Resolved in master

**Comment by grantovich** [comment]
Sweet, thanks @kellyselden for the fix!
