### ISSUE TITLE
Test suite is failing against Ember beta and canary

### ISSUE THREAD

**Issue by jamesarosen** [jamesarosen/ember-i18n#284]
Something in Ember has changed recently and started causing the test suite to fail. See, for example, https://travis-ci.org/jamesarosen/ember-i18n/jobs/73024548

**Comment by rwjblue** [comment]
https://travis-ci.org/jamesarosen/ember-i18n/builds/73068928 passed all test runs.  This can likely be closed (for now :trollface:).

**Comment by jamesarosen** [comment]
> This can likely be closed (for now :trollface:).

I enjoy you
