### ISSUE TITLE
Translate by locale tag

### ISSUE THREAD

**Issue by tehmaestro** [jamesarosen/ember-i18n#286]
Hi. I'm upgrading from ember-cli-i18n and this library seems awesome. However I have a problem.
 On ember-cli-i18n I used to do this: 
```
  var factory =  this.get('container').lookupFactory("locale:" + tag);
  return factory[this.get('key')];
```
Which would allow me to get the translation of a key in any language, not just the currently active one. How can I do the same with this library? Thanks.

Edit: This was quite simple, actually. I just needed to add a `/translations`.
```
var factory =  this.get('container').lookupFactory("locale:" + tag + "/translations");
```

**Comment by jamesarosen** [comment]
Yup!
