### ISSUE TITLE
Performance on locale change

### ISSUE THREAD

**Issue by Keeo** [jamesarosen/ember-i18n#287]
There is old issue #190 where is stated that you have to reload page on locale change. That's fine and somehow expected. Polluting large website with live bindings is large trade off for that one time when user wants to change locale. But mentioned issue ends with [wiki](https://github.com/jamesarosen/ember-i18n/wiki/Example:-Language-Chooser), containing locale change implementation. It's weird that there is no page reload, but maybe it is just expected that user writes code to reload page himself.

I was really surprised that it worked without reloading page and so I have to ask. Is it a performance concern like mentioned in that issue and if so is there configuration to disable it? I was not able to find any information about this except in [v4.0.0-beta.1](https://github.com/jamesarosen/ember-i18n/releases/tag/v4.0.0-beta.1) where is written that it works this way now.

**Comment by jamesarosen** [comment]
Before v4.0, the live-bindings to `locale` were a big performance problem, so we required a page reload. In v4+, which requires more modern versions of Ember, we have the tools (Streams and Stateful Helpers) to make live-bindings to `locale` work. You shouldn't need to do anything to make them work in v4+.

**Comment by Keeo** [comment]
Thank you for explanation.
