### ISSUE TITLE
Request for Comments: ember-i18n-test-helpers

### ISSUE THREAD

**Issue by thriqon** [jamesarosen/ember-i18n#288]
Hi all,

during the migration from `ember-cli-i18n` to `ember-i18n` we ran into the problem of being able to test localizing components in unit tests. Coming to the wiki looking for answers, we saw that this is pretty much an unsolved problem as of now.

Usually, you don't need to have the full-blown support for custom locales that `ember-i18n` provides when writing a unit test, a simple, _working_ environment fulfilling the requirements (an injected `t()` helper) is enough.

To ease the pain of setting up a i18n framework in a testing environment I wrote the lib [`ember-i18n-test-helpers`](https://github.com/thriqon/ember-i18n-test-helpers), which gives you an interface similar to the one `ember-i1n` provides, but controlled and injected entirely from within the unit test, like so:

``` javascript
beforeEach() {
  mockI18n()
    .with('global.now', 'NOW')
    .with('global.ago', params => 'AGO_' + params.seconds);
}
```

If you have any suggestions regarding API or implementation, please shoot me a message (or a PR...). If it is ok with you, I can also write a few sentences on integration into the wiki page.

**Comment by jamesarosen** [comment]
I really dig this. `.with('global.now', 'NOW')` seems fine. You might want to also support `.with({ ... })`.

I'm not sure what the future of testing with I18n is, but I think this really helps contribute to that conversation. Thanks!

**Comment by jamesarosen** [comment]
jamesarosen/ember-i18n has been deprecated in favor of [ember-intl](https://github.com/ember-intl).
