### ISSUE TITLE
Is it possible to use version 4+ w/o ember-cli?

### ISSUE THREAD

**Issue by OrKoN** [jamesarosen/ember-i18n#289]
Is something specific to ember-cli required in order to use the library?

**Comment by jamesarosen** [comment]
I don't think it's _required_, no. But you'd have to

 * run all the files through BabelJS
 * somehow convert them to globals (e.g. `EmberI18n.Service`)
 * concatenate them

**Comment by OrKoN** [comment]
@jamesarosen I did this with jspm. But I got a problem with lookups of translations: by keys like this `locale:${locale}/translations`. The error message was something like ${locale} (e.g. En) namespace is not defined. I already reverted my integration attempt but I thought the failure happens because the lib relies on some ember-cli resolver features.

**Comment by jamesarosen** [comment]
Yeah, you would probably need to duplicate some of that resolver functionality. Or override a bunch of functions in [Locale](https://github.com/jamesarosen/ember-i18n/blob/master/addon/utils/locale.js), but that's a private API.

I don't think it's going to be easy. If you manage to do it, let me know. We can add a page to the wiki on how to.

**Comment by jamesarosen** [comment]
Closing. Please let me know if you have any success with this. I'll gladly help turn it into a wiki article.
