### ISSUE TITLE
Acceptance testing w/ ember-cli 1.13.8

### ISSUE THREAD

**Issue by toranb** [jamesarosen/ember-i18n#291]
First off - love this project and thanks for all the hours you've put in maintaining it :)

I just upgraded from ember-cli 1.13.6 to 1.13.8 and found that even though my start-app does an import like so ...

```js
import t from "myapp/tests/helpers/t";
```

I started getting errors in application code that would reference it inside the assertion block (not hbs). This includes the following helper code to setup/register the service

```js
import Ember from 'ember';

export default Ember.Test.registerHelper('t', function(window, key, context) {
    return window.__container__.lookup('service:i18n').t(key, context);
});
```

I assume this is enough/over kill to get hbs code working in acceptance tests but how should I import "t" if I want to use it in my qunit assertions like so?

```js
test('we should find the name is translated for whatever reason', function(assert) {
    visit('/');
    andThen(() => {
        var model = store.find('foo', 123);
        assert.equal(model.get('name'), t("some.translation.key.here"));
    });
});
```

**update**

I ask because ember-cli now complains saying 

```
t["default"] is not defined
```

...when I run the test shown above. When I "debug" the test I just see t["default"]["default"]["default"] on and on.

**Comment by toranb** [comment]
Also -note for anyone else watching ... if you just want to work around this you can do the import in start-app like I show above/then add "t" to your globals (test .jshintrc file).

The real question here is how to use it w/out hacking on a global in test code

**Comment by jamesarosen** [comment]
Hmm. If you want to reference translations by key in tests, you're going to have to get access to the `I18nService` somehow. Perhaps this library should offer exactly the test helper you suggest:
```js
Ember.Test.registerHelper('t', function(app, key, context) {
    return app.__container__.lookup('service:i18n').t(key, context);
});
```

`foo["default"] is not defined` usually means you're importing or exporting something incorrectly. My strong guess is that the result of `Ember.Test.registerHelper` is `undefined`. In that case, I'd try changing your test helper to
```js
import Ember from 'ember';

Ember.Test.registerHelper('t', function(app, key, context) {
    return app.__container__.lookup('service:i18n').t(key, context);
});

export default function noop() {}
```

**Comment by toranb** [comment]
Awesome! Thanks for the insight @jamesarosen

**Comment by Nitijkatiyar** [comment]
If i add following line in t helper
```
export default function noop() {}
```
then translation text 
```
t("some.translation.key.here")
```
gives result as "undefined"

**Comment by jamesarosen** [comment]
I believe `import { t } from 'ember-i18n/test-support` only works if you're using [RFC-232-style tests](https://github.com/emberjs/rfcs/pull/232). Are you?
