### ISSUE TITLE
Ember 2.1.0-beta.1 compatibility

### ISSUE THREAD

**Issue by ismay** [jamesarosen/ember-i18n#292]
Usage with ember 2.0 results in the following error:

> Uncaught TypeError: Cannot read property 'register' of undefined

Which originates from line 21 of `ember-i18n.js`:

```javascript
      if (Helper['default'] != null) {
        instance.registry.register("helper:t", Helper['default']); // here
      }
```

This is with:
```
    "ember-cli": "^1.13.8",
    "ember-i18n": "^4.1.1",
    "ember-data": "^2.0.0-beta.1",
    "ember": "2.1.0-beta.1",

```

**Comment by rwjblue** [comment]
FYI - The title suggests this issue is for Ember 2.0, but it is actually for 2.1.0-beta.1...

**Comment by jamesarosen** [comment]
Try v4.1.2

**Comment by ismay** [comment]
That solved it for me, thanks!

**Comment by rwjblue** [comment]
Awesome, thanks for confirming!

**Comment by jamesarosen** [comment]
Closing. If you continue to have trouble, please reopen.
