### ISSUE TITLE
is it compatible with Ember 2.0 ?

### ISSUE THREAD

**Issue by baskarsugumar** [jamesarosen/ember-i18n#294]
Hello,

Just got upgraded to ember 2.0 from ember 1.13.7 and when starting the application, i got this error 

"Uncaught Error: Could not find module `ember-i18n/legacy-helper` imported from `apiclient/instance-initializers/ember-i18n`"

Can someone help me in solving this.

Thanks,
Baskar S

**Comment by jamesarosen** [comment]
The tests were passing against Ember-Canary as of a few weeks ago. They must have removed something in 2.0.

**Comment by jamesarosen** [comment]
`instance.registry.register` is no longer available in instance-initializers. We'll have to look for an alternative.

**Comment by jamesarosen** [comment]
Try v4.1.2

**Comment by jamesarosen** [comment]
Closing. If 4.1.2 doesn't help or if you continue to have trouble, please reopen.
