### ISSUE TITLE
ReferenceError: t is not defined in acceptance and integration specs

### ISSUE THREAD

**Issue by shicholas** [jamesarosen/ember-i18n#296]
Hello,

I was getting the above error when running acceptance tests (with StartApp in a beforeEach call) and in integration tests (tried both the initializer approach and registering the locale and helper). In both cases I kept seeing the error. I am running:

Ember: 1.13.8
Ember-I18n: 4.1.2

please let me know if you need more information, thanks.

**Comment by jamesarosen** [comment]
See #295
