### ISSUE TITLE
t helper could not be found

### ISSUE THREAD

**Issue by ronaldsuwandi** [jamesarosen/ember-i18n#297]
I'm using ember 1.13 with ember-i18n 4.1.1 and my integration test keeps failing with "Error: Assertion Failed: A helper named 't' could not be found" message. I've tried both running the initializer and registering i18n with no luck (https://github.com/jamesarosen/ember-i18n/wiki/Doc:-Testing)

```javascript
import tHelper from "ember-i18n/helper"; // tried with legacy-helper as well

moduleForComponent('blah-blah', 'Integration - components/blah-blah', {
  integration: true,
  beforeEach() {
    this.container.lookup('service:i18n').set('locale', 'en'); // container.lookup('service:i18n') returns undefined
    this.registry.register('helper:t', tHelper);
  }
});
```

```javascript
import initializer from 'app/instance-initializers/i18n';

moduleForComponent('blah-blah', 'Integration - components/blah-blah', {
  integration: true,
  beforeEach() {
    initializer.initialize(this);
  }
});
```

Am I missing something here?

**Comment by ronaldsuwandi** [comment]
now it suddenly resolved, i didn't even do anything.. this is just weird ಠ_ಠ

**Comment by tehmaestro** [comment]
Hi, I'm getting the same error, any ideas? Thanks.

**Comment by christopher-noq** [comment]
@tehmaestro any luck?

**Comment by tehmaestro** [comment]
I fixed it by removing node_modules and bower_componente and reinstalling all the packages

**Comment by christopher-noq** [comment]
Thanks @tehmaestro! I ended up upgrading to the latest version (was a few versions behind) and that sorted it out for me.
