### ISSUE TITLE
Interpolations with static values throwing errors

### ISSUE THREAD

**Issue by sridharpg** [jamesarosen/ember-i18n#300]
Hi!

Lets say I have this entry in `translations.js`

```javascript
message.marked.as.spam={{count}} marked as spam.
```

In my template:

```handlebars
{{#if notificationMessage}}
   <div class="ui message">{{notificationMessage}}</div>
{{/if}}
```

From my controller, I do this

```javascript
notificationMessage: null,

i18n: Ember.inject.service(),

done: function(count) {  //count = 3
     this.set('notificationMessage', t('message.marked.as.spam', {count: count});
}
```

I get the below error while the compiler tries to render this `notificationMessage`:

>Uncaught Error: Assertion Failed: The key provided to get must be a string, you passed 3.

From this [documentation](https://github.com/jamesarosen/ember-i18n/wiki/Doc:-Translating-Text) I understand that I can do this without errors by using a property in my controller, like this

```javascript
notificationMessage: null,

i18n: Ember.inject.service(),

count: 0,

done: function(count) {  //count = 3
     this.set('count', count);
     this.set('notificationMessage', t('message.marked.as.spam', {count: "count"});
}
```

But, is there a possibility of passing a *static* value instead of computed?

**Comment by jamesarosen** [comment]
[This test](https://github.com/jamesarosen/ember-i18n/blob/7af794ff5aaf6ec6e204d04375b89ef4c71af7bc/tests/unit/i18n-t-test.js#L11) seems to be doing about the same thing that you're doing, so I don't think the problem is the static value.

What is `t` in the scope of your controller? Are you sure you don't mean
```js
this.set('notificationMessage', this.get('i18n').t('message.marked.as.spam', {count: "count"}));
```

**Comment by sridharpg** [comment]
Hi James,

I import the `t` macro like this:

```javascript
import {
	translationMacro as t
}
from "ember-i18n";
```

The problem seems to lie in this method of `macro.js`:

```javascript
export default function createTranslatedComputedProperty(key, interpolations = {}) {
  return Ember.computed(values(interpolations), function() {
    const i18n = get(this, 'i18n');
    Ember.assert(`Cannot translate ${key}. ${this} does not have an i18n.`, i18n);
    return i18n.t(key, mapPropertiesByHash(this, interpolations));
  });
}
```

Where `values(interpolations)` returns only the values of the passed object, in my example `[3]`.

Let me know if you want me to create a dummy app to test this. I am not very sure about the quoted unit test.

**Comment by jamesarosen** [comment]
The `t` macro can't be used as a function call like you're doing. It's meant to define properties on an `Ember.Object` subclass. You want something like
```js
i18n: Ember.inject.service(),

count: 0,

notificationMessage: t('message.marked.as.spam', { count: 'count' }),

done: function(count) {  //count = 3
     this.set('count', count);
}
```

**Comment by sridharpg** [comment]
Thanks James, this helps.
