### ISSUE TITLE
"Object doesn't support this action" in IE8

### ISSUE THREAD

**Issue by jerel** [jamesarosen/ember-i18n#305]
It appears that this add-on supports Ember 1.3 but it fails in Internet Explorer 8 with the error `Object doesn't support this action`. Adding or removing the `{{t 'key'}}` helper or translation files has no effect; just adding `ember-i18n` to the package.json will take the app down.

Does anybody have an idea of where there might be incompatible code? I've been digging for a while and haven't found anything but `Object.keys` which is polyfilled.

**Comment by jamesarosen** [comment]
Which version of Ember-I18n are you using? v4 requires Ember v1.12+. For Ember 1.3, you want an earlier version. I'm not exactly sure which would work best. I'd suggest trying v2 and v3.

**Comment by jerel** [comment]
Oops, I see I missed a 1 in my earlier comment so it said Ember 1.3. I'm on v4.1.2 on Ember 1.13.7

**Comment by jerel** [comment]
Yes it is. For some reason Github didn't automatically link based on my commit message and I didn't notice until now
