### ISSUE TITLE
YAML support

### ISSUE THREAD

**Issue by jasonmit** [jamesarosen/ember-i18n#308]
Would you be opened to adding YAML support?  If so, I would be happy to send a PR.

**Comment by jamesarosen** [comment]
Probably not, since ES6 modules are really the standard for Ember-CLI. I would, however, absolutely be open to making sure there's a good public API that you could hook into for lookup. There's already [`addTranslations`](https://github.com/jamesarosen/ember-i18n/blob/7af794ff5aaf6ec6e204d04375b89ef4c71af7bc/addon/services/i18n.js#L53-L60).

**Comment by jasonmit** [comment]
I think it's important to move to a structure where translations are not bundled with the app.  Instead included dynamically on the server.  So when you consider that, ES6 modules no longer hold value.  Also, most translation software I've used work mainly against YAML and JSON

**Comment by jamesarosen** [comment]
The feedback I got was that people really liked the ease of bundling translations with the app -- that feature came from dockyard/ember-cli-i18n.

But the original project that I built Ember-I18n for (Zendesk) loads translations from an API. Thus, when I incorporated ideas from the dockyard project, I made sure to keep `addTranslations` as a way of supporting the API version.

Shipping a YAML parser with the project is definitely too much bloat for use case that has never yet come up. But if you had a YAML parser in your app already, loading translations from a YAML API would be pretty straightforward:

```js
import { request } from "ic-ajax";
import parseYaml from "some-yaml-parser";

ApplicationRoute = Ember.Route.extend({
  i18n: Ember.inject.service(),

  beforeModel() {
    const locale = this.get('session.user.locale');
    return request({
      url: `/translations/${locale}.yaml`
    }).then((yaml) => {
      const json = parseYaml(yaml);
      this.get('i18n').addTranslations(locale, json);
    });
  }
});
```

**Comment by jasonmit** [comment]
```
beforeModel() {
    const locale = this.get('session.user.locale');
    return request({
      url: `/translations/${locale}.yaml`
    }).then((yaml) => {
      const json = parseYaml(yaml);
      this.get('i18n').addTranslations(locale, json);
    });
  }
```

is exactly what I want to avoid since we're blocking the app from loading while I fetch a translation.  My approach is to send the translations down in the initial payload and I can invoke `addTranslations` on init with the data I already have.

> Shipping a YAML parser

ember-i18n would never be sending down YAML to the client, it would be basically how ember-intl works today.  Where you maintain translations in JSON or YAML format and a build step takes care of converting them to modules.  The consumer has no knowledge of this and they now can maintain their translations in formats that are widely supported.

**Comment by jamesarosen** [comment]
> it would be basically how ember-intl works today

ember-intl used to use ICU and require an ICU parser the browser. Though that may have changed in v2.0.

These two statements seem in conflict:

> I think it's important to move to a structure where translations are not bundled with the app. Instead included dynamically on the server.

> Where you maintain translations in JSON or YAML format and a build step takes care of converting them to modules.

Maybe you can explain more fully the architecture you envision.

 * Are translations stored in the Ember app project?
 * Do they get compiled into `application.js`? If so, do you have `application-en.js`, `application-es.js`, etc?
 * Who chooses which translations to load? If the server, what sort of server architecture are you assuming? Is there a particular URL scheme? A technology stack? If the client, how do you avoid blocking loading on fetching the translations?

**Comment by jasonmit** [comment]
> ember-intl used to use ICU and require an ICU parser the browser. Though that may have changed in v2.0.

I'm not sure what you're referring to.   I was saying that the JSON/YAML conversion to modules at build time is what happens today within ember-intl.

> Are translations stored in the Ember app project?

Optionally but also optionally one level out of `app` on the project root to avoid bundling.

> Do they get compiled into application.js? If so, do you have application-en.js, application-es.js, etc?

If included in `app`, they get bundled int app.js.  Otherwise, no.

> Who chooses which translations to load

The express middleware determines this based on some dimensions and context.  This is not something I plan to roll into either project.

**Comment by jamesarosen** [comment]
> If included in app, they get bundled int app.js. Otherwise, no.

We can't assume that people using Ember-I18n even have an app server, so we can't assume that they'll be added to `app.js` dynamically. Thus, there will have to be a way to fetch them at runtime.

Let's assume they get compiled to something like `assets/translations/en-US.js`. Here are some ideas on the runtime fetch API:

```js
export default Ember.Route.extend({
  i18n: Ember.inject.service(),

  beforeModel() {
    // default to `assets/translations/en-US.js`. If that request fails, it will then
    // try `assets/translations/en.js`.
    return this.get('i18n').fetchTranslations('en-US');

    // An optional second argument gets passed to ic-ajax, so you can pass a path:
    return this.get('i18n').fetchTranslations('en', 'https://my.translation.service/translations/en.js');

    // or an AJAX object:
    return this.get('i18n').fetchTranslations('en', {
      type: 'POST',
      url: '/rpc?action=get-translations&locale=en'
    });
  }
});
```

Alternatively, we could embed the `en-US` translations into an `app-en-US.js` during compile-time. That still doesn't assume an app server. It does mean that there has to be a web server capable of some simple routing. Varnish, nginx, and Apache are all capable of rewriting URLs based on the `Accept-Language` header or a cookie.

**Comment by jasonmit** [comment]
> We can't assume that people using Ember-I18n even have an app server, so we can't assume that they'll be added to app.js dynamically. Thus, there will have to be a way to fetch them at runtime.

Let's just talk at a high-level and worry about the implementations a bit later once I have buy-in.  But since you seem skeptical, if the consumer declares their translations on the project root (not within app) they're opting out of it bundling into app.js.  And in this case, it would (at build time) make sure these translations are written to the asset folder (dist).  The location of where it writes to within the dist will be fully configurable.

Now, they can do what you're proposing by loading the translations at some point during runtime or preload the initial payload with those translations.  Again, something I have fully functioning and something I would document in a wiki or something on how that can be achieved without blocking the UI to make a call on initialization.

The building of an app per locale seems interesting, but not sure necessary in this case.

**Comment by jamesarosen** [comment]
Some open questions:

 * if not in `app/`, where would translations live by default? A guess: `config/locales/*/translations.js`
 * where exactly would the translations be compiled to by default? A guess: `dist/assets/translations-*.js`
 * how could an app developer configure those paths? My guess is options in `ember-cli-build.js`

**Comment by jasonmit** [comment]
> if not in app/, where would translations live by default?

Open to ideas.  The way I currently handle it in ember-intl is hang them off the project root folder.

> if not in app/, where would translations live by default?

Correct and should be configurable

> how could an app developer configure those paths? A guess: in

Correctly, I handle this through config/environment but ember-cli-build is likely the more appropriate place for it.

**Comment by jamesarosen** [comment]
I want to start trying this out in my app. My use-case: I want to exclude translations from `app.js` and compile them to their own `.js` files, then load them asynchronously on boot. Maybe we could start a branch to collaborate? We may want to work on #255 first as it changes some organization substantially.

**Comment by jasonmit** [comment]
Awesome, would love to help :+1:

Do you want the translations to be concatted into one file or one per locale?

**Comment by jamesarosen** [comment]
> Do you want the translations to be concatted into one file or one per locale?

One per locale. I want to do something like `this.get('i18n').fetchTranslations('en-US');` in code when the user selects a locale.

**Comment by jasonmit** [comment]
> One thing I might want to do is populate app/locales/*/translations with empty JS objects so the service:i18n knows the list of supported locales.

We could maybe do this from within the config hook of `index.js`.  I need to think more about it, but agree with the general idea.

I can take a first pass this weekend based on what we discussed.

**Comment by GCheung55** [comment]
The discussion on loading and bundling translations has been great. Is there any update or movement on this?

**Comment by jasonmit** [comment]
Nothing to report on my end, I've been busy working on a few things.  I should have cycles this weekend to spike something.

**Comment by jasonmit** [comment]
@GCheung55 the functionality exists in ember-intl, I just need to be able to abstract it away into perhaps its own broccoli plugin that can be shared between the two projects.

https://github.com/jasonmit/ember-intl/blob/master/packages/ember-intl/lib/broccoli/translation-reducer.js

It takes a deeply nested directory of json or yaml files and reduces all the translations by locale code.

**Comment by gzurbach** [comment]
I have the same issue. My translation files are currently living on the server and I'd like to bundle them in the app (for convenience). However, the localization platform I'm using (crowdin) does not support `.js` files.

It'd be awesome to have the JSON files at the root and added to the project at build time.

**Comment by jamesarosen** [comment]
jamesarosen/ember-i18n has been deprecated in favor of [ember-intl](https://github.com/ember-intl).
