### ISSUE TITLE
The latest beta for ember 2.1 removes the first arg in initializers

### ISSUE THREAD

**Issue by toranb** [jamesarosen/ember-i18n#309]
https://github.com/jamesarosen/ember-i18n/blob/master/app/initializers/ember-i18n.js#L6

Upgrading to ember 2.1 beta 2 I noticed this was causing a dep warning. Any plans to remove it in an up coming release?

Thanks again for such a great OSS project!

**Comment by toranb** [comment]
It also looks like another dep warning shows up in 2.1 for instance initializers using "lookup" on the container

```
"Using `ApplicationInstance.container.lookup` is deprecated. Please use `ApplicationInstance.lookup` instead."
```

The code itself that's a "problem" now is this line

https://github.com/jamesarosen/ember-i18n/blob/master/app/instance-initializers/ember-i18n.js#L14

**Comment by toranb** [comment]
Update -the instance initializer dep warning looks to have come from v2.1.0-beta.3

**Comment by jamesarosen** [comment]
So we could change the line to
```js
const key = 'service:i18n';
const i18n = instance.lookup ? instance.lookup(key) : instance.container.lookup(key);
i18n.set('locale', defaultLocale);
```

**Comment by jamesarosen** [comment]
We can't remove the classic initializer until v5.0 because we need to support Ember 1.11.

**Comment by toranb** [comment]
To keep ember 1.x and 2.1 happy you could use this approach in the initializer (what @rwjblue recommended earlier today)

https://github.com/toranb/ember-cli-simple-store/commit/1f68d63e445a83b9298d03c9bbf95af7b93680d7

**Comment by toranb** [comment]
@jamesarosen I've got no issue submitting the PR myself but wanted to ask if you knew about it/had plans to solve this cross ember 1/2 issue :)

**Comment by jamesarosen** [comment]
I didn't know about it. I'd love a PR. I like the solution from `ember-cli-simple-store` plus trying `instance.lookup` before falling back to `instance.container.lookup`.

**Comment by toranb** [comment]
I just pushed a fix for this and it's working/solid for ember 2.1 beta 3

thanks @jamesarosen 

https://github.com/jamesarosen/ember-i18n/pull/311/files
