### ISSUE TITLE
inject i18n in router

### ISSUE THREAD

**Issue by 1STi** [jamesarosen/ember-i18n#310]
Hi! 

Thank you very much for this excellent project.

I need to i18n my route, like this post:
http://discuss.emberjs.com/t/internationalization-route/1266

But i cannot inject i18n ou Router on version 4.1.2. Cannot lookup container.

Is there a way to do that?

Cheers!

**Comment by jasonmit** [comment]
I think you would need to do this within an instance-initializer.  I don't know how you would do it otherwise.

```js
// app/instance-initializers/i18n-route.js
import Ember from 'ember';

export default {
  name: 'i18n-register-translations',
  initialize(instance) {
      let i18n = instance.container.lookup('service:i18n');
      let router = instance.container.lookupFactory('router:main');

      // will not interfere with your router.js, they basically get joined
      router.map(function() {
        this.route('books', { path: I18n.t('route.books') });
      });
  }
};
```

**Comment by jamesarosen** [comment]
Thanks for this excellent answer, @jasonmit :)

**Comment by 1STi** [comment]
Thanks @jasonmit !!!

**Comment by daminufe** [comment]
Thanks @jasonmit! Was really useful also for my case.

**Comment by oskarrough** [comment]
Thank you. We should bring this snippet into the documentation. For anyone searching and ending up here, with Ember 2.3.0 I had to replace the `Router` line with this:

`const Router = appInstance.resolveRegistration('router:main');`

**Comment by locks** [comment]
@oskarrough how you inject this library should be the same how you inject others, and is generally address by [Application Concerns](https://guides.emberjs.com/v2.3.0/applications/applications-and-instances/) in the guides.
This isn't an argument against, just complimentary info.

**Comment by jasonmit** [comment]
For any future travelers, Router.map will leak in fastboot see: https://github.com/emberjs/ember.js/issues/13840

For that reason, I've created way of achieving this w/o the user of an instance initializer or invoking Router.map from within an app instance.

https://github.com/jasonmit/ember-routermap-inject-service

**Comment by jasonmit** [comment]
> @jasonmit Would your addon work around this issue?

The addon doesn't use Router._router so it should be fine.
