### ISSUE TITLE
Capitalization

### ISSUE THREAD

**Issue by kgish** [jamesarosen/ember-i18n#314]
Is there an easy way to capitalize a given translation?

**Comment by jamesarosen** [comment]
There's [`Ember.String.capitalize`](http://emberjs.com/api/classes/Ember.String.html#method_capitalize).  There's nothing locale-aware. (For example, lowercasing a noun in German is nonsense.)

**Comment by kgish** [comment]
Right, but how to combine with `{{t 'string'}}` to capitalize this?

**Comment by jamesarosen** [comment]
You'd need to write your own capitalize helper:
```js
// app/helpers/capitalize.js
import Ember from "ember";
const capitalize = Ember.String.capitalize;

export default Ember.Helper.helper(function([ string ]) {
  return capitalize(string);
});
```
and then use it like so:
```hbs
{{capitalize (t "my.string")}}
```

**Comment by kgish** [comment]
Great, thanks!
