### ISSUE TITLE
accessing translations from a util function

### ISSUE THREAD

**Issue by robneville73** [jamesarosen/ember-i18n#316]
Almost 100% of my translation needs are translating responses from a server. So whenever I need to translate a response from within the code somewhere I have to go through some gyrations to conform to my server's error responses into a form that i18n can use. Thus, I've done this historically in a util function.

However, now I'm left with a problem. I can't inject the i18n service into a util function and although I can get access to the translation macro, that's not terribly useful in this context because it's not something I can assign to a property. In the past I had access directly to i18n from the global Ember object. I get that that's no longer idiomatic Ember, but short of passing a direct reference to i18n from various bits of code to my util function, any ideas on how to solve that problem?

**Comment by jamesarosen** [comment]
You could copy the service to a global in an initializer:
```js
// app/instance-initializers/export-i18n.js
export default {
  name: 'export-i18n/,
  after: 'i18n',
  initialize({ container }) {
    window.I18n = container.lookup('service:i18n');
  }
};
```

**Comment by robneville73** [comment]
True, though kinda ugly. I mean I've solved the issue by just passing the
handle to i18n from the calling context which has had it injected and that
works. Was just curious if there was a better way.

On Fri, Sep 25, 2015 at 1:00 PM, James Alexander Rosen <
notifications@github.com> wrote:

> You could copy the service to a global in an initializer:
>
> // app/instance-initializers/export-i18n.jsexport default {
>   name: 'export-i18n/,  after: 'i18n',  initialize({ container }) {    window.I18n = container.lookup('service:i18n');  }};
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jamesarosen/ember-i18n/issues/316#issuecomment-143283056>
> .
>



-- 
Rob Neville
RetailArchitects
(888) 891-4511 x801
-----------------------------------------------
For Support: (888) 891-4511 Option 1 or support@retailarchitects.com
