### ISSUE TITLE
Deprecation warning in Ember 2.1

### ISSUE THREAD

**Issue by jamesdixon** [jamesarosen/ember-i18n#317]
Hi,

When upgrading to Ember 2.1, I get the following deprecation warning:

```DEPRECATION: When calling `Ember.warn` you must provide an `options` hash as the third parameter.  `options` should include an `id` property. [deprecation id: ember-debug.warn-options-missing] See http://emberjs.com/deprecations/v2.x/#toc_ember-debug-function-options for more details.```

Tracking it down, it appears to links to [this line](https://github.com/jamesarosen/ember-i18n/blob/master/addon/utils/locale.js#L35) in `locale.js`. I was going to attempt to update it and do a PR, but wasn't sure on what exactly was needed to satisfy the deprecation as I was having difficulty tracking down exactly what `Ember.warn()` does.

If you can point me in the right direction, I'd be more than happy to work up a PR.

Best,
James

**Comment by locks** [comment]
I believe it is related to the changes in 2.1 with regards to the deprecation warnings: http://emberjs.com/blog/2015/10/04/ember-2-1-released.html#toc_deprecate-and-warn-handlers.

**Comment by jamesarosen** [comment]
Nice investigation :)

I think we can just add `, { id: 'ember-i18n.locale-lacks-rtl' }` to that `Ember.warn` call.

**Comment by jamesdixon** [comment]
Thanks @jamesarosen @locks. I took a stab at making the update [here](https://github.com/jamesdixon/ember-i18n). However, I still receive a deprecation warning for the case in which a default locale wasn't specified. Would you mind having a peek?

**Comment by davidsteinberger** [comment]
@jamesarosen @locks The ember-debug-handlers got changed with [PR 11833](https://github.com/emberjs/ember.js/pull/11833/files). So shouldn't all warn calls have the signature (*message*, *test*, *options*)?

E.g. services/i18n.js:

        warn('ember-i18n did not find a default locale; falling back to "en".', true, { id: 'ember-i18n.default_locale'});

**Comment by robneville73** [comment]
+1 ..same issue here.

**Comment by davidsteinberger** [comment]
@jamesarosen Thanks! Is this going to be release on npm soon?

**Comment by jamesarosen** [comment]
Probably. No specific release schedule. Depends on how many other PRs I can attend to in the next couple days.
