### ISSUE TITLE
Using ember-i18n in defaultValue of model property

### ISSUE THREAD

**Issue by alexanderjeurissen** [jamesarosen/ember-i18n#318]
I'm migrating from an older ember application to ember-cli,

previously we used the i18n gem and had the following code work in our model:

```javascript
LS.Chapter = DS.Model.extend({
 name: DS.attr('string', { defaultValue: I18n.t('chapter.titleValue') })
})
```

I'm kinda stuck on implementing this using ember-i18n
I tried the following:

```javascript
import { translationMacro as t } from "ember-i18n";

export default DS.Model.extend({
 name: DS.attr('string', { defaultValue: t('chapter.titleValue') })
})
```

but that won't work because the translationMacro is a computed property.
ember-cli-i18n automatically injects the `t` helper in all models, but I'm kinda stuck getting this to work with ember-i18n

Do I need to write a initialiser to inject the i18n service ? or how would you solve this ?

**Comment by alexanderjeurissen** [comment]
Ok I found a solution to my problem the following code works:

```javascript
export default DS.Model.extend({
    i18n: Ember.inject.service(),
    name: DS.attr('string', { 
        defaultValue: function (self) {
            self.get('i18').t('chapter.titleValue')
        }
    })
})
```

**Comment by jamesarosen** [comment]
Nice solution!
