### ISSUE TITLE
Translation with interpolated values

### ISSUE THREAD

**Issue by kgish** [jamesarosen/ember-i18n#324]
The documentation about interpolated values is not clear and would be improved if you showed how it works

```
user.followers.title => 'All {{count}} Followers'
```

https://github.com/jamesarosen/ember-i18n/wiki/Doc:-Translating-Text

**Comment by jamesarosen** [comment]
What information would you like?

**Comment by kgish** [comment]
Just including the syntax for the interpolated string as above. Does that make sense or am i missing something obvious? Thanks!

**Comment by jamesarosen** [comment]
The format is defined in [Defining Translations](https://github.com/jamesarosen/ember-i18n/wiki/Doc:-Defining-Translations)
