### ISSUE TITLE
Using via service injection or initializers

### ISSUE THREAD

**Issue by BrianSipple** [jamesarosen/ember-i18n#330]
Hello,

I'm currently having trouble using this utility (v4.1.4) in an Ember 2.0.0 / Ember-Cli 1.13.8 application. 

Having already performed ```ember install ember-i18n```, attempting to inject the service into a component by doing ```i18n: Ember.inject.service()``` throws the following error:
```
Assertion Failed: Attempting to lookup an injected property on an object without a container, ensure that the object was instantiated via a container.
```

Alternatively, implementing the injection in an initializer ([as described in the docs](https://github.com/jamesarosen/ember-i18n/wiki/Doc:-i18n-Service#i18n-service)) like so...

```
// app/initializers/i18n.js

export function initialize(registry, application) {
  application.inject('component', 'i18n', 'service:i18n');
};

export default {
  name: 'i18n',
  after: 'ember-i18n',
  initialize: initialize
};

```

... performing ```this.get('i18n')``` inside of a component simply returns ```undefined```.

Am I just overlooking a step that's involved with wiring everything up properly?

**Comment by jamesarosen** [comment]
Somewhere in your code you must have something like the following:
```js
var Foo = Ember.Object.extend({
  it18n: Ember.inject.service()
});
...
Foo.create();
```
The problem is that you're instantiating `MyClass` without giving the instance a `container`. You'll need to instantiate it from somewhere that has a `container` (a Route, Controller, Service, or Component) and pass it in:
```js
foo: Ember.computed(function() {
  return Foo.create({ container: this.container });
})
```

**Comment by jamesarosen** [comment]
(If I'm wrong, please post some of your component code and I'll take another look.)

**Comment by BrianSipple** [comment]
Yep, you're right -- I totally overlooked this. 

Registering the object with a container -- WHILE ALSO injecting the service into it -- in my i18n initializer did the trick:

```
// part of app/initializers/i18n.js

    object.reopen({
      container: application.__container__,
      i18n: Ember.inject.service()
    });
```
