### ISSUE TITLE
Overriding `missingMessage()` of addon?

### ISSUE THREAD

**Issue by camatangelo** [jamesarosen/ember-i18n#331]
I can't seem to override the `missingMessage` function from an addon that I'm developing (that's using emberi-18n) unless I declare the function directly within the dummy app. I expected to be able to override from the addon itself e.g. within `addon/utils/i18n/missing-message.js`, and exporting the function from `app/utils/i18n/missing-message.js` - as opposed to overriding in `tests/dummy/app/utils/i18n/missing-message.js`. 

Any thoughts/recommendations?

**Comment by jamesarosen** [comment]
I think you want to put the file in `app/utils/i18n/missing-message.js`.

**Comment by jamesarosen** [comment]
I'm not sure. I've never tried overriding one addon's exports in another addon. I'd ask the Ember-CLI folks about which takes precedence. It may be alphabetical or random.

**Comment by jasonmit** [comment]
You can change the order in which your addon is included:

```js
// package.json
// ...
"ember-addon": {
  "configPath": "tests/dummy/config",
  "after": [
    "ember-i18n"
  ]
}
```

**Comment by jamesarosen** [comment]
jamesarosen/ember-i18n has been deprecated in favor of [ember-intl](https://github.com/ember-intl).
