### ISSUE TITLE
Default to count 1 if not provided

### ISSUE THREAD

**Issue by Fed03** [jamesarosen/ember-i18n#332]
Hi, I'm using this awesome addon and it works great. 
But I think it can be improved in one thing.

Given this

```
// translation.js
"pluralizableWord": {
  "one": "singular",
  "other": "plural"
}
```

I think it would be a better UX if when I'm doing `{{t "pluralizableWord"}}` it would spit out `"singular"`.
In other words, if a localization string is marked for pluralization but count is not provided use the `"one"` version.

let me know what do you think about it. Maybe I could help with a PR if you find it apprpriate

**Comment by jamesarosen** [comment]
The problem with this idea is that this is a totally valid set of translations:
```js
{
  pancakes: 'Some number of pancakes',
  'pancakes.one': 'One pancake',
  'pancakes.other': '{{count}} pancakes'
}

t('pancakes', { count: null }); // 'Some number of pancakes'
```

**Comment by jamesarosen** [comment]
jamesarosen/ember-i18n has been deprecated in favor of [ember-intl](https://github.com/ember-intl).
