### ISSUE TITLE
Can't initialize i18n service

### ISSUE THREAD

**Issue by benoittgt** [jamesarosen/ember-i18n#333]
Hello

I'm trying to use i18n into a controller. I've install it, add an initialiser : 
```javascript
//app/initializers/i18n.js

export default {
  name: 'i18n',

  after: 'ember-i18n',

  initialize: function(_, app) {
    app.inject('controller', 'i18n', 'service:i18n')
  }
};
```

On my controller I have something like this : 

```javascript
// app/controllers/application.js

import Ember from 'ember';

export default Ember.Controller.extend({
  isLoading: false,
  searchQuery: '',
  goBackRoute: '',
  goBackName: function() {
    var currentRoute = this.get('currentRouteName');
    this.set('goBackRoute', currentRoute + 's');
    return i18n.t('menu.'+ currentRoute + 's');
  }.property('currentRouteName'),

 //...
  }
});
```

But I get and error `i18n not defined`. I've tried to add manually : 

```javascript
export default Ember.Controller.extend({
  i18n: Ember.inject.service(),
  //...
});
```

Same error. `this.get('i18n')` is undefined. Do I miss something earlier ? 

I'm using ` "ember-i18n": "4.1.4",  "ember-cli": "1.13.8", "ember": "2.0"`

**Comment by benoittgt** [comment]
My initializer was simply in the wrong place. It's works now.

**Comment by jamesarosen** [comment]
:smile_cat:

**Comment by rizkytahara** [comment]
@benoittgt may i know where should i put the initializer? since i have the same problem and cannot find to configure it out..

**Comment by benoittgt** [comment]
@rizkytahara something like https://github.com/AtelierCartographie/Khartis/blob/ae64fc8f9a57725e3c84aeb798174d5feb036be0/app/initializers/i18n.js :)

**Comment by rizkytahara** [comment]
thanks, but i already did that before and i still cannot call it from the controller.
calling `this.i18n.t('message.success.save')` from the route works; but from the controller, it says `undefined`... any idea how should i call it from the controller?

**Comment by jamesarosen** [comment]
`inject.service()` is _lazy_, which means you need to do `this.get('i18n')`, not `this.i18n`.

**Comment by rizkytahara** [comment]
`this.i18n.t` and `this.get('i18n').t` works when calling from route..

from controller.. i got `Uncaught TypeError: this.get is not a function` when i did `this.get('i18n').t`

**Comment by jamesarosen** [comment]
Let's see the controller code. Controllers definitely have `this.get`. Perhaps you're trying to call it in the wrong scope, like in a promise callback that's not bound to `this`.

**Comment by rizkytahara** [comment]
app/initializers/i18n.js


here is my controller:

    import Ember from 'ember';

    export default Ember.Controller.extend({
      crudTable: {
        columns: [
          {
            key: 'description',
            label: this.get('i18n').t('field.description')
          },
        ],
      },
    });

did i miss something?

**Comment by rizkytahara** [comment]
app/initializers/i18n.js

    export function initialize(application) {
      const types = ['model', 'controller', 'route', 'component', 'view'];

      types.forEach((type) => {
        application.inject(type, 'i18n', 'service:i18n');
      });
    }

    export default {
      name: 'i18n',
      after: 'ember-i18n',
      initialize
    };

app/pods/master/index/controller.js

    import Ember from 'ember';

    export default Ember.Controller.extend({
      crudTable: {
        columns: [
          {
            key: 'description',
            label: this.get('i18n').t('field.description')
          },
        ],
      },
    });

did i missed something?

**Comment by jamesarosen** [comment]
```js
export default Ember.Controller.extend({
  crudTable: {
    columns: [
      {
        key: 'description',
        label: this.get('i18n').t('field.description')
      },
    ],
  },
});
```

The problem is that where you're calling `this.get` isn't in the controller instance. The scope you're in there is simply the global require-js scope. You may find #352 helpful, though it's for a slightly different case.

If you want `crudTable` to have translated properties, you can't define it statically. It has to be a computed property like
```js
crudTable: computed('i18n.locale', function() {
  const i18n = this.get('i18n');

  return {
    columns: [
      {
        key: 'description',
        label: i18n.t('field.description')
      }
    ]
  };
})
```

**Comment by rizkytahara** [comment]
@jamesarosen Thank you! It worked
