### ISSUE TITLE
Test for missing translations

### ISSUE THREAD

**Issue by jelhan** [jamesarosen/ember-i18n#339]
I like to test my application against missing translations in different locales. What's the best practice to do so? I have written a working test (https://github.com/jelhan/croodle/commit/c5a42ce9d8eb8864ccfaa1787de1bddf4fd81d4f) but it looks like crap. Would like to hear how others solved this issue and perhaps work together to improve documentation.

**Comment by blimmer** [comment]
I throw exceptions when encountering a missing translation in tests.

```javascript
// app/utils/i18n/missing-message.js

export default function(locale, key/* , context */) {
  const msg = `Missing translation for key: ${key}`;
  reportError(msg); // newrelic

  // fail tests with missing translation
  if (ENV.environment === 'test') { throw new MissingTranslationError(msg); }

  return msg;
}
```

```javascript
// app/utils/missing-translation-error.js
function MissingTranslationError(message) {
  this.name = "MissingTranslation";
  this.message = message;
  this.toString = function() {
    return `${name}: ${message}`;
  };
}
```

It is much slower than your solution because you'd need to run tests for each locale, but wanted to share.

**Comment by blimmer** [comment]
@jamesarosen what do you think about throwing errors by default in test environments when encountering a missing message? idk if that's too heavy handed for the addon to do. I will happily PR if it seems useful.

**Comment by jamesarosen** [comment]
> what do you think about throwing errors by default in test environments when encountering a missing message?

Great for app authors; possibly bad for addon authors. Let's try to explore the cases where someone _wouldn't_ want that.

**Comment by blimmer** [comment]
There are definitely times in my app that I expected an error to be thrown in test. In this case, I was testing to make sure that my app could handle an unexpected piece of content in the payload. In this example, we dynamically look up a translation (something like this):

```js
return this.get('i18n').t(`myBaseKey.${this.get('somethingElse')`); // no translation for my test value
```

In that case I had to do this in my test:

```js
    it('is not visible if translation is missing', function() {
      try {
        this.set('setting.settingName', 'idontexist');
        this.render(hbs `{{setting-option option=setting}}`);
        componentDoesNotHaveElement(this, '.setting-option:visible');
      } catch (MissingTranslationError) {} // Eat the error we throw
    });
```

It might be too much to ask users to deal with that, but I'm open to ideas.

**Comment by jamesarosen** [comment]
jamesarosen/ember-i18n has been deprecated in favor of [ember-intl](https://github.com/ember-intl).
