### ISSUE TITLE
installation process for v3.1.1 incorrectly inserts 4.x into bower.json

### ISSUE THREAD

**Issue by asross** [jamesarosen/ember-i18n#341]
I have a commit [here](https://github.com/asross/ember-i18n/commit/1946bd231fbc2bb281bfe054a234bfea4bd3ff19) with an explanation of the problem and a fix, but I can't make a pull request because there's no 3.x branch.

**Comment by jamesarosen** [comment]
[There is now](https://github.com/jamesarosen/ember-i18n/tree/v3)!

**Comment by asross** [comment]
Thanks :)
