### ISSUE TITLE
Add documentation on tools to manipulate the translation files?

### ISSUE THREAD

**Issue by Kilowhisky** [jamesarosen/ember-i18n#343]
Probably not a bug and more a request. I have my keys for my app all filled out in their translations.js and now i don't quite know what to do with the files. The docs don't quite say if any translation tools can accept and mainupulate the translation.js file.    I can't quite ship the raw JSON files out to my translators. What have people done with them? I suspect the roll their own tool to export/impor to excel or something like that...

**Comment by kellyselden** [comment]
Here are some tools for you https://github.com/jamesarosen/ember-i18n/wiki/Links#related-tools-and-projects

**Comment by Kilowhisky** [comment]
Thanks! the to-CSV and to-JS are perfect!
