### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by kgish** [jamesarosen/ember-i18n#344]
I'm a happy user of the `ember-i18n` addon and have lots of tests running on controllers which use it.

Unfortunately the only way to get it to work is by adding tons of extra code, as shown here:

https://github.com/jamesarosen/ember-i18n/wiki/Doc:-Testing

Has anyone thought about this any further?

**Comment by vvscode** [comment]
What for do you need translations inside unit tests? Is there translation or not -- it doesn't metter for tunctionality

**Comment by jamesarosen** [comment]
jamesarosen/ember-i18n has been deprecated in favor of [ember-intl](https://github.com/ember-intl).
