### ISSUE TITLE
Does ember-i18n work in Safari without any extra "Safari specific" configuration?

### ISSUE THREAD

**Issue by aronysidoro** [jamesarosen/ember-i18n#345]
@jamesarosen,

Sorry if this is a noob question.  It is just that I did some Googling, and saw the two comments below about Safari not natively providing international Locales.

I am just seeing **Big Error**, and it's only in Safari, and I have seen this in the past when the **ember-i18n**'s Translation files aren't loaded correctly, so I'm guessing this is why my app isn't working in Safari, and some extra configuration is needed, but not sure.

Here are the two ember-i18n issue comments, where people talked about Safari.  Thank you in advance, and thank you for this great library.

[Issue 38: comment-29644711](https://github.com/jamesarosen/ember-i18n/issues/38#issuecomment-29644711)

[Issue 109: comment-104078173](https://github.com/yahoo/ember-intl/issues/109#issuecomment-104078173)

**Comment by jamesarosen** [comment]
I'm on vacation and won't be back to a computer for a week or so.

But Safari shouldn't pose a problem for v4.x. Ember-I18n doesn't use any of the browser's native I18n support.

**Comment by aronysidoro** [comment]
@jamesarosen, thank you for the quick reply!

Ok, if it's not Safari related, I'm going to go ahead and close the issue.  

Thank you!

**Comment by jamesarosen** [comment]
If you send a stack trace and some more detail about the error, I'll gladly help debug.
