### ISSUE TITLE
String within string?

### ISSUE THREAD

**Issue by si4star** [jamesarosen/ember-i18n#347]
Hi,

I can't seem to see the feature, but would it be possible to do a string within a string for the translations...
```
"appname": "Application Name",
"welcome":"Welcome to {{t "appname"}}."
"copyright:"Copyright 2015. {{t "appname"}}"
```
I appreciate my " aren't correct, but I'm sure you get the point.

Simon

**Comment by kellyselden** [comment]
This is possible, but not like that. The translation files shouldn't have handlebars logic (other than variable lookups), so you need to do it in two steps:

```hbs
{{t "welcome" appname=(t "appname")}}
{{t "copyright" appname=(t "appname")}}
```

```js
"appname": "Application Name",
"welcome": "Welcome to {{appname}}",
"copyright": "Copyright 2015. {{appname}}"
```

**Comment by jamesarosen** [comment]
@kellyselden has the perfect answer. We should add that to https://github.com/jamesarosen/ember-i18n/wiki/Doc:-Translating-Text

**Comment by si4star** [comment]
Great, thanks!

**Comment by kellyselden** [comment]
>We should add that to https://github.com/jamesarosen/ember-i18n/wiki/Doc:-Translating-Text

@jamesarosen added to the bottom
