### ISSUE TITLE
Fetching translations for current locale only

### ISSUE THREAD

**Issue by algodave** [jamesarosen/ember-i18n#348]
My app is going to have a huge number of translations, all being returned from the server (as they need to be available for native mobile apps too). [This wiki page](https://github.com/jamesarosen/ember-i18n/wiki/Example:-Fetching-Translations-Live) provided me a great hint, but I would like to pass the current locale to my API using:

```javascript
this.get('i18n.locale')
```

My plan is to set the default locale in `config/environment.js` as seen on [this wiki page](https://github.com/jamesarosen/ember-i18n/wiki/Doc:-Setting-the-Locale) and then change it based on user settings as they login to my app. After login, I would also invoke my `translationsFetcher` service in order to fetch translations for current user's locale.

Do you see any issue with this plan?

**Comment by jamesarosen** [comment]
Sounds very similar to setups I've seen work well before. If you come across any gotchas or tips, feel free to add them to with wiki or suggest them. Good luck!
