### ISSUE TITLE
Getting subset of a locale

### ISSUE THREAD

**Issue by FredUK** [jamesarosen/ember-i18n#349]
Hi there, is it possible to get from the current locale a particular subset ?

Normally we access single translation strings by doing `this.get('i18n').t('general.calendar.month.may');`

Is there any way of doing `this.get('i18n').t('general.calendar')` and get the whole `calendar` tree and it's sub keys with the translations of the locale?

The reason for this is that I'm using a third party plugin that takes a json object for all it's translation strings and I would like to specify the key `general.calendar` as the root for the plugin's translation strings.

Thanks in advance.

**Comment by kellyselden** [comment]
This sounds like a useful feature.

**Comment by jamesarosen** [comment]
It does sound useful. It also happens to be a bit challenging. The reason is that when you switch to a locale, we walk the whole tree of translations and flatten all the keys down. (This is in part for fast lookup and in part to avoid having to do multiple deep object merges.) The data structure doesn't retain the tree structure that your input files use. Thus, to find `general.calendar`, we'd have to enumerate all translations and find those matching the prefix.

It's also difficult because it would be hard to disambiguate between `t('general.calendar')` being a missing translation and being a request for all nested translations. My first thought is to change it to `t('general.calendar.*')`, but even that could be a valid translation key.

Instead, maybe a separate method: something like `translateByPrefix('general.calendar.')`. It would still take O(n) (n = number of translated keys in the app) to build that tree though.

**Comment by kellyselden** [comment]
I like the idea of a new helper, to not complex the flattening logic in `t()`.

**Comment by jamesarosen** [comment]
The flattening doesn't happen in `t()`; it happens in the `locale` setter.

There's an additional complication. We've stored the translations in a structure like

```js
{
  'foo.bar.baz': 'Baz',
  'foo.bar.quux': 'Quux',
  'foo.bar.deeply.nested.key': 'Deeply nested key',
  'some.other.area': 'Of the app'
}
```

If you ask for `translateByPrefix('foo.bar.')`, then you would get

```js

{
  'foo.bar.baz': 'Baz',
  'foo.bar.quux': 'Quux'
  'foo.bar.deeply.nested.key': 'Deeply nested key'
}
```

It wouldn't bee *too* hard to strip the `foo.bar.` prefix from the keys as we add them to the result, in which case we could do
```js
{
  'baz': 'Baz',
  'quux': 'Quux'
  'deeply.nested.key': 'Deeply nested key'
}
```

But I expect @FredUK would want

```js
{
  baz: 'Baz',
  quux: 'Quux',
  deeply: {
    nested: {
      key: 'Deeply nested key'
    }
  }
}
```

Unfortunately, there's no way for us to know whether the source strings were themselves in tree form or dotted-key form. And they could be a mix! So we'd have to pick one output format. If we output as a tree, it means some expensive parsing of keys.

**Comment by kellyselden** [comment]
Could the new helper reuse some of the original code that flattens, instead of trying to reconstruct from the flattened object? Our docs would have to warn it is an expensive operation, but then it would retain the original nesting.

**Comment by jamesarosen** [comment]
The original files could have inconsistent format and there would be no way to know which to pick for the output. Take the following example:

```js
// locales/en/translations.js
export default {
  common: {
    welcome: 'Hello',
    goodbye: 'Goodbye'
  }
};

// locales/en-gb/translations.js
export default {
  'common.goodbye': 'Cheerio!'
};

// locales/en-us/translations.js
export default {
  common: {
    goodbye: 'See ya'
  }
};
```

What would you expect the result of `translateByPrefix('common.')` to be for `en-us`? What about for `en-gb`?

**Comment by kellyselden** [comment]
Ok. I didn't expect that.

**Comment by kellyselden** [comment]
Or could you put the burden on the app at that point, what comes out of `translateByPrefix` is whatever is in your locales file?

**Comment by jamesarosen** [comment]
But *which* locales file? The most specific? The least specific? The point is that `en-gb` is the merger of `en-gb` and `en`, but they have different structures. That's why we flatten.

**Comment by kellyselden** [comment]
Ah I didn't realize at the time that you were giving me two locales with the same root.

**Comment by jamesarosen** [comment]
I think the only sensible solution is to return the flattened dictionary and leave any parsing up to the client app.

@FredUK would you be able to reconstruct what you need from that?

**Comment by FredUK** [comment]
@jamesarosen , thanks for looking into this. Yes, that would be more than enough. Cheers.

**Comment by FredUK** [comment]
@jamesarosen Hi there, is this something that can easily be implemented and if so are there any plans to implement it? Thanks

**Comment by kellyselden** [comment]
@FredUK If this feature was implemented, It would have some gotchyas where you wouldn't get an exact replica of the original. I think I can speak for @jamesarosen that this is a low priority feature, so it probably won't get implemented for some time. You may be better off trying to implement yourself and submitting a PR or telling us how you got it working. @jamesarosen Feel free to correct me if you feel differently.

**Comment by jamesarosen** [comment]
I'd love to see this as an example in the wiki. If others find it useful, we can also talk about a PR :)

**Comment by FredUK** [comment]
@kellyselden, In my case I wouldn't mind not getting an exact replica of the original as long as I'd be able to access the keys and values either by dot notation or translation[key].
Unfortunately I don't think I'd be able to implement it myself and submit a PR. :)

**Comment by jamesarosen** [comment]
jamesarosen/ember-i18n has been deprecated in favor of [ember-intl](https://github.com/ember-intl).
