### ISSUE TITLE
Are there any plans to upgrade it to EMBER-1.13.12 or 1.13.15?

### ISSUE THREAD

**Issue by shivanibhanwal** [jamesarosen/ember-i18n#350]
Hello

Are you planning to upgrade it to 1.13.12 or latest ember-cli version?
Because as per the [this ember-security issue](https://groups.google.com/forum/#!msg/ember-security/OfyQkoSuppY/lJM-w7kADgAJ) we should upgrade ember. 
So wondering if app has dependency on ember-i18n how we will resolve it if it is still dependent on old version and how it can be secure?

Thanks

**Comment by kellyselden** [comment]
@shivanibhanwal The addon doesn't describe which ember version you are using. Your app's ember version is always used. The version of ember in the addon project is just used for testing.

**Comment by locks** [comment]
Like @kellyselden explains the dependency poses no security issue for your application. Hm, we could still update the dependency.
@shivanibhanwal can you submit a Pull Request?

**Comment by shivanibhanwal** [comment]
@locks sure I will create a pull-request soon.

**Comment by jamesarosen** [comment]
jamesarosen/ember-i18n has been deprecated in favor of [ember-intl](https://github.com/ember-intl).
