### ISSUE TITLE
How to translate a link-to path

### ISSUE THREAD

**Issue by oskarrough** [jamesarosen/ember-i18n#353]
Hi, how would you translate inside a `link-to` helper? I tried the following without success:

```hbs
{{#link-to "dynamic-route" (t "route.fish")}}
  {{t "Fish"}}
{{/link-to}}
```

My locales look like this:

```js
export default {
	'Fish': 'Fish',
	'route.fish': 'fish'
}
```

The dynamic segment ends up undefined. Outside the link-to helper all is good. Any ideas?

**Comment by jamesarosen** [comment]
The `{{t}}` helper returns an instance of `Ember.Handlebars.SafeString`, not a bare String. My _guess_ is that `{{link-to}}` doesn't know how to handle that object. What happens if you do the following?
```hbs
{{#link-to "dynamic-route" (to-string (t "route.fish"))}}
```
and
```js
// app/helpers/to-string.js
export default Ember.Helper.helper(function([ value ]) {
  return '' + value;
});
```

**Comment by oskarrough** [comment]
Oh man, that works! This pretty much made my day. Thank you.

Could the `{{t}}` helper be changed to not require this extra step?

**Comment by jamesarosen** [comment]
> Could the {{t}} helper be changed to not require this extra step?

It could, but it would dramatically reduce the security of the project. That's there for a very specific reason: to make your app secure against XSS attacks by default.
