### ISSUE TITLE
Upgrading from 4.1.1 breaks t-helper lookup in Ember 1.13

### ISSUE THREAD

**Issue by mphasize** [jamesarosen/ember-i18n#355]
Upgrading from 4.1.1 to 4.1.2 or any other higher version including 4.2.0 breaks the lookup of the `t` helper. 

Versions in use:
```
Ember             : 1.13.13
Ember Data        : 1.13.15
jQuery            : 1.11.2
```

Using the Chrome inspector to peek into the ember-cli development build I can see, that the file `myapp/helpers/t.js` exists, but when booting, the application errors with:
`Assertion Failed: A helper named 't' could not be found.`

Any ideas how to circumvent this problem?

**Comment by jamesarosen** [comment]
v4.2.0 is tested against Ember 1.13: https://github.com/jamesarosen/ember-i18n/blob/v4.2.0/.travis.yml#L16

Some hypotheses:

 * `myapp/helpers/t.js` is throwing an exception during *definition*; try setting a debugger in there and walking through it
 * another addon or a file in your app is conflicting with this helper
 * another addon or a file in your app is changing the way the resolver finds modules

What version of Ember-CLI are you using?

**Comment by mphasize** [comment]
Ember-CLI version is 1.13.8 – I will try an update of that soon and also look into the other hypotheses. Will report back as soon as I have some more infos.

**Comment by jamesarosen** [comment]
Here's the [diff from v4.1.1 to v4.1.2](https://github.com/jamesarosen/ember-i18n/compare/v4.1.1...v4.1.2). Highlights:

 * Many files in `addon/` were moved around. I wouldn't expect that to change how your app works unless you were importing things directly from the addon.
 * The instance initializer no longer manually registers `helper:t`; instead, the addon declares an `app/helpers/t.js` that the registry looks up automatically. Unless you've modified how the resolver works, this should continue to work.

Are you using `helper:t` only in templates via `{{t "..."}}`? Or do you import it somewhere in your code, particularly in initialization code?

**Comment by mphasize** [comment]
I don't have any initializers or instance-initializers in my app apart from the ones installed by other addons and I didn't manually modify the resolver. Well, as far as I remember... the app already suffered a refactor from ember-i18n to ember-cli-i18n and back during it's development history, so I have to double-check if there is some legacy code hanging around. ;)

**Comment by mphasize** [comment]
Alright, an update of `ember-cli` ( now 1.13.15 ) solved this issue for me.
