### ISSUE TITLE
added t macro

### ISSUE THREAD

**Issue by kellyselden** [jamesarosen/ember-i18n#356]
I just created [ember-i18n-macros](https://github.com/kellyselden/ember-i18n-macros).

Instead of doing this:

```js
// inside controller or component...
textNeededForOperation: Ember.computed('i18n.locale', function() {
  return this.get('i18n').t('my.translation.key');
})
```

You can do this:
```js
import t from 'ember-i18n-macros/t';

// inside controller or component...
textNeededForOperation: t('my.translation.key')
```
Would you want this in core, added to the wiki, or neither?

**Comment by jamesarosen** [comment]
That's already in core! https://github.com/jamesarosen/ember-i18n/blob/master/tests/unit/utils/macro-test.js

**Comment by kellyselden** [comment]
Damn I missed it!!! Wow it's in the wiki too. Time to stop coding today...
