### ISSUE TITLE
Documentation about acceptance tests should be updated

### ISSUE THREAD

**Issue by nomuna** [jamesarosen/ember-i18n#359]
According to the current documentation ember-i18n should just work fine with acceptance tests.

I could use the test helpers in an acceptance test using the information in the discussion of the pull request #273.

I think the documentation about testing should contain this information.

**Comment by jamesarosen** [comment]
[Done](https://github.com/jamesarosen/ember-i18n/wiki/Doc:-Testing#acceptance-tests)

**Comment by nomuna** [comment]
The added documentation is not complete.
That you have to import the helpers in  tests/helpers/start-app.js is not there.

**Comment by jamesarosen** [comment]
Updated.
