### ISSUE TITLE
Use deep merge in addTranslations to override nested translations

### ISSUE THREAD

**Issue by jandlint** [jamesarosen/ember-i18n#360]
Hello,

The app I am working on allows users to override specific terms on the platform, which I wanted to override the translated term with. However, in I18n's addTranslations method, Ember.merge() only performs a shallow merge.

Would it be helpful to others to replace this with a deep merge for other such situations?

**Comment by jamesarosen** [comment]
Ember-I18n flattens the hashes as it loads. That is, it converts
```js
{
  'foo.bar': 'BAR',
  foo: {
    baz: 'BAZ'
  }
}
```
to
```js
{
  'foo.bar': 'BAR',
  'foo.baz': 'BAZ',
}
```
Perhaps the correct solution would be to flatten, then use a shallow merge. I say that because the following is a valid translations file:
```js
{
  foo: 'FOO',
  'foo.bar': 'BAR'
}
```
but if you try to deep-merge with
```js
{
  foo: {
    bar: 'NEW BAR'
  }
}
```
you'll overwrite `foo: 'FOO'`.

**Comment by jandlint** [comment]
Thank you for the quick response. I had overlooked that the keys were flattened and I am now able to solve my problem by flattening my keys as well.
