### ISSUE TITLE
Uncaught TypeError: Cannot read property 't' of undefined

### ISSUE THREAD

**Issue by kgish** [jamesarosen/ember-i18n#362]
Are there any plans to upgrade `ember-i18n` so that it will work with Ember 2.4.5 or higher?

Since I've upgrade my application, all calls to `this.get('i18n').t(...)` fail, resulting in the error:
```
Uncaught TypeError: Cannot read property 't' of undefined
```

Here are my settings:
```
DEBUG: -------------------------------
DEBUG: Ember             : 2.4.5
DEBUG: Ember Data        : 2.5.2
DEBUG: jQuery            : 2.2.3
DEBUG: Ember Simple Auth : 1.0.0
DEBUG: -------------------------------
```

This is a real show-stopper for me, so if you already have something great, otherwise I'll be happy to try to fix it myself.

**Comment by jamesarosen** [comment]
We certainly want to stay current with Ember. I haven't tried testing against 2.4.5 yet. I don't know what might be causing this. 

### Some thoughts

> `Uncaught TypeError: Cannot read property 't' of undefined`

This tells me that `this.get('i18n')` is `undefined`.

Do you have `i18n: inject.service()` at the top of that file? If not, I'm interested to find out where `this.get('i18n')` came from before Ember 2.4.5.

If you _do_ have it in that class, I'd guess there's some problem with the resolver or container. I do know that `owner` is replacing `application` or `applicationInstance` for the thing we get `container` or `resolver` from. I don't know much more about the details of these changes, so I'm not totally sure where to start debugging.

**Comment by splattne** [comment]
Just as info: I'm using ember-i18n with ** Ember 2.5.0.** No problem with it so far or previous version. (Just the deprecation message in console about `Ember.merge` is deprecated, use `Ember.assign`. But I saw that there's already a patch for this. Would be nice if there was a release for this. :-) Thank you!

**Comment by kgish** [comment]
Yes indeed, by inserting `i18n: inject.service()` in the file, everything works again, thanks!

My question is then: is this to be the standard way of using services from now on?

Seems kind of a pain having to insert this into every single file that wants to use it.

Internationalization is such an ubiquitous need that being able to inject it once and for all into all models and controllers so that it is available across the whole application in one go is a better option.

Is there still some way to achieve this?

**Comment by workmanw** [comment]
I think it's becoming pretty standard. And I personally prefer explicit injections, but you could configure an "auto inject" (I don't know if there is a better name for it) using an initializer. For example:

```javascript
// app/initializers/i18n-inject.js
export default {
  name: 'i18n-injections',
  initialize(application) {
    // Inject i18n service into all components, controllers and models.
    application.inject('component', 'i18n', 'service:i18n');
    application.inject('controller', 'i18n', 'service:i18n');
    application.inject('model', 'i18n', 'service:i18n');
  }
};
```

**Comment by kgish** [comment]
I agree that normally auto inject is not the most elegant, but for i18n which is required across the whole application wherever ext is involved that it's not such a bad idea.

**Comment by kellyselden** [comment]
@kgish You could use the auto injector stated [here](https://github.com/jamesarosen/ember-i18n/wiki/Doc:-i18n-Service#i18n-service)
[ember-i18n-inject](https://github.com/kellyselden/ember-i18n-inject)

**Comment by jamesarosen** [comment]
> Would be nice if there was a release for this.

There will be, but not for a couple weeks as I'm about to head out on vacation. In the meantime, I recommend [ember-cli-deprecation-workflow](https://github.com/mixonic/ember-cli-deprecation-workflow).

**Comment by rphadake** [comment]
I am getting same error while running component integration test.
DEBUG: Ember      : 2.8.1
DEBUG: Ember Data : 2.8.1
jQuery     : 3.1.1

Using ember-18n successfully in my project. Using i18n initializer as below:
export default {
    name: 'i18n',

    after: 'ember-i18n',

    initialize: function (app) {
        app.inject('route', 'i18n', 'service:i18n');
        app.inject('controller', 'i18n', 'service:i18n');
        app.inject('mixin', 'i18n', 'service:i18n');
        app.inject('model', 'i18n', 'service:i18n');
        app.inject('component', 'i18n', 'service:i18n');
    }
};

And in component code using it as 
var localizedLabel =  this.get('i18n').t("units.charts.summary");

Tried to inject i18n as below without success. 
  beforeEach(){
    this.set('i18n', this.container.lookup('service:i18n'));
  }

Any pointers?

**Comment by jamesarosen** [comment]
Can you try getting some more information about `i18n` and `container`?
```js
localizedLabel: Ember.computed('i18n.locale', function() {
  console.log('container', this.container);
  console.log('i18n', this.get('i18n'));
  return this.get('i18n').t("units.charts.summary");
})
```
Does the `container` have a `service:i18n`? What is `i18n` there?

Is there anything special about this component or does it happen on all components?

**Comment by rphadake** [comment]
While running test, the computed property code from component returned following:
console.log('container', this.container);  // valid container ref
console.log('i18n', this.get('i18n'));  //undefined.

I removed beforeEach() from my test and changed computed prop code as below.
    var i18n =  Ember.getOwner(this).lookup('service:i18n');
   var localizedLabel =  i18n.t("units.charts.summary");

Now tests are also passing for this component. The code works fine for all components only tests were problem but now its resolved.

Thanks.

**Comment by jamesarosen** [comment]
Component integration tests don't run initiializers. For that reason, I recommend `Ember.inject.service()` instead of an initializer with injections.
