### ISSUE TITLE
Ember.Handlebars.SafeString depreciation thrown with latest ember version.

### ISSUE THREAD

**Issue by nullrocket** [jamesarosen/ember-i18n#364]
There is a reference in  compile-template.js throwing a depreciation warning in the latest ember beta.

```
//addon/utils/i18n/compile-template.js
...
const SafeString = Ember.Handlebars.SafeString;
...
```

Easy enough to switch to Ember.String.htmlSafe but I'm not sure what that does to the tests

```
//tests/unit/utils/i18n/default-compiler-test.js
...
  assert.ok(result instanceof Ember.Handlebars.SafeString);
...
```

**Comment by nullrocket** [comment]
Just now noticed PR #363 missed it somehow.

**Comment by jamesarosen** [comment]
Can you check with the core team about how we should assert that something is a safe-string?

**Comment by jamesarosen** [comment]
@rwjblue [suggests](https://github.com/emberjs/ember.js/issues/13318#issuecomment-209599955)

```js
moduleForComponent('asdf', { integration: true });

test('renders html', function(assert) {
  this.render(hbs`{{some-helper}}`);

  assert.equal(this.$('.some-selector-for-html-values-from-helper').length, 1, 'found html from helper');
});
```

The problem is that we don't have a component in the Ember-I18n test suite to test. We could create a synthetic one in the dummy app and then test it:

```js
moduleForComponent('dummy-component', 't helper', { integration: true });

test('t escapes HTML', function(assert) {
  this.render(hbs`{{t ...}}`);

  ...
});
```

That's a bit of an awkward workaround, but it very well might work.

**Comment by workmanw** [comment]
The plan is to undeprecate `Ember.Handlebars.SafeString` for now and long term to add `Ember.String.isHtmlSafe()`.

Related: https://github.com/emberjs/ember.js/issues/13318 and https://github.com/emberjs/rfcs/pull/139

**Comment by rwjblue** [comment]
@jamesarosen - No component is needed for that snippet. Just a helper, that you invoke from within this.render.

**Comment by jamesarosen** [comment]
How would I get `this.render` without `moduleForComponent`?

**Comment by workmanw** [comment]
I also created a polyfill for the RFC which seeks to add `isHtmlSafe`. This whole discussion is only like 8 hours old, so I completely understand if you want to let that thing run it's course first. But it would also be an easy option and require little change on the ember-i18n side. [ember-string-ishtmlsafe-polyfill](https://github.com/workmanw/ember-string-ishtmlsafe-polyfill).

**Comment by rwjblue** [comment]
@jamesarosen - See https://github.com/aptible/dashboard.aptible.com/blob/master/tests/integration/helpers/eq-test.js.  `moduleForComponent` is a bad name. It has nothing to do with components, it just renders the template snippet you provide.

**Comment by jamesarosen** [comment]
jamesarosen/ember-i18n has been deprecated in favor of [ember-intl](https://github.com/ember-intl).
