### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by williamsbdev** [jamesarosen/ember-i18n#366]
I am noticing that there is some code in master that has not been released yet. I am upgrading my app and am noticing the deprecations for Ember.merge which has been fixed in master. Will there be a new release soon so that I can take advantage of the deprecation fix?

Thanks for this great project!

**Comment by workmanw** [comment]
@williamsbdev `Ember.merge` was actually "undeprecated" in Ember 2.5.1 ([CHANGELOG.md](https://github.com/emberjs/ember.js/blob/v2.5.1/CHANGELOG.md#251-april-21-2016)). So for the short term you could probably just upgrade to that.

**Comment by williamsbdev** [comment]
@workmanw - interesting. Thank you for that advice! Is that eventually going to be deprecated/removed? Should we continue to move forward with `Ember.assign` instead of `Ember.merge`?

**Comment by workmanw** [comment]
@williamsbdev I'm not totally sure. I asked that here: https://github.com/emberjs/ember.js/pull/13344#issuecomment-211074119. In our app, we went ahead and converted to `Ember.assign`.

**Comment by williamsbdev** [comment]
@workmanw Thank you for the link to that thread! I'll keep an eye on it.

**Comment by jamesarosen** [comment]
v4.2.1 was just released.
