### ISSUE TITLE
[Doc] Unit testing: needs: ['locale/xy:config'] throws

### ISSUE THREAD

**Issue by jelhan** [jamesarosen/ember-i18n#368]
Following [Docs for unit testing](https://github.com/jamesarosen/ember-i18n/wiki/Doc:-Testing#unit-tests) `local/xy:config` should be part of `needs` array to setup for unit tests. But if it's added tests throws:

> Promise rejected before validation for make a poll: Attempting to register an unknown factory: `locale:en/config`

Everything works fine if `locale:en/config` is not part of `needs` array.

It might be an issue with my outdated stack:

```
ember: 1.13.13
ember-cli-test-loader: 0.2.1
ember-i18n: 4.1.4
```

**Comment by jamesarosen** [comment]
Do your tests work without that module in the `needs` block?

**Comment by jelhan** [comment]
Yes. Everything is fine if `locale:xy/config` is not part of `needs` block.

**Comment by jamesarosen** [comment]
I'd like to try to figure out why this is different in your environment. But I'm happy to have the docs suggest that it may not be needed / allowed.

**Comment by LucasHillDex** [comment]
I am also able to reproduce this in ember 2.6

**Comment by alvincrespo** [comment]
I'm running into this issue right now. 

**Error**

```
‣TypeError: Attempting to register an unknown factory: `locale:en/config`
    at Registry.register (http://localhost:7357/assets/vendor.js:11358:15)
    at Klass._setupIsolatedContainer (http://localhost:7357/assets/test-support.js:15525:29)
    at Klass.setupContainer (http://localhost:7357/assets/test-support.js:15360:14)
    at http://localhost:7357/assets/test-support.js:14412:26
    at Object.initializePromise (http://localhost:7357/assets/vendor.js:62544:7)
    at new Promise (http://localhost:7357/assets/vendor.js:64394:21)
    at nextStep (http://localhost:7357/assets/test-support.js:14411:18)
    at Klass.invokeSteps (http://localhost:7357/assets/test-support.js:14418:14)
    at Klass.setup (http://localhost:7357/assets/test-support.js:14368:19)
    at Context.<anonymous> (http://localhost:7357/assets/test-support.js:14202:23)
```

**Test Setup**

```
describeModule(
  'service:days',
  'DaysService',
  {
    needs: [
      'service:i18n',
      'locale:en/translations',
      'locale:en/config',
      'util:i18n/missing-message',
      'util:i18n/compile-template',
      'config:environment'
    ],
    beforeEach() {
      this.container.lookup('service:i18n').set('locale', 'en');
      this.registry.register('locale:en/config', localeConfig);
      this.registry.register('helper:t', tHelper);
    }
  },
```

**Environment**

```
version: 2.3.0
node: 5.3.0
os: darwin x64
```

```
    "ember-i18n": "4.4.0",
```

Based on the docs for 4.4.0 and the latest, not much has changed in terms of set up for unit testing. Not sure what the issue might be.

**Comment by crusy** [comment]
Same here: With `'locale:en/config'` I get an `Attempting to register an unknown factory`, but without I get some JSON instead of a translated String. ember-cli:2.13.1, ember-i18n:^5.0.1

**Comment by damien-mcmahon** [comment]
I was having the same issue and removing `locale:en/config` from the `needs` array fixes things for me running `ember-cli:2.12.1` with `ember-i18n: 5.0.1`

**Comment by mehulkar** [comment]
Removing the `locale:en/translations` and `locale:en/config` from the `needs` array made this work for me also. Using ember 2.13.4, ember-i18n 5.0.2

**Comment by jamesarosen** [comment]
jamesarosen/ember-i18n has been deprecated in favor of [ember-intl](https://github.com/ember-intl).

**Comment by bbansalWolfPack** [comment]
removing the two things does not help as in the model file where I use Ember.i18n, it fails saying that t is not defined. Any comments on this?
