### ISSUE TITLE
Introduction to ember-i18n on The Ember Show at Global Ember Meetup

### ISSUE THREAD

**Issue by taras** [jamesarosen/ember-i18n#369]
Would you someone familiar with this library be interested in giving a lightning talk about this addon on The Ember Show? We're recording the next episode on June 11th followed by July 2nd. 

An introduction to <addon> talk is about 15 minutes long and covers the following:
- Why was this addon created?
- When should it be used?
- How does one get started?
- What should the person be aware of?

You can see some of the previously recorded introduction talks on [Global Ember Meetup Videos](https://www.embermeetup.com/videos?category=addon-introductions) page.

Would you be able to give this talk?

**Comment by jamesarosen** [comment]
June 11th is no good for me, but I might be able to do July 2nd. I'll send contact info.

**Comment by taras** [comment]
@jamesarosen we're going to move July 2nd event to July 9th because of holiday conflicts. Does this still work for you?

**Comment by jamesarosen** [comment]
jamesarosen/ember-i18n has been deprecated in favor of [ember-intl](https://github.com/ember-intl).
