### ISSUE TITLE
locales in addon

### ISSUE THREAD

**Issue by jakope** [jamesarosen/ember-i18n#370]
Hey,
i wanna use my translations in multiple apps, so i made an addon only for the locales directory, but at the main project i can't acces it. 

folder structure
addon
 locales
  de
   config.js  // real file 
   translations.js // real file with translations
  en
   config.js
   translations.js
app
 locales
  de
   config.js // export { default } from 'addon-name/locales/de/config';
   translations.js  // export { default } from 'addon-name/locales/de/translations';
  en
   config.js
   translations.js

Any suggestions?

Thank You!

**Comment by jamesarosen** [comment]
See #255
