### ISSUE TITLE
Uncaught Error: Could not find module ember-metal/streams/stream

### ISSUE THREAD

**Issue by nickbrit** [jamesarosen/ember-i18n#371]
I'm trying to install `ember-i18n`. But I get this error

I use `ember install:addon ember-i18n`.

`Uncaught Error: Could not find module ember-metal/streams/stream`.

Ember 1.8.1, Ember CLI 0.1.12

**Comment by jamesarosen** [comment]
Please see the [installation guide](https://github.com/jamesarosen/ember-i18n/wiki/Doc:-Installation) for supported versions of Ember.

**Comment by Voles** [comment]
I was able to resolve this issue by updating from v4.2.1 to v4.3.2.
