### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by SamiSammour** [jamesarosen/ember-i18n#375]
Hi there, 
I there anywhere in my Ember application I can know what is the value of `rtl` for the current `i18n.locale`?
I tried `this.get('i18n.locale.rtl')` but I got `undefined`.
I am running a version 4.1.1

**Comment by jamesarosen** [comment]
No, I don't think there is. The `service:i18n` doesn't expose the locale's config information anywhere. That seems like a good thing to do.

**Comment by acorncom** [comment]
I'd be quite interested in seeing this as well ...

**Comment by LinKassem** [comment]
Any updates on this issue?

**Comment by jamesarosen** [comment]
jamesarosen/ember-i18n has been deprecated in favor of [ember-intl](https://github.com/ember-intl).
