### ISSUE TITLE
With ember-beta (2.7) the streams import has changed

### ISSUE THREAD

**Issue by workmanw** [jamesarosen/ember-i18n#376]
I get this error when testing with ember-beta:

> vendor.js:9573 Uncaught Error: Could not find module ember-metal/streams/stream

It seems that the import should now be `ember-metal/streams/stream/index`. I'll submit a PR and try to maintain backwards compat.

**Comment by workmanw** [comment]
Oh actually it looks like @Cryrivers already fixed this in 74f9cb5ebd73d84d7e5f6ae0564171cc7f471ea8. 

@jamesarosen What do you think about a patch release since this is now an issue with ember-beta? I'd be happy a PR for the changelog and package.json if that's helpful.

**Comment by jamesarosen** [comment]
I'll do a 4.2.2 release in a few minutes. It's unfortunate that the `import`s happen before we can check whether `Ember.Helper` exists. If we could check that first, we wouldn't ever have to import `Stream` at all.

**Comment by jamesarosen** [comment]
Closed by e12fcda0641368737e2370409a2a702a9ef2322e

**Comment by workmanw** [comment]
@jamesarosen Thanks!
