### ISSUE TITLE
RFC: allow more htmlSafety control

### ISSUE THREAD

**Issue by jamesarosen** [jamesarosen/ember-i18n#377]
Currently (in v4.x), ember-i18n supports the following translation:

``` js
hello: "Hello, <em>{{name}}</em>"
```

If you use this in Handlebars:

``` hbs
{{t "hello" name=user.name}}
```

or in JavaScript:

``` js
hello: Ember.computed('i18n.locale', function() {
  return this.get('i18n').t('hello', { name: this.get('user.name') });
})
```

the result is the same: ember-i18n runs `escapeExpression` on `user.name`, then wraps the whole translation in `htmlSafe`. The first operation prevents XSS attacks. The second prevents overescaped strings -- users seeing _Hello, <em>Vijay</em>_ on the page.

Several people have submitted various issues regarding this escaping-and-safety logic: #280, #374. I believe the best approach to solve this is as follows:

In v4.x, allow calls to `i18n.t` to ask for the `htmlSafe` call to be omitted on a case-by-case basis:

``` js
const i18n = this.get('i18n');
const hello = i18n.t('hello', { name: this.get('user.name'), __htmlSafe: false });
// hello is a plain string, though `user.name` is still escaped
```

Also in v4.x, add a mechanism for users to turn off these `htmlSafe` calls in JavaScript-land globally:

``` js
initialize(application) {
  application.lookup('service:i18n').set('tMarksSafe', false);
}
```

By default, `tMarksSafe` is `undefined`, which is functionally equivalent to `true`, but prints a deprecation warning. Valid overrides are `true` and `false`.

Also in v4.x, add an _escape hatch_ at the helper level in case application developers want plain strings there -- for example, when composing helpers:

``` hbs
{{capitalize (t 'hello' name=user.name __htmlSafe=false)}}
```

In v5.x, remove support for `i18n.Options.htmlSafe` and `tMarksSafe`. All JavaScript-land calls will _not_ mark the string as safe. Helper invocations will wrap in `htmlSafe` by default, but still support `__htmlSafe=false` for composing.

**Comment by jamesarosen** [comment]
@abfx @rainerfrey @workmanw @cfator @gossi I'd love your thoughts on this.

**Comment by workmanw** [comment]
I think we run into this case: `hello: "Hello, <em>{{name}}</em>"` pretty often. Clearly `{{name}}` chars should be escaped and the translation should not be escaped. But we also have this other case we want to be careful because we have `&`, `<`, and `>` as translation values (not interpolated values). In these cases, we want the entire translation to be escaped.

What ends up happening is that the consumer of that specific translation has to know if it contains HTML or not.

I think in a perfect world, you might allow this to be signaled from the `translations.js` file itself. For example:

```javascript
export default {
  hello: { t:  "Hello, <em>{{name}}</em>", htmlSafe: true },
  goodbye: "Thanks & have a nice day."
}
```

This also has the added advantage if you want to change the translation value for `goodbye` to have an `<em>` you wouldn't need to find all of the consumers and update them. 

I don't think this and the above proposal are mutually exclusive.

**Comment by jamesarosen** [comment]
Or maybe
```js
import html from 'ember-i18n/has-markup';

export default {
  hello: html`Hello, <em>{{name}}</em>`,
  goodbye: 'Thanks & have a nice day.'
};
```

**Comment by workmanw** [comment]
@jamesarosen Actually yes!!! That would be really awesome.

**Comment by jamesarosen** [comment]
There have also been some discussions about how to best ask for a translation in a particular locale. It may be wise to reuse the process for `htmlSafe`.

In v4.x, we would introduce two new configuration settings:
```js
// config/environment.js:

ENV.i18n = {
  defaultLocale: 'en-gb',
  reservedHtmlSafeKeyword: true,
  reservedLocaleKeyword: true
}
```

`service:i18n.tMarksSafe` reads its default value from `reservedHtmlSafeKeyword` and `service:18n.canOverrideLocale` reads its default value from `reservedLocaleKeyword`. In both cases, if the value is `undefined`, we print a deprecation warning and treat it as `false`. Then, in looking up the translation, we use `locale` iff `canOverrideLocale` is `true`.

**Comment by workmanw** [comment]
Hey @jamesarosen et al -- We've been adding a lot more markup to our translations and find that we're doing `__htmlSafe=true` more and more. I wonder what your thought are on implementing the `hasMarkup` decorator we talked about last June.

I'd be happy to investigate and submit a PR it seems like the right direction.

**Comment by jamesarosen** [comment]
I think the decorator is the best approach we've been able to come up with. One tricky bit will be keeping the compiler backwards compatible while supporting the decorated strings.

### My first idea:

 1. have a flag like `ENV.i18n.translationsSafeByDefault = true`, with `true` being the default value (mimicking current behavior)
 1. add `html` marker

Then the compiler would look something like

```js
if (isHTMLSafe(translation) || translationsSafeByDefault) {
  // escape interpolations
  // insert interpolations
  // return safe string
} else {
  // insert interpolations
  // return whole, unsafe string
}
```

To turn this feature on, you would set `translationsSafeByDefault = false` and use the `htmlSafe...` marker in your translations file.

### My Second Idea

I don't love that the translation compiler knows about the configuration parameter. I'd rather the translation compiler receive a string that is either marked HTML-Safe or not. The Locale could mark strings as HTML-safe when it looks them up (right before compiling). Thus:

```js
getCompiledTemplate(fallbackChain, count) {
  let translation = this.findTranslation(fallbackChain, count);
  let result = translation.result;

  if (this.translationsSafeByDefault && typeOf(result) === 'string') {
    result = this._compileTemplate(translation.key, htmlSafe(result));
  } else if (isHTMLSafe(result)) {
    result = this._compileTemplate(translation.key, result);
  }

  ...
}

### My Third Idea

For v5.x, I want to move translation compilation to _build-time_, just like Ember did with Handlebars compilation. We might want to offer a runtime compiler for people who want to load raw translations from an API and compile them on-the-fly. Perhaps this feature is the right time to start moving towards precompiled translations. That is, precompiled translations would _always_ have `translationsSafeByDefault = false` and require use of the `html` marker to get current behavior.

### My Fourth Idea

Use ember-intl, which has a distinction between `{{t}}` and `{{t-html}}`. This means the _template_ needs to know whether the translation has HTML, rather than storing that information in the translation.

@jasonmit do you think there would be a way to declare HTML-safety at the translation level in ember-intl?

**Comment by jasonmit** [comment]
@jamesrosen with some work declaring this metadata closer to the translations would be possible.

However, my worry with that is most projects I've worked in delegate translations to a third-party which may not have the ability to export translations with such metadata.

**Comment by sankar-ganesh** [comment]
Any plans to get this out really??? How can we use html tags inside content definitions. We also might have to consider the use case where adding anchor text and url will be dynamic when the anchor lives in the translation to support non-fragment translation

Example:
=======
To continue "click here"

will become something like this in other translations 

"click here" to continue

**Comment by jamesarosen** [comment]
jamesarosen/ember-i18n has been deprecated in favor of [ember-intl](https://github.com/ember-intl).
