### ISSUE TITLE
i18n.exists returns true for missing strings under certain conditions

### ISSUE THREAD

**Issue by jamespenick** [jamesarosen/ember-i18n#380]
I'm seeing an issue where the exists routine returns true for a missing string. I'm using version 4.2.0 of the library. 

Here's how to reproduce the issue:

const i18n = this.get('i18n');
i18n.exists('nonExistentString');  // returns false as expected
i18n.t('nonExistentString');  // returns 'Missing translation: nonExistentString' as expected
i18n.exists('nonExistentString');  // returns true??

**Comment by jamesarosen** [comment]
Fascinating. This is a regression. I remember fixing it a long time ago. It's true that the logic for falling back to "Missing translation: nonExistingString" does insert a translation into the locale dictionary, but it _used to_ mark that as a "missing translation."

This should be pretty straightforward to fix. Any takers?

**Comment by borissuska** [comment]
I improved missing translation message for pluralForms and I fixed this too. I fixed it in one version of implementation which was not used in final commit, then I added this fix separately including test. The fix is included in Non deterministic behavior ... PR.

**Comment by jamesarosen** [comment]
Resolved by #390
