### ISSUE TITLE
Suggestions: Arrays, Aliases and Subsets

### ISSUE THREAD

**Issue by FredUK** [jamesarosen/ember-i18n#382]
Hi,
The app I'm working on was using a translation plugin (https://github.com/mirego/ember-cli-foreigner) before I migrated to the awesome ember-i18n. Although I do miss some functionalities of foreigner which could be nice additions to ember-i18n..
- String values as arrays

This allowed us to query just for t('general.weekdays') and get an array of strings which we would then be able to iterate over either in a component or handlebars template.

```
general: { 
   weekdays: ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']
}
```

---
- Translation aliases

Any translated string which would start with a "!" would actually just be an alias for the real translate key.
In the example below, this allows us to keep the translation strings for a component isolated but without the need to repeat yourself (copy paste) and still keeping the namespace of the translation correct.

```
general: { 
   weekdays: ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']
   components: {
      date_picker: {
         weekdays: '!general.weekdays'
      }
   }
}
```

---
- Get child translations of key

I already mentioned this in another issue #349 but it would be nice to be able to get all the child translations for a given key.

```
subjects: {
   math: 'Math',
   physics: 'Physics',
   geography: 'Geography',
   english: 'English
}
```

By calling `this.get('i18n').t('subjects')` we could then be able to iterate trough all the subjects and even do useful things such as generate dropdowns:

```
// Js
subjectOptions: Object.keys(this.get('i18n').t('subjects')).map...

// Or similar in handlebars
<select>
{{#each (t 'subjects') as |subject|}}
  <option>....</option>
{{/each}}
</select>
```

The old plugin would actually expose the whole translation json object. so we could just call translations.key and get all the translations below it.

These are not requests or demands, just features  which I found useful while using the other plugin. Perhaps if there is a lot of interest there could be a chance they get implemented. I might try and do a fork but I'm afraid I might not be able to do it :+1:

**Comment by jamesarosen** [comment]
Prior to v4.0, it was possible to do
```js
someArray: [ 'foo', 'bar', 'baz' ],
someObject: [ foo: 'bar' ]
```
`i18n.t('someArray')` would return `[ 'foo', 'bar', 'baz' ]`.

See https://github.com/jamesarosen/ember-i18n/blob/v3.1.1/lib/i18n.js#L23-L32

We lost that in v4.0. See https://github.com/jamesarosen/ember-i18n/blob/master/addon/utils/locale.js#L46-L61.

It shouldn't be too hard to get object-literal support back. You wouldn't be able to compile a template for those, though, which means they can't have interpolations.

**Comment by jamesarosen** [comment]
jamesarosen/ember-i18n has been deprecated in favor of [ember-intl](https://github.com/ember-intl).
