### ISSUE TITLE
pluralized translations fail when count is undefined

### ISSUE THREAD

**Issue by jamesarosen** [jamesarosen/ember-i18n#383]
Given translations

``` js
catCount: {
  one: 'One cat',
  other: '{{count}} cats'
}
```

and this template:

``` hbs
{{t 'catCount', count=numberOfCats}}
```

if `numberOfCats` is 0 or 1 or 1214212342, it works. If it's `undefined`, it shows `missing translation: catCount`. I believe the problem is that the translator only looks for `catCount.one` or `catCount.other` if `count` is _present_, rather than if the _key is passed_.

**Comment by alexmiddeleer** [comment]
Would this cause "missing translation" to appear while a page is loading? Is there an elegant workaround for this that you would recommend? Thanks :)

**Comment by lcpriest** [comment]
I have a default-to helper that I use for this:
```
import Ember from 'ember';
function defined(value) {
  return value !== null && value !== undefined && value !== "";
}

export function defaultTo([value, value1, value2]) {
  if (defined(value)) {
    return value;
  } else if (defined(value1)) {
    return value1;
  } else {
    return value2;
  }
}

export default Ember.Helper.helper(defaultTo);
```

`{{t 'csvs.columns.map' count=(default-to columns.length 0)}}`

**Comment by jamesarosen** [comment]
jamesarosen/ember-i18n has been deprecated in favor of [ember-intl](https://github.com/ember-intl).
