### ISSUE TITLE
Does not load under ember js 2.7

### ISSUE THREAD

**Issue by ffaubry** [jamesarosen/ember-i18n#385]
This addon uses private modules previously defined under ember-metal/streams. In ember 2.7, these modules have moved under ember-htmlbars/streams.
See: https://github.com/emberjs/ember.js/issues/13917

I was using the official release 4.2.1. I pulled the master 4.2.2 and the installs made in the addon/stream.js fixed the issue.

This issue is to request the 4.2.2 to be the the latest official release.

Thx for the amazing job!

**Comment by jamesarosen** [comment]
https://www.npmjs.com/package/ember-i18n shows 4.2.2 as the latest release

**Comment by ffaubry** [comment]
@jamesarosen Correct the latest release is 4.2.2. The official green label is still on 4.2.1.
I usually follow the green label...
![image](https://cloud.githubusercontent.com/assets/3506166/17275286/6ffb1584-5702-11e6-8e41-2540129f9e5e.png)
