### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by kanongil** [jamesarosen/ember-i18n#388]
My Ember 2.7 project spews out 2 deprecation warning whenever the `service.t()` method is used.

The warnings comes from https://github.com/jamesarosen/ember-i18n/commit/a7bcf7c5fc9f9614c39420df0d2a65e0ebb3c0be, which issues deprecations that should probably have been asserts.

**Comment by jamesarosen** [comment]
> deprecations that should probably have been asserts

For semver reasons, they can't be asserts until we go to v5.0. Are you passing a `locale` or `htmlSafe` option to the `t` calls?

**Comment by jamesarosen** [comment]
Those deprecations now announce an `until`. Try upgrading to v4.3.2. Do you still get erroneous deprecation warnings?

**Comment by kanongil** [comment]
Everything seems fine now.
