### ISSUE TITLE
Extracting strings from source code to translations.js

### ISSUE THREAD

**Issue by omarkohl** [jamesarosen/ember-i18n#389]
Any thoughts or tools on how to automatically (e.g. as part of the build process) extract the strings for translation from the source code? By that I mean all calls to the t() function in routes, controllers, components etc. and all calls to the {{t}} helper in Handlebars templates.

This would be helpful to:
- Ensure no strings stay untranslated
- Ensure strings that no longer appear in the source code get removed (or moved to an alternate file)

Optionally it would be helpful to store additional information in translations.js where each string appears in the sources (file name, line number). This kind of information is useful for translators to check the context where the string was used.

**gettext** and the whole _family_ of tools to manipulate .po files do this.

Two projects exist to do this with _i18next_ (another i18n library for JavaScript), namely https://github.com/i18next/i18next-parser and https://github.com/i18next/i18next-scanner

**Comment by jamesarosen** [comment]
I believe @ebryn or @rwjblue was looking into some sort of linter to ensure that templates don't include untranslated literals. I haven't heard of any such efforts for JavaScript-land. I'm intrigued for sure!

**Comment by rwjblue** [comment]
Ya, ember-template-lint includes a rule (`bare-strings`) that would prevent usage of untranslated strings in a template.

**Comment by mydea** [comment]
Fyi, [ember-l10n](https://github.com/Cropster/ember-l10n) has some code to extract translations from your project - it is based on gettext, though. Extraction works really well there.

**Comment by jamesarosen** [comment]
jamesarosen/ember-i18n has been deprecated in favor of [ember-intl](https://github.com/ember-intl).
