### ISSUE TITLE
Translations fail to load if region subtag is capitalized

### ISSUE THREAD

**Issue by elidupuis** [jamesarosen/ember-i18n#394]
Just came across an issue where we had `app/locales/zh-CN/translations.js` and all strings failed to load. When I updated the locale directory to be lowercase `app/locales/zh-cn/translations.js`, everything worked fine.

Thoughts?

**Comment by jamesarosen** [comment]
It's because ember-cli downcases all module names. The issue has come up numerous times. The only solution I can come up with is a custom Broccoli filter in the app, which I'm open to, but not looking forward to writing.

**Comment by elidupuis** [comment]
I see. Maybe just a little note in the docs/wiki is good enough for now? Might save someone a bit of time and frustration in the future!

It's a little strange I suppose since IETF states *usually written in upper case*,  but that implies that lower case is not incorrect.

**Comment by elidupuis** [comment]
Went ahead and added a note to the Defining Translations page in the wiki: https://github.com/jamesarosen/ember-i18n/wiki/Doc:-Defining-Translations#location-fallback

**Comment by jamesarosen** [comment]
Excellent. I was just looking at the wiki to see if it was there 😀

For v5.0, I'm considering moving more things to build-time, which will require some custom Broccoli work. I'll investigate solving this as well.

**Comment by elidupuis** [comment]
Awesome, thanks!
