### ISSUE TITLE
ember-i18n does not work

### ISSUE THREAD

**Issue by wayneiny** [jamesarosen/ember-i18n#398]
Hi, thanks for all the hard work!

I am using Ember2.5.1, Ember cli 2.5.1 and I installed ember-i18n at v4.2.0

I use ember g locale en to create a locale and defined a translation in it.
Also I defined i18n: { defaultLocale: 'en' }, in config/environment.js in ENV and APP.

But when I tried to inject the service in component, it is always undefined and use {{t "something"}} in template, it gave error like A helper named 't' could not be found.

Thanks in advance.

**Comment by jamesarosen** [comment]
That's definitely surprising! It sounds like Ember-CLI isn't putting ember-i18n into the build for some reason. When you open up the generated `vendor.js`, do you see any of the ember-i18n code? If so, can you set a breakpoint on [this line](https://github.com/jamesarosen/ember-i18n/blob/master/app/instance-initializers/ember-i18n.js#L10) in the browser and tell me whether it gets hit during boot? What about [this line](https://github.com/jamesarosen/ember-i18n/blob/master/app/initializers/ember-i18n.js#L7)?

**Comment by jamesarosen** [comment]
If you're still having trouble, please reopen with additional information about what code is in your `vendor.js` and `app.js`.
