### ISSUE TITLE
Stream not available in 2.7.0  (v4.3.0)

### ISSUE THREAD

**Issue by luqman** [jamesarosen/ember-i18n#401]
I was just upgrading a private add-on to 2.7.0 and found this broke it due to legacy files coming in (stream).

`https://github.com/jamesarosen/ember-i18n/blob/master/index.js#L10`

`config(){...}` appears to be called multiple times when I run `ember s`, sometimes 
`this.hasEmberHelper` is `undefined` other times its `true`.

moving it to `init(){...}` fixes it.

I'm not too familiar with add-on callbacks yet, any ideas why `init` works but not `config`?

**Comment by jamesarosen** [comment]
No clue. Happy to move it to `init` if that's the right thing to do. Maybe @stefanpenner or @rwjblue could comment on the hooks?

**Comment by lordkada** [comment]
I'm hitting the same problem...
I just can say that the "config(){}" is never executed (`this.hasEmberHelper` is undefined and legacy files are not excluded).
