### ISSUE TITLE
Removal of ember-i18n initializer

### ISSUE THREAD

**Issue by swquinn** [jamesarosen/ember-i18n#403]
I didn't see anything in the changelog that reflected the removal of the `ember-i18n` initializer (or, rather the rename of the initializer to `ember-i18n-legacy-helper`. I found this only after my own initializer that referenced the `ember-i18n` initializer began failing with the error:

> **Assertion Failed:** No application initializer named 'ember-i18n'

The previous instance initializer would set up things, like an observer on `locale` and also register the `t` helper. I would imagine that the removal of the instance initializers means they are no longer necessary, should applications upgrading to 4.3.0 of ember-i18n be aware of any side effects that might be encountered when not using these instance initializers?

**Comment by franzliedke** [comment]
Indeed, this also broke our app. :(

**Comment by rwjblue** [comment]
Hmm.  Can you explain how it broke things? Are you referencing `ember-i18n` in another initializer or something?

**Comment by franzliedke** [comment]
Yes, exactly. I am injecting the `i18n` service into components etc. in an initializer that runs `after` ember-i18n.

That's a BC break, I guess. ;)

**Comment by rwjblue** [comment]
FWIW, the initializer was removed because it isn't needed any longer (it is still used on Ember 1.12 IIRC).  I *guess* we could add it back as a noop to prevent app breakage (along with a note in the CHANGELOG to let folks know not to use it any more), but it seems somewhat odd to need to depend on the ordering here.

**Comment by franzliedke** [comment]
Well, it's in your docs: https://github.com/jamesarosen/ember-i18n/wiki/Doc:-i18n-Service

**Comment by swquinn** [comment]
As @franzliedke mentioned, I also had an `i18n` initializer for the service that "depended" on `ember-i18n`. Admittedly the dependency seems to have been superfluous. I believe I came across documentation (either here or elsewhere) that recommended referencing the `ember-i18n` initializer in the initializer's `after` property.

With that having been said, removing the reference to `ember-i18n` solves the issue and doesn't appear to have any side effects (not that I have seen yet) so for my purposes a note in the change log would be enough to alert developers using the add on.

**Comment by franzliedke** [comment]
...plus a new no-op service to keep backwards compatibility.

**Comment by jamesarosen** [comment]
Easy to add a no-op one for backwards compatibility. I'm for that.

**Comment by hinti** [comment]
After upgrading to 4.3 my integration tests are failing, because they are importing the initializer.
The docs still mention the initializer approach: https://github.com/jamesarosen/ember-i18n/wiki/Doc:-Testing

**Comment by rwjblue** [comment]
Yep, as mentioned, I think a PR would absolutely be welcomed.

**Comment by swquinn** [comment]
@rwjblue I've opened a PR to add a no-op `ember-i18n` initializer back in, and run a rudimentary integration test with an application I'm developing which just adds the `after: 'ember-i18n'` line back into my service initializer. Everything seems to work. I wasn't sure if there was a better way to test this (or more formally test this) as I'm still pretty new to the Ember.js ecosystem and haven't really spent too much time in the testing facilities that Ember.js uses.

The PR is here: https://github.com/jamesarosen/ember-i18n/pull/404

**Comment by jamesarosen** [comment]
Should be resolved in 4.3.1
