### ISSUE TITLE
owner._lookupFactory is not a function

### ISSUE THREAD

**Issue by balinterdi** [jamesarosen/ember-i18n#407]
In the latest version, 4.3.1 (although 4.3.2 seems to be released here, it's not yet available as an npm package), I get the following error from one of my tests:

> TypeError: owner._lookupFactory is not a function

I tracked it down to [this line](https://github.com/jamesarosen/ember-i18n/blob/v4.3.1/addon/utils/locale.js#L118) in the `getFlattenedTranslations` function.

I'm using Ember CLI and Ember 2.8.0 and it seems that the container no longer has a `_lookupFactory` method. I tried changing to to `owner.lookupFactory` but then other tests were failing with the same error message.

Could you recommend what I'm doing wrong? Thank you.

**Comment by rwjblue** [comment]
`container` and `owner` are different things (generally speaking), and the container has `lookupFactory` but the `owner` instance has `_lookupFactory`.  The introduction of the owner concept was the first time this was made public API (with the exception of `_lookupFactory` which is being addressed in an open RFC). 

It seems we are creating the `Locale` instance with the result of `getOwner(this)` [here](https://github.com/jamesarosen/ember-i18n/blob/c21e5983d2c0c333d077986f1f23951a142fbedb/addon/services/i18n.js#L98) and that object should definitely have a `_lookupFactory` method on it.  When you get the error, is the `Locale` being instantiated differently?

**Comment by balinterdi** [comment]
Thank you, @rwjblue, indeed that was the source of my agony.

Here is what the test looked like when it was failing:

```js
import Ember from 'ember';
import LocaleHelper from 'ember-i18n/utils/locale';

const { getOwner } = Ember;

moduleFor('service:i18n', 'Integration | translations', {
  integration: true
});

test('All locales have same amount of translation strings as default locale', function(assert) {
  const i18n = this.subject();
  const { defaultLocale } = config.i18n;
  const { translations: defaultTranslations } = new LocaleHelper(defaultLocale, i18n.get('container'));
  (...)
});
```

Just changing the `i18n.get('container')` above (see last line) to `getOwner(i18n)` made the test pass with flying colors.

Thank you very much, I'm closing this issue.
