### ISSUE TITLE
How to deal with genders?

### ISSUE THREAD

**Issue by IAmJulianAcosta** [jamesarosen/ember-i18n#408]
I'm trying to translate some things to spanish with has genders, but I can't find how to do this. Is this supported?

**Comment by jamesarosen** [comment]
Sadly, it's not. ember-i18n inherited its translation model from Rails, which only supported pluralization, not full [ICU Message](http://userguide.icu-project.org/formatparse/messages) strings.

You could override [`ember-i18n/utils/locale.prototype.findTranslation`](https://github.com/jamesarosen/ember-i18n/blob/b6afcd172d0c3176c7199b94a0f2bae7458f8364/addon/utils/locale.js#L63-L88) to handle inflection based on gender of the subject or object.

[ember-intl](https://github.com/jasonmit/ember-intl) _does_ support ICU Message format. Ideally, ember-i18n will eventually merge with that project.

**Comment by ieugen** [comment]
Use ICU MessageFormat style instead of this. It's industry standard and supports plurals and genders and all the likes. It has a JavaScript implementation https://messageformat.github.io/

**Comment by vvscode** [comment]
Hope this one https://github.com/jamesarosen/ember-i18n/pull/418 will be helpfull to redefine `Locale.prototype.findTranslation`

**Comment by jamesarosen** [comment]
jamesarosen/ember-i18n has been deprecated in favor of [ember-intl](https://github.com/ember-intl).
