### ISSUE TITLE
Transalting text in an input attribute

### ISSUE THREAD

**Issue by davideferre** [jamesarosen/ember-i18n#409]
The wiki is wrong where it explains how to translate a string into an input attribute, the correct way tu use a translation string is:
`<input name="email" placeholder=(t "login.email-placeholder")>`
and not:
`<input name="email" placeholder={{t "login.email-placeholder"}}>`
like the wiki says.

**Comment by jamesarosen** [comment]
Good catch! Can you update the wiki?

**Comment by davideferre** [comment]
Yes, updated!
