### ISSUE TITLE
pluralForm auto-generated by CLDR data

### ISSUE THREAD

**Issue by jasonmit** [jamesarosen/ember-i18n#411]
@jamesarosen I recently extracted out a broccoli plugin that was internal to ember-intl which is responsible for extracted the pluralization function out of CLDR data and making it accessible in the app or addon tree.

This could be used to remove having to manage pluralForm methods within  https://github.com/jamesarosen/ember-i18n/tree/master/addon/config/

https://github.com/jasonmit/broccoli-cldr-data

Are you opened to this idea?

**Comment by jamesarosen** [comment]
I used to maintain https://github.com/jamesarosen/CLDR.js, but abandoned it because (a) it didn't auto-generate the pluralizer functions from the CLDR repo and (b) it was tough to maintain the dependency in a pre-ember-cli world.

I'd be happy for that logic to be extracted again. One concern I've had with other pluralizer-generator libraries before is that they generate _massive_ amounts of code and try to support every language variant that the CLDR does.

Could we make an ember-addon for just the plural-form calculator library that wraps broccoli-cldr-data and exposes the results in a known service like `service:i18n-plurals` or something?

**Comment by jasonmit** [comment]
> they generate massive amounts of code and try to support every language variant that the CLDR does

Ember-intl avoids this by only including the locales the application is targeting (which is derives from the translations).  It can optionally be explicitly set for cases where the translations are not bundled within the project.

> Could we make an ember-addon for just the plural-form calculator library that wraps broccoli-cldr-data and exposes the results in a known service like service:i18n-plurals or something?

Unsure what you mean by for just the plural-form calculator library.

The broccoli plugin can be configured to _only_ include the plural methods, and they can be bundled with the app as modules (like they are today).

**Comment by jamesarosen** [comment]
> Unsure what you mean by for just the plural-form calculator library.

I guess I just meant exposing the plural-form rules as an ember module (service? utility?) in a standard way so ember-i18n can consume it -- and so consumers can override it if they don't want to use that pluralization library.

**Comment by icywolfy** [comment]
@jamesarosen I think thi biggest hurdle to that is that Ember plural rules are incompatible with CLDR plural rules.  

For instance: 
English in CLDR:  cardinal-one: "i = 1 && v = 0", ordinal-one="n%10 = 1 and n%100 != 11"
English in Ember:  one: "n = 1"
Thus, "1.0 days ago" will be mistransalted as singular "1.0 day ago"
And "Take the 2nd right" will be mistranslated as "plural" and never "two" or "few"
And Range plural-combination rules....  It will take "1-8 characters long" (resultant rule depends on combination and order of computed plural rule for start and end range. )
 

CLDR Supports Fractional plural rules, Ember currently does not.
Correct plural rule choice depends on visible number, not the numeric value.  
Thus, some languages will conjugate  0.4, 1.4, 1.04, 4, 14, 24 all the same (i % 10 = 4 && f % 10 = 4) 

To support automated transform, then ember will need to support all the values that are keyed off in CLDR.

To date, ember supports "n"
CLDR defines:
n: Absolute numeric value, integer and decimals
v: Visible number of fractional digits, with trailing 0s
w: Visible number of fractional digits, without trailing 0s
f: Visible fractional digits, with trailing 0s
t: Visible fractional digits, without trailing 0s.

Thus, to support this idea fully, one will need to implement the NumberFormat specifications from ICU, so number formatting can be resolved before plural rules can be calculated.  
This is why the ICU message format gets more complicated 
```
msgid_amount_remaining_label = " {amount_unit, select, metric { {amount_remaining, plural, one { There is # litre remaining in the jar } other {There are # litres remaining in the jar}, =0 {the jar is empty} }other {{amount_remaining, plural, one { There is # ounce remaining in the jar } other {There are # ounces remaining in the jar}, =0 {the jar is  empty}}";
numberFormmater = new DecimalFormatter(2); // 2 decimal places, rounded
messageFormatter.format(msgid_amount_remaining_label, numberFormatter);
```

**Comment by jamesarosen** [comment]
jamesarosen/ember-i18n has been deprecated in favor of [ember-intl](https://github.com/ember-intl).
