### ISSUE TITLE
Get the translation from another locale

### ISSUE THREAD

**Issue by pohodnya** [jamesarosen/ember-i18n#419]
Now it looks like this
```coffee 
currentLocale = @get('i18n.locale')
@set('i18n.locale', anotherLocale)
result = @get('i18n').t(key)
@set('i18n.locale', currentLocale)
```
Is it possible to specify a locale?
```coffee 
result = @get('i18n').t(key, { locale: anotherLocale })
```

**Comment by jamesarosen** [comment]
https://github.com/jamesarosen/ember-i18n/pull/381 reserves `locale` (and `htmlSafe`) as special keys in v4.x so that in v5.0 we can support this, be we haven't finished that migration. So it's planned, but I don't know when it will happen.

**Comment by nsharrok** [comment]
Yes please. I would like this very much too.
I want to create an edit page where the user can select and edit the translation of a product name for all the supported locals in a single web form.

**Comment by Fl0rianFischer** [comment]
If anyone wonders how to do this until it's officially implemented:

We wrote our own little service that would fetch new translation files and created our own translate method that closely resembles Ember.I18n ones:

`import compileTemplate from 'ember-i18n/utils/i18n/compile-template';

export default Service.extend({
  translations: {},

  t(key, data = {}, code) {
    const translation = this.get(`translations.${code}`);
    Ember.assert(`Translations for code ${code} not loaded`, !!translation);

    const resolvePath = (path, object) => {
      return path.split('.').reduce((prev, curr) => {
        return prev ? prev[curr] : undefined;
      }, object);
    };

    const template = resolvePath(key, translation);
    if (!template) return `Missing translations for ${key}`;

    const compiled = compileTemplate(template)(data);
    return compiled;
  }
});`

**Comment by jamesarosen** [comment]
jamesarosen/ember-i18n has been deprecated in favor of [ember-intl](https://github.com/ember-intl).
