### ISSUE TITLE
Allow locale changes without the need to be rebuilt

### ISSUE THREAD

**Issue by marioGomezDev** [jamesarosen/ember-i18n#420]
We have an app that we build with only one locale for each client, eventually our clients can modify some translations after build (they haven't the source code). 

Is it possible to allow locale changes without the need to be rebuilt?

Can we exclude locales from build code and take locales from assets for example?

I apologize for my poor english.

**Comment by jamesarosen** [comment]
You can add translations to the app at runtime, for example, after making an AJAX call to fetch them. See [Defining Translations at Runtime](https://github.com/jamesarosen/ember-i18n/wiki/Doc:-Defining-Translations#defining-translations-at-runtime)
