### ISSUE TITLE
Ember 2.10 - could not load module ember-metal/streams/stream

### ISSUE THREAD

**Issue by nerdyworm** [jamesarosen/ember-i18n#421]
Good Afternoon!

We took a crack at updating our ember app to 2.10 and ran into an issue with this file: https://github.com/jamesarosen/ember-i18n/blob/028c41bc89145a959a99caf8334712e26d6ac348/addon/legacy/stream.js

It seems that these imports are no longer available and cause the app to crash during the init phase.

Ripping out all of the legacy stuff allowed the app to boot correctly.

There were more errors, but it may be our stuff, not yours :grin:  Hopefully others can report their experiences here.

Cheers,
Benjamin

**Comment by rwjblue** [comment]
You need to update to 4.3.0 for Ember 2.10 support.

Discussed in release notes: https://github.com/jamesarosen/ember-i18n/releases/tag/v4.3.0

**Comment by nerdyworm** [comment]
Oh, a thousand apologies sir!  I swear I updated this package 😀 

![lol](https://cloud.githubusercontent.com/assets/230608/20777333/32be3ace-b71b-11e6-9a65-3e51ee6d7abe.jpg) <-- me upgrading our app today

Thanks.  I'll close this down and report back if I manage to break anything else.
