### ISSUE TITLE
Code parser 

### ISSUE THREAD

**Issue by karellm** [jamesarosen/ember-i18n#427]
Hi,

I wrote the [i18next-parser](https://github.com/i18next/i18next-parser) a while back. I've seen switched to Ember and currently looking into implementing i18n using this addon. I was wondering if this project had some sort of code parser to automatically populate the locale files?

From experience looking for the missing keys in the code is tedious and have a tool to automate the process is really neat especially as the project grows. I would be happy to port my project to ember if it isn't available at this point. Let me know if that would interest you (given you aren't already doing it).

**Comment by jamesarosen** [comment]
jamesarosen/ember-i18n has been deprecated in favor of [ember-intl](https://github.com/ember-intl).
