### ISSUE TITLE
multiple translations at the same time, on the same page

### ISSUE THREAD

**Issue by ngouy** [jamesarosen/ember-i18n#429]
Sorry, i'm sure i'm missing something somewhere, but i can not find a way to have multiple translations at the same time on the same page, regardless of `i18n.locale`.
There is no `locale` key to pass to `{{t .... }}` helper so we have  

`{{t 'hello' locale='en'}}/{{t 'hello' locale='es'}}/{{t 'hello' locale='fr'}}`
which could gives :
`hello/hola/bonjour`
 ?

**Comment by nsharrok** [comment]
see #419
Its only a hack but it got me what I needed

**Comment by jamesarosen** [comment]
jamesarosen/ember-i18n has been deprecated in favor of [ember-intl](https://github.com/ember-intl).
