### ISSUE TITLE
Error: Attempting to inject an unknown injection: 'service:i18n'

### ISSUE THREAD

**Issue by dmtask** [jamesarosen/ember-i18n#434]
Hi,

i have the following Problem with ember-i18n:
```
Error: Attempting to inject an unknown injection: 'service:i18n'
    at Registry.validateInjections (ember.debug.js:2303)
    at ember.debug.js:1538
    at runInDebug (ember.debug.js:5813)
    at Object.runInDebug (ember.debug.js:17396)
    at instantiate (ember.debug.js:1532)
    at lookup (ember.debug.js:1385)
    at Container.lookup (ember.debug.js:1304)
    at Class.lookup (ember.debug.js:32564)
    at Class._internalGetHandler (router-ext.js:107)
    at Class._getHandlerForEngine (router-ext.js:84)
```

I use the ember-i18n plugin in an ember engine. My i18n initializers `addon/instance-initializers/i18n.js`:
```
export default {
    name: 'i18n',

    initialize: function(applicationInstance) {
        const i18nService = applicationInstance.lookup('service:i18n');
        i18nService.set('defaultLocale', window.I18n.defaultLocale);
        i18nService.set('locale', window.I18n.locale);
    }
};
```

In my index route (`routes/index.js`) i have the following code:
```
import Ember from 'ember';

export default Ember.Route.extend({
    i18n: Ember.inject.service(),

    actions: {
        didTransition() {
            Ember.run.scheduleOnce('afterRender', this, function() {
                console.log(this.get('i18n').t('error_empty_user_data'));
                // ....
            });
        }
    }
});
```

How can I declare the i18n service?

I use the ember-18n 4.5.0 Version and the 2.10.0 ember-cli Version.

**Comment by locks** [comment]
Thanks for your question, I'm closing this in favor of http://stackoverflow.com/questions/42117557/error-attempting-to-inject-an-unknown-injection-servicei18n which seems to be getting some activity!

**Comment by vicky0203** [comment]
Hi,

I come across same issue when using ember-i18n in an **ember engine**. 
> Error: Attempting to inject an unknown injection: 'service:i18n'

And the answer above is not work for me.
I use ember-i18n 5.0.2 and ember-cli 2.16.2.

Any other configuration need to do?
