### ISSUE TITLE
A way to not fallback to "en" when there is not a default locale

### ISSUE THREAD

**Issue by viniciussbs** [jamesarosen/ember-i18n#438]
Hi,

In my app the default locale is different per company, so I set the locale only after fetching the company configs from the API. Since I don't have a default locale hard coded, I'm facing this warning.

> WARNING: ember-i18n did not find a default locale; falling back to "en"

How can I instruct i18n service for not use a fallback locale. I would like to avoid false positives.

**Comment by jamesarosen** [comment]
If ember-i18n didn't pick a default locale _and_ you don't set a locale, what would `i18n.t()` and the `{{t}}` helper do? Would they just throw an exception like "no locale set"?

**Comment by viniciussbs** [comment]
In my specific case, an exception would be good. If I don't set the locale, that will be a bug in my app. Right now ember-i18n hide this scenario setting the locale to "en".

**Comment by jamesarosen** [comment]
Could you set the default to `zz` or something else that doesn't exist?

**Comment by viniciussbs** [comment]
Since this is a corner case, I can go with that. I will set my server to reject request with header Accept-Language=zz.

**Comment by viniciussbs** [comment]
Actually, the server won't reject the request. `zz` will tell the server that I don't have a language preference and the server will choose the best fit for the current company.
