### ISSUE TITLE
Cannot read property 'class' of undefined after 5.0.0 update

### ISSUE THREAD

**Issue by bugduino** [jamesarosen/ember-i18n#440]
Hi,
after updating to v5.0.0 all my unit tests are failing like the following one
```
TypeError: Cannot read property 'class' of undefined
    at Locale._setConfig (http://localhost:4200/assets/vendor.js:123960:72)
    at Locale.rebuild (http://localhost:4200/assets/vendor.js:123946:12)
    at Locale (http://localhost:4200/assets/vendor.js:123940:10)
    at Class.<anonymous> (http://localhost:4200/assets/vendor.js:123825:23)
    at ComputedPropertyPrototype.get (http://localhost:4200/assets/vendor.js:29696:28)
    at Object.get (http://localhost:4200/assets/vendor.js:35348:19)
    at Class.get (http://localhost:4200/assets/vendor.js:49724:38)
    at Class.t (http://localhost:4200/assets/vendor.js:123759:25)
    at Class.callee$0$0$ (http://localhost:4200/assets/vendor.js:131695:95)
    at tryCatch (http://localhost:4200/assets/vendor.js:4374:40)
```

In my unit tests I have the following (which used to work before updating)

```
import tHelper from 'ember-i18n/helper';
import localeConfig from 'ember-i18n/config/en';

moduleForComponent('foo', 'Unit | Component | foo', {
  unit: true,
  needs: [
    'service:i18n',
    'locale:en/translations',
    'locale:en/config',
    'util:i18n/missing-message',
    'util:i18n/compile-template',
    'config:environment'
  ],
  beforeEach() {
    // set the locale and the config
    this.container.lookup('service:i18n').set('locale', 'en');
    this.registry.register('locale:en/config', localeConfig);

    // register t helper
    this.registry.register('helper:t', tHelper);
  }
});
```

Any ideas?

**Comment by gleseur** [comment]
Ran into the same issue and found a work around this, though not very satisfying.
You can add in the beforeEach


    this.registry.register('ember-i18n@config:zh', localeConfig);

Note the zh which is required no matter what language you're working with
It's not pretty but does the job

**Comment by j-a-m-l** [comment]
Similar problem here, but fails because `defaultConfig` is `undefined`. As @gleseur pointed is related to hardcoding `zh` (https://github.com/jamesarosen/ember-i18n/blob/dd5157db58fa230267bade5fc6543a3be0959037/addon/utils/locale.js#L32).

**Comment by jamesarosen** [comment]
Any idea why it only started happening in v5? `zh` has been the root configuration for a long time (because its options are shared by so many locales and has a very minimal `pluralForm`).

**Comment by xm** [comment]
@jamesarosen it must be a difference with how `_lookupFactory` and `factoryFor` behave

Diff with change:
https://github.com/jamesarosen/ember-i18n/commit/fe39fa218129393c5eed83d216f304635591e10a#diff-b7974a08aafd914ea5ff7f2731b64274

`_lookupFactory` source:
https://github.com/emberjs/ember.js/blob/ee8ab348484421f254fe995c6f04f0d4a0859cfa/packages/container/lib/container.js#L395-L448

`factoryFor` source:
https://github.com/emberjs/ember.js/blob/ee8ab348484421f254fe995c6f04f0d4a0859cfa/packages/container/lib/container.js#L214-L246

**Comment by jamesarosen** [comment]
@xm great catch. A simple fix to get back to old behavior:
```js
const defaultConfigFactory = this.owner.factoryFor('ember-i18n@config:zh');
const defaultConfig = defaultConfigFactory == null ? null : defaultConfigFactory.class;
```
Anyone want to submit a PR?

**Comment by xm** [comment]
@jamesarosen submitted one

**Comment by xm** [comment]
@jamesarosen is there a timeline for when a release with this fix for this will be published?

**Comment by jamesarosen** [comment]
v5.0.1 should have the fix and is published.

**Comment by xm** [comment]
👍 thanks!
