### ISSUE TITLE
Does it support cross browser such as IE?

### ISSUE THREAD

**Issue by woosungchu** [jamesarosen/ember-i18n#442]
I set translation filename like

```
app/locales/en/translation.js
app/locales/ko/translation.js
```

and caclculateLocale
```
function calculateLocale(locales) {
  // whatever you do to pick a locale for the user:
  const language = navigator.language || navigator.userLanguage;

  return  locales.includes(language) ? language : 'en-GB';
}
```

**I think this setting from docs doesn't support IE but work in chrome**
if you console 'navigator.lanuage' in each browser, it show different value 
```
navigator.language
//IE ->english
'ko-KR'
//chrome -> korean
'ko'
```

Do I miss additional setting or is it bug?
Of course I can add some logic for solve this problem, but I think document guide or source should be editted to prevent this kind of bug (if it is bug)

**Comment by jamesarosen** [comment]
`ko-KR` should fall back to `ko`, which you have defined.

Browsers are welcome to return any valid locale code, including `ko-KR`, `en`, `pt-BR-x-9`, or an infinite variety of others. They're also welcome to take into account whatever they want to do so, including your operating system preferences, browser preferences, location services, DNS, or anything else. Perhaps your IE is returning `ko-KR` because that's what your computer has it set to?

**Comment by woosungchu** [comment]
@jamesarosen 
Do you mean that 'ko-kr' in IE should come to 'ko' translation but it doesn't?
Or should I have to make new file for 'ko-kr'?

*thank you for kind explanation about browser local.

**Comment by jamesarosen** [comment]
I recommend reading about [Location Fallback](https://github.com/jamesarosen/ember-i18n/wiki/Doc:-Defining-Translations#location-fallback). Your app can define `app/locales/ko/translations.js` for general-purpose Korean and `app/locales/ko-kr/translations.js` (SK), `app/locales/ko-kp/translations.js` (NK), and `app/locales/ko-us/translations.js` (USA) for region-specific overrides. If the user's locale (however your app calculates it) is `ko-KR`, it will look for translations in `ko-kr` and fall back to those in `ko`.

**Comment by woosungchu** [comment]
@jamesarosen  
By your help, I get the role of location fallback but I think it is not working properly.

I have two locale setting 'en' and 'ko'.
At first, ember failed to find ko-KR in IE then it goes to default 'en-GB' and show english well.
It means location fallback working well (en-GB -> en O) but not in korean (ko-KR -> ko X)

what I expect in IE
- ko-KR ----> ko 
what happened actually
- ko-KR ----> en-GB(default) ----> en

**Comment by jamesarosen** [comment]
Good catch. Your browser is obeying the spec there; country codes in language tags are capitalized. But ember-cli uses all lowercase for module names. I thought ember-i18n handled mixed case properly, but I guess not.
