### ISSUE TITLE
HTMLElement support

### ISSUE THREAD

**Issue by jamesarosen** [jamesarosen/ember-i18n#443]
Problem: the current `{{t}}` helper and `I18n.t()` utility function don't allow interpolations to be `HTMLElement`s. That means I can't pass the result of a "well-behaved helper" as an interpolation to a translation.

Some thoughts:

 * We already allow users to pass in `htmlSafe: true|false` in the interpolations to control whether the result is marked as safe. This is done in [`I18n.t`](https://github.com/jamesarosen/ember-i18n/blob/2d67b472edba11ef17dd6436a9106fba650ee63b/addon/services/i18n.js#L29-L32)
 * We probably don't want `I18n.t()` to return an `HTMLElement`, at least not by default.
 * It's probably OK for the `{{t}}` helper to return an `HTMLElement` by default. It's conceivable that will break use of `(t ...)` sub-expressions when passing to another helper that doesn't understand `HTMLElement`s. That seems like a limitation of the other helper.
 * Perhaps we need three functions: `tString`, `tElement`, `tSafeString`
 * Currently we have a single compiler function that returns a `function(String, Object?) -> SafeString` compiled translation. We _could_ support `HTMLElement` interpolations by getting `.outerHTML` on each interpolation if the interpolation is an `HTMLElement`, but then we're throwing away the original node, copying it to a string, and rebuilding an element. I'd love the compiled template to support `HTMLElement` interpolations directly with `appendChild`. That suggests the compiled template should be of the form `function(String, Object?) -> HTMLElement`. We can convert to `String` by calling `.outerHTML` on the result or a `SafeString` by converting to `String` and then marking safe.

**Comment by jamesarosen** [comment]
@cibernox @workmanw @rwjblue I'd love your thoughts here.

**Comment by jamesarosen** [comment]
After a brief chat with @rwjblue, we may want to try using Glimmer to compile the translation templates into Glimmer wire-format. They would then accept other helpers and `HTMLElement` or component interpolations.

**Comment by sandstrom** [comment]
Some thoughts:

1. Is it possible for a helper to know if it's invoked as a subexpression? (I think not)
   
  It that was possible (perhaps after some change to Ember) we could use that to decide whether to return an element or not.

2. I agree that html element interpolation can be an issue, but in our app it's fairly uncommon. So although some type of support could be neat, I'm not sure if the default should be to emit elements (I'm sceptical to emitting an HTMLElement by default).

**Comment by jamesarosen** [comment]
jamesarosen/ember-i18n has been deprecated in favor of [ember-intl](https://github.com/ember-intl).
