### ISSUE TITLE
Any way to override /app/locales 

### ISSUE THREAD

**Issue by brianmglass** [jamesarosen/ember-i18n#446]
Hello!

Is there any way to override the default /app/locales/<locale> structure when importing translations? 

I'd like to add locales using a subfolder in vendor (i.e. /vendor/branding/<locale>) but there doesn't seem to be a way to override the default.  My thinking was to pull them in using a defined path in ember-cli-build without building an addon that manipulates and moves files into the locales default directory.  Hope that makes sense. 

Thanks

**Comment by workmanw** [comment]
You can call `addTranslations`on the `i18n` service. We actually load translations from the server on boot that, in some cases, are customer specific.

```
this.get('i18n').addTranslations('en', {
  'hello': 'world',
  'foo': 'bar'
});
```

So all you really need to do is just export a hash from the `vendor/branding/XXX` file, import it and call `addTranslations`. I'd say do this in an initializer.

**Comment by jamesarosen** [comment]
jamesarosen/ember-i18n has been deprecated in favor of [ember-intl](https://github.com/ember-intl).
