### ISSUE TITLE
Error: Compile Error: t is not a helper

### ISSUE THREAD

**Issue by perlun** [jamesarosen/ember-i18n#448]
Like in #434, I am also attempting to use the `ember-i18n` addon from an Ember Engine, unfortunately with little success thus far.

This is the error I am getting:

```
Error: Compile Error: t is not a helper
    at Helper.compile (ember.debug.js:53456)
    at OptimizedAppend.compile (ember.debug.js:52599)
    at compileStatement (ember.debug.js:50229)
    at ember.debug.js:50446
    at LinkedList.forEachNode (ember.debug.js:55279)
    at WrappedBuilder.compile (ember.debug.js:50445)
    at ComponentLayoutBuilder.compile (ember.debug.js:50338)
    at Object.compileLayout (ember.debug.js:50317)
    at Cache._emberMetal.Cache.owner [as func] (ember.debug.js:9254)
    at Cache.get (ember.debug.js:16628)
defaultDispatch @ ember.debug.js:18008
dispatchError @ ember.debug.js:17987
invokeWithOnError @ ember.debug.js:349
flush @ ember.debug.js:405
flush @ ember.debug.js:529
end @ ember.debug.js:599
run @ ember.debug.js:713
run @ ember.debug.js:22690
(anonymous) @ uxfactory-token-auth.js:17
mightThrow @ jquery.js:3583
process @ jquery.js:3651
```

Any way around this? `ember-i18n` is working correctly in the host application (the application in which the engine is being hosted)

**Comment by perlun** [comment]
Managed to work around it by adding an `addon/helpers/t.js` file with the following content:

```javascript
export { default } from 'ember-i18n/helper';
```

**Comment by jamesarosen** [comment]
I wonder whether some other addon is specifying an `app/helpers/t.js`

**Comment by perlun** [comment]
Weird, it worked now even when removing the t.js... Super strange! Closing the issue, sorry for wasting your time.

**Comment by NullVoxPopuli** [comment]
This error showed up for me, though I'm using i18n in an app (though, I'm using module unification way before release :-) )

hopefully I'm just doing something stupid
