### ISSUE TITLE
Duplicate locales when translations exist in main application and addon

### ISSUE THREAD

**Issue by GrandSlam90** [jamesarosen/ember-i18n#449]
This could easily be down to my implementation, but I think I've followed all the best practice.
I've developed a locale aware addon and put some translations into it.
Using the instance-initializers method, I know that they're being imported into the main application and are working.
The main application also has it's own set of translations for routes etc.
One of the addons is a language picker that uses the example code in the wiki to build a list of available translations and it's here I get the problem.
It appears that because I've got translations in the main application and in the vendor.js file that they're being treated separately so I end-up with duplicates where translations exist in both the app and addon.
It's not a massive issue, a quick dedupe function removes them but I'm sure I've gone wrong somewhere.
Thanks for a great addon, and I appreciate any help with the issue.

**Comment by jamesarosen** [comment]
jamesarosen/ember-i18n has been deprecated in favor of [ember-intl](https://github.com/ember-intl).
