### ISSUE TITLE
Which license file is valid?

### ISSUE THREAD

**Issue by ghost** [jamesarosen/ember-i18n#452]
I see there are 2 licenses in the root of this project. The MIT license appears to be newer but there's an Apache-2.0 license in there, which is also referenced from `package.json`.

Which license is correct, please? If it's just one of them would it be possible to remove the other and/or update `package.json`? Our org doesn't seem to like license ambiguity :)

**Comment by jamesarosen** [comment]
The last _intentional_ license change was to APLv2: #39. Can you open a PR make the project consistently reflect that?
