### ISSUE TITLE
Need testing docs for ember-cli-mocha

### ISSUE THREAD

**Issue by rajasegar-c** [jamesarosen/ember-i18n#456]
Since we are not using Qunit, it would be great to include information regarding writing Mocha unit, integration and acceptance tests with ember-i8n

**Comment by rajasegar-c** [comment]
Please find the sample repository here where the integration tests are failing
https://github.com/rajasegar/ember-i18n-mocha-test

**Comment by jamesarosen** [comment]
jamesarosen/ember-i18n has been deprecated in favor of [ember-intl](https://github.com/ember-intl).
