### ISSUE TITLE
How to define language names without duplication?

### ISSUE THREAD

**Issue by BogdanAlexandru** [jamesarosen/ember-i18n#460]
In the docs there's 
> Example: Language Chooser

which defines the labels of the options as `i18n.t('language-select.language.' + loc) `

which implies that each locale defines its own translations of the language name (label). For example:

```
/locales/en/translations.js
language-select.language.en: 'English',
language-select.language.fr: 'Français',
```

```
/locales/fr/translations.js
language-select.language.en: 'English',
language-select.language.fr: 'Français'
```

Is this duplication the only way to get correct language labels? With a single `languageName` definition inside each translation file, the only way to get what I wanted was to use this hack:

```
    let currentLocale = i18n.get('locale');
    let options = i18n.get('locales').map((item) => {
      i18n.set('locale', item);
      return {
        id: item,
        name: i18n.t('languageName')
      };
    });
    i18n.set('locale', currentLocale);
```

Am I missing something about how translations are handled, or am I entirely on the wrong path?

**Comment by jamesarosen** [comment]
jamesarosen/ember-i18n has been deprecated in favor of [ember-intl](https://github.com/ember-intl).
