### ISSUE TITLE
Adding a `scope` option

### ISSUE THREAD

**Issue by sandstrom** [jamesarosen/ember-i18n#463]
Would you be open to adding a scope option? Similar to [Rails :scope key on `t`](http://guides.rubyonrails.org/i18n.html#looking-up-translations).

A common use-case is templates, where the first parts of a key is static and the last part is dynamic.

```hbs
<div>
  <!-- With a scope option these would all lookup the same translation: -->
  {{t 'countries.names.de'}}
  {{t 'de' scope='countries.names'}}
  {{t countryKey scope='countries.names'}}
</div>
```

Without this we need a separate computed property on the component or a dedicated helper to concat the dynamic and static parts into a single translation key string.

**Comment by jamesarosen** [comment]
You'd have to first deprecate the key since people might be interpolating `{{scope}}`.

**Comment by sandstrom** [comment]
Alright, would you be open to adding deprecation for that key?

Do you have a timetable for the next major release, where we could add a breaking change such as this?

**Comment by jamesarosen** [comment]
jamesarosen/ember-i18n has been deprecated in favor of [ember-intl](https://github.com/ember-intl).
