### ISSUE TITLE
helper creates Ember.Object.extend().create()

### ISSUE THREAD

**Issue by mehulkar** [jamesarosen/ember-i18n#465]
https://github.com/jamesarosen/ember-i18n/blob/df616c0b1eb4f25b27d78cbc220e9a6a0b863d4d/addon/helper.js#L6-L11

The `t` helper is extending `Ember.Object` and then creating an object on every usage of the helper. I'm not *really* sure what is going on, but I found a strange bug where `Object.assign()` does't work as expected on `Ember.Object.extend().create()`.:

```js
Object.assign({}, Ember.Object.extend({foo: 'bar'}).create())
#=> {}

Object.assign({}, Ember.Object.create({foo: 'bar'}))
#=> {foo: 'bar'}
```

In my code, I'm using this Object.assign() to clone the data that comes into this method and it's causing strange problems.

I *think* we could use `Ember.Object.create()` directly in this method and then go chase down the underlying problem in Ember separately?

**Comment by mehulkar** [comment]
turns out that the Object.assign() behavior is probably correct, since Ember.Object.extend is adding properties to the prototype, Object.keys won't be able to loop over it. 

So, the only thing left to consider here is if ember-i18n should use Ember.Object.create() directly instead of extending

**Comment by jamesarosen** [comment]
I'd happily accept a PR for that :)

**Comment by mehulkar** [comment]
@jamesarosen submitted
