### ISSUE TITLE
Setting locale as described fails

### ISSUE THREAD

**Issue by belgoros** [jamesarosen/ember-i18n#472]
When trying to set a locale as described in [Wiki](https://github.com/jamesarosen/ember-i18n/wiki/Doc:-Setting-the-Locale):
```
# app/routes/application.js
import Route from '@ember/routing/route';

export default Route.extend({
  i18n: Ember.inject.service(),
    afterModel: function(user) {
      this.set('i18n.locale', user.get('locale'));
    }
});
```
it fails:
```
  4:9  error  'Ember' is not defined  no-undef

✖ 1 problem (1 error, 0 warnings)
```
Is the provided syntax outdated ?
 Here is my settings:
```
npm: 5.6.0
node: v8.9.1
ember-cli: 2.16.2
os: darwin x64
```
Thank you.

**Comment by jamesarosen** [comment]
Have you imported Ember into your file?

**Comment by belgoros** [comment]
@jamesarosen I just figured out how to do that the right way:
I figure out how to get it working:

1. Generate an instance initializer named i18n: `ember generate instance-initializer i18`
2. Modify if as follows:
```
export function initialize(applicationInstance) {
  let i18n = applicationInstance.lookup('service:i18n');
  i18n.set('locale', calculateLocale(i18n.get('locales')));
}

function calculateLocale(locales) {
  // whatever you do to pick a locale for the user:
  const language = navigator.languages[0] || navigator.language || navigator.userLanguage;

  return  locales.includes(language.toLowerCase()) ? language : 'en-GB';
}

export default {
  name: 'i18n',
  initialize
};
```
2. Declare the default locale in `config/environment.js`, for example, just before `if (environment === 'development') {` block:
```
// setting the default locale
  ENV.i18n = {
    defaultLocale: 'en'
  };
```

3. Generate the locales you need `ember generate locale your_locale` and add some translations:
for example, in my `locales/fr/translations.js`:
```
export default {
  "hello.user": "Bonjour, {{user}}"
};
```
4. Use translations in your template, for example, in `templates/application.hbs`:
```
<h3>{{t "hello.user" user="belgoros"}}</h3>
```
Now if you change the locale used by your browser, it works. Thank you.
