### ISSUE TITLE
require in get-locales clashes with other locally defined requires

### ISSUE THREAD

**Issue by danidr** [jamesarosen/ember-i18n#480]
Hello there,
I am using ember-i18n for an ember-electron app. I haven't updated it in a while, and gotten my hands on it only lately since the beginning of the year, while also updating to the `5.1.0` (latest version back then).
Well... my app broke when dynamically inserting translations from a `fs.readFile`-loaded file, with the `addTranslations` method. Hunting down the bug, the error is here, on the `get-locales` util.

[get-locales.js](https://github.com/jamesarosen/ember-i18n/commit/814bed8f026fabf6370ac2f6ef0003561555c1cf#diff-5dc3a0643834df4d59a527bd6407a8af)

My guess is that ember-electron already defines its own `require`, therefore breaking what ever `require` ember-i18n refers to. Maybe it's worth going back to `requirejs` as with before that commit? That would potentially avoid all conflicts with any other add-on.

**Comment by debelop13** [comment]
+1

**Comment by bummzack** [comment]
Got the same. Any pointers on how to resolve that?

**Comment by danidr** [comment]
@bummzack, I have solved the issue by manually editing utils/get-locales.js in node_modules, in the line where it reads `require`, to `requirejs`; it is an alias in a normal Ember environment, but in Ember-Electron it's the module that causes problems. See the note in the link I have posted above.

**Comment by bummzack** [comment]
@danidr Thanks for that info. I'm not too fond of editing the files in `node_modules` for obvious reasons. I think reverting to `5.0.2` is probably the fastest/cleanest approach for my needs.

**Comment by danidr** [comment]
@bummzack I definitely know what you mean. Let's wait for @jamesarosen to find a way to fix it elegantly :)

**Comment by jamesarosen** [comment]
`requirejs || require`?

**Comment by danidr** [comment]
Well, I guess it depends on what the reason was to switch from requirejs to require in the first place... does requirejs work in all cases?

**Comment by jamesarosen** [comment]
> the reason was to switch from requirejs to require

Calling @cibernox…

**Comment by brendanoh** [comment]
+1

**Comment by jamesarosen** [comment]
jamesarosen/ember-i18n has been deprecated in favor of [ember-intl](https://github.com/ember-intl).
