### ISSUE TITLE
Quest: intent to deprecate

### ISSUE THREAD

**Issue by jamesarosen** [jamesarosen/ember-i18n#481]
@jasonmit and I have [long](https://github.com/ember-intl/ember-intl/issues/109) [discussed](https://github.com/ember-intl/ember-intl/issues/545) [joining](https://github.com/jamesarosen/ember-i18n/issues/308) [forces](https://github.com/jamesarosen/ember-i18n/issues/411).

I think that ember-intl has a few major things going for it:

 1. it's based on the ICU message syntax
 1. it uses the browser-native `Intl` APIs (or a polyfill)
 1. it compiles translations at build-time

In that spirit, I'd like to deprecate ember-i18n in favor of ember-intl. At minimum, I think we should build a codemod. At EmberConf 2018 @mixonic [talked about lots of great codemods](https://youtu.be/qfnkDyHVJzs?t=23386). I think this would be a great case for such a tool. It should at least try to handle
   * moving translation files and reformatting from JSON to ICU
   * doing any necessary template modifications
   * moving global / default settings in `config/environment.js`

It might be nice to add a deprecation warning to ember-i18n and bumping the minor version. I don't think we should finalize the deprecation (in code or in README) until we have a codemod or alternate migration strategy.

**Comment by jamesarosen** [comment]
My opinion is that we should standardize on one internationalization library as a community, but others may wish for this library to live on. If we can find maintainers, I'm also happy to turn ember-i18n over.

**Comment by cibernox** [comment]
FWIW, I also think that `ember-intl` is the best solution for all the points mentioned above. It's much more capable as the native Intl API can do pretty much anything. I want to highlight some:

- Handle languages with 7 plurals
- Dormat dates, money, durations...
- Encode pretty complex logic in translations. This pseudolanguage is very powerful. P.e.
```
"{gender_of_host, select, "
  "female {"
    "{num_guests, plural, offset:1 "
      "=0 {{host} does not give a party.}"
      "=1 {{host} invites {guest} to her party.}"
      "=2 {{host} invites {guest} and one other person to her party.}"
      "other {{host} invites {guest} and # other people to her party.}}}"
  "male {"
    "{num_guests, plural, offset:1 "
      "=0 {{host} does not give a party.}"
      "=1 {{host} invites {guest} to his party.}"
      "=2 {{host} invites {guest} and one other person to his party.}"
      "other {{host} invites {guest} and # other people to his party.}}}"
  "other {"
    "{num_guests, plural, offset:1 "
      "=0 {{host} does not give a party.}"
      "=1 {{host} invites {guest} to their party.}"
      "=2 {{host} invites {guest} and one other person to their party.}"
      "other {{host} invites {guest} and # other people to their party.}}}}"
```

**Comment by karellm** [comment]
I was wondering if you guys ever considered something like `i18next`? I've used it for many years without ever hitting a limitation. It is supported in most languages. It has its own catalog format though that support context and plural. You can read a comparison from the author [here](https://medium.com/@jamuhl/i18n-frameworks-the-unfair-showdown-8d436cd6f470).

It offers some nice features like namespaces that I don't think are supported by either `ember-intl` or `ember-i18n` at the moment. It's a great way to load just what is needed in big apps. Eventually I'd love to see auto-namespacing and "distributed" locale files (à la `ember-css-modules` for css). There are also fallbacks that can sometime be useful.

I guess my concern here is do we need to reinvent the wheel when it comes to i18n?

**Comment by raido** [comment]
For me ember-intl seems to add more bundle size. I like the lightweight ember-i18n in that regard.

**Comment by Alonski** [comment]
Hey friends, do you know of a codemod/tool to migrate ember-i18n compatible json to ember-intl json?

**Comment by raido** [comment]
ember-intl adds 10KB (gzip) to vendor file + additional polyfill files.

While ember-i18n over here adds just 2.5KB (gzip).

I don't see myself switching at this point to ember-intl.

My current setup with [broccoli-json-module](https://yarnpkg.com/en/package/broccoli-json-module) + ember-i18n works well. My app/locales includes JSON files which broccoli-json-module compiles to ES6 modules.

**Comment by jamesarosen** [comment]
> I was wondering if you guys ever considered something like i18next?

`Intl` is actually part of the ECMAScript standard. I think that's one of the biggest selling points of ember-intl and the rest of the intl family.

> I guess my concern here is do we need to reinvent the wheel when it comes to i18n?

Exactly why I support ember-intl.

> ember-intl adds 10KB (gzip) to vendor file + additional polyfill files. While ember-i18n over here adds just 2.5KB (gzip).

That's concerning. I hope that by deprecating ember-i18n we can focus more of the community's attention on ember-intl, and I think download size and performance are great things to work on there.

> Hey friends, do you know of a codemod/tool to migrate ember-i18n compatible json to ember-intl json?

I don't know of one, but I'd love to see the community build one as part of the deprecation process.

**Comment by tschoartschi** [comment]
We are also using `ember-i18n` and are really satisfied with it. I've never tried `ember-intl` but I also think we (the community) should keep in mind to create a lightweight (or modularized and tree-shakeable) addons. My fear is that we (as a community) create a super powerful addon which can do everything but therefore is also super big. Another nice thing with `ember-i18n` is that we can add translations lazily during runtime. We have a lot of translations and we load them as JSON on demand. We prefer the translations to be JSON because JSON can be parsed quicker than JS and we think that it makes no sense to waste parsing time for translations. 

Nevertheless, I think it makes sense if the community agrees on standards and with joint forces, we can solve issues like the ones mentioned above easily. 

@jamesarosen thanks for the great work on `ember-i18n`. I'll miss it 😉

**Comment by jasonmit** [comment]
> I've never tried ember-intl but I also think we (the community) should keep in mind to create lightweight (or modularized and tree-shakeable) addons.

ember-intl can be split up into modules (number formatting, datetime formatting, relative time formatting, translations).  Should not require much work and the benefit being users can opt into only native APIs built right into the browser (excluding message parser).

The message parser itself is lightweight and that too could maybe one day be swappable to a custom parser that fits ember-i18ns format.  I've never explored that but that's sort of what is exciting about this, we can experiment and build something awesome together.

>My fear is that we (as a community) create a super powerful addon which can do everything but therefore is also super big.

Above response should answer that.  It can be split up.

> Another nice thing with ember-i18n is that we can add translations lazily during runtime. We have a lot of translations and we load them as JSON on demand. We prefer the translations to be JSON because JSON can be parsed quicker than JS and we think that it makes no sense to waste parsing time for translations.

ember-intl supports loading translations at runtime along with storing your translations in yaml or json (no configuration required, just rename the translation to either).

**Comment by NullVoxPopuli** [comment]
is there a migration guide / tool? for going to ember-intl?
(I'm also using module unification on ember-canary, so I've had to do some hacks to get ember-i18n working)

**Comment by cibernox** [comment]
@NullVoxPopuli It's not ready for production, but we did this today. I hope it will be finished next week: https://github.com/DockYard/ember-i18n-to-intl-migrator

**Comment by NullVoxPopuli** [comment]
Man, DockYard is my hero

**Comment by 0xadada** [comment]
@cibernox i'm interested in that migrator, where'd the URL go?

**Comment by cibernox** [comment]
@0xadada oops, the repo was still private. I just made it public: https://github.com/DockYard/ember-i18n-to-intl-migrator

**Comment by iezer** [comment]
@cibernox This migrator looks great. It's hard to tell how far along it is because there are no tests for the translation file migrator. I'd be happy to help add some. I also created a simple app to give it a try. https://github.com/iezer/ember-i18n-to-intl-migrator-test

Are there any outstanding tasks that need to be addressed in the migrator? Also does anyone know of any large open source Ember apps that use ember-i18n and could be used to test the migrator and find some edge cases that may need addressing?

**Comment by cibernox** [comment]
I don't know about large OS apps that are internationalized, but at DY we have a few internal ones. I believe there isn't any outstanding work to do, but @snewcomer did the work here, I delegate to him.

**Comment by jamesarosen** [comment]
jamesarosen/ember-i18n has been deprecated in favor of [ember-intl](https://github.com/ember-intl).

**Comment by jacobq** [comment]
To anyone else who finds this issue while looking for an easy migration solution: please let me know if you find a working codemod / tool. I just stumbled upon https://github.com/DockYard/ember-i18n-to-intl-migrator and am about to see if it works...
