### ISSUE TITLE
Pluralized do not behave always the same way

### ISSUE THREAD

**Issue by cbou** [jamesarosen/ember-i18n#484]
There seems to be a fallback for non defined pluralized strings.

```
t('prototypes.defaultNewPrototypeName', {count: 3})
    Missing translation: prototypes.defaultNewPrototypeName {count: 3}
 => SafeString {string: "My project"}
t('prototypes.defaultNewPrototypeName', {count: 0})
 => SafeString {string: "My first project"}
t('prototypes.defaultNewPrototypeName', {count: 3})
 => SafeString {string: "My first project"}
```

Is that a wanted behaviour? 

It's hard to predict which translation will be returned because it depends on which string were already translated.

**Comment by jamesarosen** [comment]
Can you show the relevant translations? Do you have multiple locales? What version are you using?

Given `'prototypes.defaultNewPrototypeName', {count: 3}`, ember-i18n doesn't know whether you have translations like
```js
prototypes:
  defaultNewPrototypeName: 'something with {{count}}'
```
or like
```js
prototypes:
  defaultNewPrototypeName:
    one: 'one new default property name'
    other: '{{count}} new default property names'
```
So it first looks for `prototypes.defaultNewPropertyName.other`, then falls back to `prototypes.defaultNewPropertyName`.

We'll need more of your setup to be able to replicate the failure.

**Comment by cbou** [comment]
As you said, I think it's related to my setup.

I play a bit with a twiddle and it seems to be ok: https://ember-twiddle.com/#/910eefc652a09838b15674ffe8e39cd3

I will reopen the issue if I find an error I can't explain.

**Comment by cbou** [comment]
Thanks!

**Comment by cbou** [comment]
Sorry, now I was able to reproduce the issue.

https://ember-twiddle.com/910eefc652a09838b15674ffe8e39cd3

```
    console.log(this.get('i18n').t('plural', {count: 1}).toString()); // Missing translation: plural
    console.log(this.get('i18n').t('plural', {count: 0}).toString()); // Zero plural
    console.log(this.get('i18n').t('plural', {count: 1}).toString()); // Zero plural
```

**Comment by jamesarosen** [comment]
I won't be able to look into this in the near future, but I hope that this excellent reproduction will make it easy for the community to solve :)

**Comment by tehmaestro** [comment]
The problem is that both `_defineMissingTranslationTemplate` and `_compileTemplate` set `this.translations[key] = something;` and they do not take into account `inflection` generated by `pluralForm` , I think :)

**Comment by jamesarosen** [comment]
jamesarosen/ember-i18n has been deprecated in favor of [ember-intl](https://github.com/ember-intl).
