### ISSUE TITLE
Call a translation key dynamically

### ISSUE THREAD

**Issue by belgoros** [jamesarosen/ember-i18n#485]
Is it possible to interpolate a value in a template to get the corresponding translation key ?
For example, I have a dynamic value for a day as `monday`. In `translations.js` I define all the week days:
```
'weekdays': {
    'sunday': 'Sunday',
    'monday': 'Monday',
    'tuesday': 'Tuesday',
    'wednesday': 'Wednesday',
    'thursday': 'Thursday',
    'friday': 'Friday',
    'saturday': 'Saturday'
  },
````
In the template I'd like to concatenate the value `monday`to get its translation:
```
<label>{{weekdays.}} ????? HERE the value to concatenate</label>
Thank you.

**Comment by jamesarosen** [comment]
How about
```hbs
{{t (concat 'weekdays.' someDay)}}
```

**Comment by belgoros** [comment]
Yes, I knew that way, thank you. I believed that there was another more elegant way to achieve that, so that to avoid putting some logic into the template.
