### ISSUE TITLE
Dynamic update of <html lang="en"> with FastBoot support

### ISSUE THREAD

**Issue by daniel-de-wit** [jamesarosen/ember-i18n#488]
How do I dynamically update the language attribute of the html tag:`<html lang="en">`?

**Comment by lifeart** [comment]
@daniel-de-wit `document.head.parentElement.setAttribute('lang','ru')`

**Comment by daniel-de-wit** [comment]
@lifeart Thanks, I was hoping for a built-in solution that works with FastBoot as well. I've should have made that more clear, I updated the title.

Using an instance-initializer I seem to get it working:

```
export default {
    after: 'ember-i18n',
    name: 'set-app-locale',

    initialize(application) {
        application.lookup('service:-document').documentElement.setAttribute('lang', 'nl');
    },
};

```
