### ISSUE TITLE
;import Service from "ember-i18n/service";

### ISSUE THREAD

**Issue by tomaszs** [jamesarosen/ember-i18n#493]
When using ember-18n it is compiled into vendor.js with a semicolon on the beginning:

;import Service from "ember-i18n/service";

And it breaks the app. Why is this happening and how to fix it?

**Comment by jamesarosen** [comment]
I wouldn't expect to see `import` in `vendor.js`. I'm guessing Babel isn't transpiling some files that it should be. This sounds like a problem with ember-cli or your ember-cli configuration.

**Comment by jamesarosen** [comment]
jamesarosen/ember-i18n has been deprecated in favor of [ember-intl](https://github.com/ember-intl).
