### ISSUE TITLE
Double HTML encoding

### ISSUE THREAD

**Issue by sebastianseilund** [jamesarosen/ember-i18n#77]
When using the `Ember.I18n.t` function, the output is HTML encoded. This is a problem if a property that returns a result from `Ember.I18n.t` is bound in a template.

JS: 

``` javascript
title: function() {
  if (this.get('state') === 'draft') {
    return Ember.I18n.t('invoice.index.title_draft', {contactName: this.get('contact.name')});
  } else {
    return Ember.I18n.t('invoice.index.title_draft', {contactName: this.get('contact.name')});
  }
}.property('state', 'contact.name')
```

Template:

``` hbs
<h1>{{title}}</h1>
```

Example of resulting HTML if `contact.name` is `Billy's Billing`:

``` html
<h1>Draft invoice for Billy&amp;#x27;s Billing</h1>
```

= The apostrophe is doubly encoded.

In my opinion, the result from `Ember.I18n.t` should not be HTML encoded.

Any ideas?

**Comment by harianus** [comment]
For people that are reading this later.

You can indeed just use `Handlebars.SafeString`. The [above two described problems](https://github.com/jamesarosen/ember-i18n/issues/77#issuecomment-25258182) you can easily solve by using this:

```js
window.alert(Ember.I18n.t('hello {{name}}', {name: new Handlebars.SafeString('Billy\'s Billing')}))
```

```js
$.post('/emails', {subject: Ember.I18n.t('hello {{name}}', {name: new Handlebars.SafeString('Billy\'s Billing')})})
```
