### ISSUE TITLE
Interpolating a helper

### ISSUE THREAD

**Issue by briarsweetbriar** [jamesarosen/ember-i18n#79]
I'm assuming this isn't possible, but I wanted to check. Is there a way to interpolate a helper, such as `link-to`? To do something like:

```
t organizations.versions.submitted userLinkBinding="#link-to 'user' user"
```

**Comment by sluchznak** [comment]
Hello. Please, tell me, hoe can i work with link-to helper in ember 2.3:
I thought `{{t "forms.register.login-link" link=(link-to (t 'forms.login.title') 'login')}}` is should work, but doesn't

**Comment by jamesarosen** [comment]
The problem in this case is that `link-to` doesn't emit a string or even a `Handlebars.SafeString`. It's a very complex helper that manages DOM state. Unfortunately, Ember doesn't provide an easy way to generate a link -- or even an `href` from the router -- as a String.

**Comment by danidr** [comment]
Hello,
I am having the same problem with a quite complex multi-language website I'm developing.
I have a suggestion: wouldn't it be possible to output directly in HTMLBars.compile (or HTMLBars.render) from the T helper? I would guess there MUST be a solution to output DOM elements directly into the template from helpers.
This would allow the use of any kind of HTMLBars syntax inside the translation text; possibly changing the syntax for interpolated values, which at this point, could even be handled by simply passing the scope as a parameter, and setting the interpolated value directly in the template (or component) that calls the T helper or method.
Makes sense?

**Comment by jamesarosen** [comment]
> wouldn't it be possible to output directly in HTMLBars.compile (or HTMLBars.render) from the T helper

It might... if _all_ of your translation happens at the template layer. But it wouldn't work if you wanted to do any translations in a component

```js
export default Ember.Component.extend({
  foo: 'bar',

  fooText: Ember.computed('i18n.locale', function() {
    return this.get('i18n').t(`some.foo.${this.get('foo')}`);
  }
});
```
because HTMLBars doesn't exist there. There's no DOM on which it could operate.
