### ISSUE TITLE
"Global redraw" mode

### ISSUE THREAD

**Issue by johnnyshields** [jamesarosen/ember-i18n#96]
Hi, I'm new to Ember, so please pardon if I've misunderstood anything.

As I understand it, using `Em.I18n.t` binds a listener on the given HTML text field such that when I18n locale changes, the text is automatically updated.

I have an app with many I18n keys that I'd like to optimize for speed. Rather than binding each text field individually, I'd like text values to be drawn without a binding and have I18n locale change trigger a global redraw. The thinking is that locale changes are very infrequent, so binding each field is wasteful.

So my questions are:

1) Have I understood the ember-i18n design correctly?

2) Is it possible to do the global redraw as I have suggested with ember-i18n? If not, are there any other projects which behave in this manner?

**Comment by jamesarosen** [comment]
v4.0 alpha (see #213) has live bindings on locale.
